
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem some_prob)
    (:domain satellite)

    (:objects
        
    )

    (:init
        
    )

    (:goal
        (and )
    )

    
    
    
)

