(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite2 - satellite
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite4 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	thermograph4 - mode
	thermograph3 - mode
	image1 - mode
	thermograph0 - mode
	thermograph2 - mode
	star4 - direction
	groundstation2 - direction
	star0 - direction
	star1 - direction
	star3 - direction
	phenomenon5 - direction
	planet6 - direction
	planet7 - direction
	star8 - direction
	star9 - direction
	star10 - direction
	planet11 - direction
	phenomenon12 - direction
	phenomenon13 - direction
	planet14 - direction
	star15 - direction
	phenomenon16 - direction
	phenomenon17 - direction
	phenomenon18 - direction
	planet19 - direction
	planet20 - direction
	phenomenon21 - direction
	star22 - direction
	planet23 - direction
	phenomenon24 - direction
)
(:init
	(supports instrument0 thermograph4)
	(supports instrument0 thermograph0)
	(supports instrument0 thermograph2)
	(calibration_target instrument0 star4)
	(supports instrument1 thermograph3)
	(calibration_target instrument1 star0)
	(supports instrument2 image1)
	(calibration_target instrument2 star4)
	(supports instrument3 image1)
	(supports instrument3 thermograph0)
	(supports instrument3 thermograph3)
	(calibration_target instrument3 star3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 star8)
	(supports instrument4 image1)
	(calibration_target instrument4 groundstation2)
	(supports instrument5 thermograph4)
	(supports instrument5 image1)
	(calibration_target instrument5 star1)
	(supports instrument6 thermograph3)
	(supports instrument6 thermograph2)
	(calibration_target instrument6 star0)
	(supports instrument7 thermograph0)
	(supports instrument7 thermograph2)
	(calibration_target instrument7 groundstation2)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(power_avail satellite1)
	(pointing satellite1 phenomenon17)
	(supports instrument8 image1)
	(supports instrument8 thermograph0)
	(calibration_target instrument8 star3)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 planet20)
	(supports instrument9 thermograph0)
	(calibration_target instrument9 star1)
	(supports instrument10 thermograph3)
	(supports instrument10 image1)
	(supports instrument10 thermograph0)
	(calibration_target instrument10 star1)
	(supports instrument11 thermograph0)
	(supports instrument11 image1)
	(calibration_target instrument11 groundstation2)
	(supports instrument12 image1)
	(calibration_target instrument12 star4)
	(supports instrument13 thermograph0)
	(calibration_target instrument13 groundstation2)
	(supports instrument14 thermograph2)
	(supports instrument14 thermograph4)
	(supports instrument14 thermograph0)
	(calibration_target instrument14 star1)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(power_avail satellite3)
	(pointing satellite3 planet19)
	(supports instrument15 thermograph3)
	(supports instrument15 thermograph0)
	(supports instrument15 thermograph4)
	(calibration_target instrument15 star1)
	(supports instrument16 thermograph0)
	(supports instrument16 thermograph3)
	(supports instrument16 thermograph4)
	(calibration_target instrument16 star0)
	(supports instrument17 thermograph3)
	(supports instrument17 thermograph0)
	(calibration_target instrument17 star3)
	(supports instrument18 image1)
	(calibration_target instrument18 star1)
	(supports instrument19 thermograph2)
	(supports instrument19 thermograph0)
	(calibration_target instrument19 star3)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(power_avail satellite4)
	(pointing satellite4 star3)
)
(:goal (and
	(pointing satellite1 star1)
	(pointing satellite4 planet23)
	(have_image phenomenon5 thermograph4)
	(have_image planet7 image1)
	(have_image star8 thermograph3)
	(have_image star9 image1)
	(have_image star10 image1)
	(have_image phenomenon13 thermograph2)
	(have_image star15 thermograph2)
	(have_image phenomenon17 thermograph4)
	(have_image phenomenon18 image1)
	(have_image planet19 thermograph2)
	(have_image planet20 thermograph4)
	(have_image phenomenon21 image1)
	(have_image star22 thermograph3)
))

)
