(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite1 - satellite
	instrument9 - instrument
	satellite2 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite3 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite4 - satellite
	instrument26 - instrument
	infrared5 - mode
	thermograph0 - mode
	image1 - mode
	thermograph2 - mode
	image6 - mode
	thermograph7 - mode
	thermograph4 - mode
	thermograph3 - mode
	star0 - direction
	groundstation1 - direction
	groundstation3 - direction
	groundstation4 - direction
	groundstation2 - direction
	planet5 - direction
	planet6 - direction
	phenomenon7 - direction
	phenomenon8 - direction
	star9 - direction
	star10 - direction
	star11 - direction
	star12 - direction
	planet13 - direction
	phenomenon14 - direction
	planet15 - direction
	planet16 - direction
	phenomenon17 - direction
	planet18 - direction
	phenomenon19 - direction
	planet20 - direction
	phenomenon21 - direction
	star22 - direction
	planet23 - direction
	phenomenon24 - direction
)
(:init
	(supports instrument0 thermograph4)
	(supports instrument0 image6)
	(calibration_target instrument0 groundstation1)
	(supports instrument1 image6)
	(calibration_target instrument1 groundstation4)
	(supports instrument2 thermograph4)
	(supports instrument2 thermograph2)
	(supports instrument2 thermograph7)
	(calibration_target instrument2 groundstation1)
	(supports instrument3 thermograph7)
	(supports instrument3 thermograph3)
	(calibration_target instrument3 groundstation3)
	(supports instrument4 image1)
	(calibration_target instrument4 groundstation3)
	(supports instrument5 thermograph3)
	(calibration_target instrument5 star0)
	(supports instrument6 thermograph2)
	(calibration_target instrument6 groundstation2)
	(supports instrument7 thermograph2)
	(supports instrument7 infrared5)
	(calibration_target instrument7 star0)
	(supports instrument8 thermograph4)
	(calibration_target instrument8 groundstation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(power_avail satellite0)
	(pointing satellite0 planet16)
	(supports instrument9 thermograph3)
	(supports instrument9 thermograph2)
	(calibration_target instrument9 groundstation1)
	(on_board instrument9 satellite1)
	(power_avail satellite1)
	(pointing satellite1 planet18)
	(supports instrument10 thermograph7)
	(calibration_target instrument10 groundstation2)
	(supports instrument11 thermograph2)
	(supports instrument11 image1)
	(supports instrument11 infrared5)
	(calibration_target instrument11 groundstation3)
	(supports instrument12 thermograph2)
	(calibration_target instrument12 groundstation3)
	(supports instrument13 thermograph3)
	(supports instrument13 thermograph4)
	(calibration_target instrument13 star0)
	(supports instrument14 image6)
	(calibration_target instrument14 groundstation2)
	(supports instrument15 thermograph3)
	(calibration_target instrument15 groundstation1)
	(supports instrument16 thermograph3)
	(calibration_target instrument16 groundstation1)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(power_avail satellite2)
	(pointing satellite2 phenomenon8)
	(supports instrument17 thermograph3)
	(calibration_target instrument17 groundstation2)
	(supports instrument18 thermograph3)
	(supports instrument18 thermograph2)
	(supports instrument18 infrared5)
	(calibration_target instrument18 groundstation2)
	(supports instrument19 image1)
	(supports instrument19 thermograph4)
	(supports instrument19 infrared5)
	(calibration_target instrument19 groundstation1)
	(supports instrument20 thermograph3)
	(supports instrument20 thermograph0)
	(calibration_target instrument20 groundstation4)
	(supports instrument21 image6)
	(supports instrument21 image1)
	(calibration_target instrument21 star0)
	(supports instrument22 infrared5)
	(supports instrument22 thermograph7)
	(calibration_target instrument22 star0)
	(supports instrument23 image1)
	(supports instrument23 thermograph4)
	(supports instrument23 thermograph0)
	(calibration_target instrument23 groundstation1)
	(supports instrument24 thermograph4)
	(supports instrument24 image6)
	(supports instrument24 thermograph2)
	(calibration_target instrument24 groundstation3)
	(supports instrument25 thermograph3)
	(supports instrument25 thermograph4)
	(supports instrument25 thermograph7)
	(calibration_target instrument25 groundstation4)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(power_avail satellite3)
	(pointing satellite3 phenomenon8)
	(supports instrument26 thermograph3)
	(calibration_target instrument26 groundstation2)
	(on_board instrument26 satellite4)
	(power_avail satellite4)
	(pointing satellite4 planet15)
)
(:goal (and
	(have_image planet5 image6)
	(have_image planet6 thermograph4)
	(have_image planet6 thermograph0)
	(have_image phenomenon8 thermograph0)
	(have_image phenomenon8 thermograph7)
	(have_image star9 image1)
	(have_image star10 infrared5)
	(have_image star10 image1)
	(have_image star11 infrared5)
	(have_image star11 thermograph3)
	(have_image star12 infrared5)
	(have_image planet13 thermograph3)
	(have_image phenomenon14 thermograph0)
	(have_image phenomenon14 image6)
	(have_image planet15 image1)
	(have_image planet16 image1)
	(have_image phenomenon17 infrared5)
	(have_image phenomenon17 thermograph7)
	(have_image planet18 image1)
	(have_image planet18 infrared5)
	(have_image planet20 thermograph7)
	(have_image phenomenon21 thermograph7)
	(have_image star22 thermograph4)
	(have_image star22 thermograph7)
	(have_image planet23 infrared5)
	(have_image phenomenon24 thermograph4)
	(have_image phenomenon24 thermograph2)
))

)
