(define (problem roverprob5932) (:domain rover)
(:objects
	general - lander
	colour high_res low_res - mode
	rover0 rover1 rover2 rover3 rover4 rover5 rover6 rover7 rover8 rover9 - rover
	rover0store rover1store rover2store rover3store rover4store rover5store rover6store rover7store rover8store rover9store - store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 waypoint40 waypoint41 waypoint42 waypoint43 waypoint44 waypoint45 waypoint46 waypoint47 waypoint48 waypoint49 - waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 camera11 camera12 camera13 camera14 camera15 - camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - objective
	)
(:init
	(visible waypoint0 waypoint20)
	(visible waypoint20 waypoint0)
	(visible waypoint0 waypoint26)
	(visible waypoint26 waypoint0)
	(visible waypoint0 waypoint28)
	(visible waypoint28 waypoint0)
	(visible waypoint1 waypoint0)
	(visible waypoint0 waypoint1)
	(visible waypoint1 waypoint13)
	(visible waypoint13 waypoint1)
	(visible waypoint1 waypoint16)
	(visible waypoint16 waypoint1)
	(visible waypoint1 waypoint37)
	(visible waypoint37 waypoint1)
	(visible waypoint1 waypoint38)
	(visible waypoint38 waypoint1)
	(visible waypoint2 waypoint15)
	(visible waypoint15 waypoint2)
	(visible waypoint2 waypoint17)
	(visible waypoint17 waypoint2)
	(visible waypoint2 waypoint28)
	(visible waypoint28 waypoint2)
	(visible waypoint2 waypoint44)
	(visible waypoint44 waypoint2)
	(visible waypoint3 waypoint28)
	(visible waypoint28 waypoint3)
	(visible waypoint3 waypoint31)
	(visible waypoint31 waypoint3)
	(visible waypoint3 waypoint36)
	(visible waypoint36 waypoint3)
	(visible waypoint3 waypoint46)
	(visible waypoint46 waypoint3)
	(visible waypoint4 waypoint3)
	(visible waypoint3 waypoint4)
	(visible waypoint4 waypoint5)
	(visible waypoint5 waypoint4)
	(visible waypoint4 waypoint7)
	(visible waypoint7 waypoint4)
	(visible waypoint4 waypoint21)
	(visible waypoint21 waypoint4)
	(visible waypoint4 waypoint22)
	(visible waypoint22 waypoint4)
	(visible waypoint4 waypoint26)
	(visible waypoint26 waypoint4)
	(visible waypoint5 waypoint8)
	(visible waypoint8 waypoint5)
	(visible waypoint5 waypoint10)
	(visible waypoint10 waypoint5)
	(visible waypoint5 waypoint12)
	(visible waypoint12 waypoint5)
	(visible waypoint5 waypoint17)
	(visible waypoint17 waypoint5)
	(visible waypoint5 waypoint39)
	(visible waypoint39 waypoint5)
	(visible waypoint5 waypoint42)
	(visible waypoint42 waypoint5)
	(visible waypoint5 waypoint46)
	(visible waypoint46 waypoint5)
	(visible waypoint5 waypoint49)
	(visible waypoint49 waypoint5)
	(visible waypoint6 waypoint8)
	(visible waypoint8 waypoint6)
	(visible waypoint6 waypoint9)
	(visible waypoint9 waypoint6)
	(visible waypoint6 waypoint10)
	(visible waypoint10 waypoint6)
	(visible waypoint6 waypoint13)
	(visible waypoint13 waypoint6)
	(visible waypoint6 waypoint22)
	(visible waypoint22 waypoint6)
	(visible waypoint6 waypoint25)
	(visible waypoint25 waypoint6)
	(visible waypoint6 waypoint45)
	(visible waypoint45 waypoint6)
	(visible waypoint7 waypoint9)
	(visible waypoint9 waypoint7)
	(visible waypoint7 waypoint13)
	(visible waypoint13 waypoint7)
	(visible waypoint7 waypoint44)
	(visible waypoint44 waypoint7)
	(visible waypoint8 waypoint3)
	(visible waypoint3 waypoint8)
	(visible waypoint8 waypoint10)
	(visible waypoint10 waypoint8)
	(visible waypoint8 waypoint13)
	(visible waypoint13 waypoint8)
	(visible waypoint8 waypoint21)
	(visible waypoint21 waypoint8)
	(visible waypoint8 waypoint29)
	(visible waypoint29 waypoint8)
	(visible waypoint8 waypoint47)
	(visible waypoint47 waypoint8)
	(visible waypoint9 waypoint12)
	(visible waypoint12 waypoint9)
	(visible waypoint9 waypoint14)
	(visible waypoint14 waypoint9)
	(visible waypoint9 waypoint30)
	(visible waypoint30 waypoint9)
	(visible waypoint9 waypoint35)
	(visible waypoint35 waypoint9)
	(visible waypoint10 waypoint27)
	(visible waypoint27 waypoint10)
	(visible waypoint10 waypoint28)
	(visible waypoint28 waypoint10)
	(visible waypoint10 waypoint37)
	(visible waypoint37 waypoint10)
	(visible waypoint10 waypoint41)
	(visible waypoint41 waypoint10)
	(visible waypoint11 waypoint0)
	(visible waypoint0 waypoint11)
	(visible waypoint11 waypoint3)
	(visible waypoint3 waypoint11)
	(visible waypoint11 waypoint14)
	(visible waypoint14 waypoint11)
	(visible waypoint11 waypoint40)
	(visible waypoint40 waypoint11)
	(visible waypoint12 waypoint13)
	(visible waypoint13 waypoint12)
	(visible waypoint12 waypoint32)
	(visible waypoint32 waypoint12)
	(visible waypoint12 waypoint40)
	(visible waypoint40 waypoint12)
	(visible waypoint12 waypoint44)
	(visible waypoint44 waypoint12)
	(visible waypoint13 waypoint29)
	(visible waypoint29 waypoint13)
	(visible waypoint13 waypoint43)
	(visible waypoint43 waypoint13)
	(visible waypoint14 waypoint1)
	(visible waypoint1 waypoint14)
	(visible waypoint14 waypoint31)
	(visible waypoint31 waypoint14)
	(visible waypoint14 waypoint43)
	(visible waypoint43 waypoint14)
	(visible waypoint14 waypoint49)
	(visible waypoint49 waypoint14)
	(visible waypoint15 waypoint11)
	(visible waypoint11 waypoint15)
	(visible waypoint15 waypoint12)
	(visible waypoint12 waypoint15)
	(visible waypoint15 waypoint17)
	(visible waypoint17 waypoint15)
	(visible waypoint15 waypoint24)
	(visible waypoint24 waypoint15)
	(visible waypoint15 waypoint33)
	(visible waypoint33 waypoint15)
	(visible waypoint15 waypoint41)
	(visible waypoint41 waypoint15)
	(visible waypoint16 waypoint15)
	(visible waypoint15 waypoint16)
	(visible waypoint16 waypoint21)
	(visible waypoint21 waypoint16)
	(visible waypoint16 waypoint24)
	(visible waypoint24 waypoint16)
	(visible waypoint16 waypoint41)
	(visible waypoint41 waypoint16)
	(visible waypoint16 waypoint49)
	(visible waypoint49 waypoint16)
	(visible waypoint17 waypoint7)
	(visible waypoint7 waypoint17)
	(visible waypoint17 waypoint22)
	(visible waypoint22 waypoint17)
	(visible waypoint17 waypoint39)
	(visible waypoint39 waypoint17)
	(visible waypoint18 waypoint12)
	(visible waypoint12 waypoint18)
	(visible waypoint18 waypoint35)
	(visible waypoint35 waypoint18)
	(visible waypoint19 waypoint5)
	(visible waypoint5 waypoint19)
	(visible waypoint19 waypoint11)
	(visible waypoint11 waypoint19)
	(visible waypoint19 waypoint17)
	(visible waypoint17 waypoint19)
	(visible waypoint19 waypoint28)
	(visible waypoint28 waypoint19)
	(visible waypoint19 waypoint30)
	(visible waypoint30 waypoint19)
	(visible waypoint19 waypoint33)
	(visible waypoint33 waypoint19)
	(visible waypoint20 waypoint19)
	(visible waypoint19 waypoint20)
	(visible waypoint20 waypoint30)
	(visible waypoint30 waypoint20)
	(visible waypoint20 waypoint31)
	(visible waypoint31 waypoint20)
	(visible waypoint22 waypoint3)
	(visible waypoint3 waypoint22)
	(visible waypoint22 waypoint13)
	(visible waypoint13 waypoint22)
	(visible waypoint22 waypoint19)
	(visible waypoint19 waypoint22)
	(visible waypoint22 waypoint27)
	(visible waypoint27 waypoint22)
	(visible waypoint22 waypoint33)
	(visible waypoint33 waypoint22)
	(visible waypoint22 waypoint38)
	(visible waypoint38 waypoint22)
	(visible waypoint22 waypoint39)
	(visible waypoint39 waypoint22)
	(visible waypoint22 waypoint48)
	(visible waypoint48 waypoint22)
	(visible waypoint23 waypoint4)
	(visible waypoint4 waypoint23)
	(visible waypoint23 waypoint7)
	(visible waypoint7 waypoint23)
	(visible waypoint23 waypoint9)
	(visible waypoint9 waypoint23)
	(visible waypoint23 waypoint10)
	(visible waypoint10 waypoint23)
	(visible waypoint23 waypoint13)
	(visible waypoint13 waypoint23)
	(visible waypoint23 waypoint16)
	(visible waypoint16 waypoint23)
	(visible waypoint23 waypoint34)
	(visible waypoint34 waypoint23)
	(visible waypoint23 waypoint44)
	(visible waypoint44 waypoint23)
	(visible waypoint23 waypoint45)
	(visible waypoint45 waypoint23)
	(visible waypoint24 waypoint3)
	(visible waypoint3 waypoint24)
	(visible waypoint24 waypoint9)
	(visible waypoint9 waypoint24)
	(visible waypoint24 waypoint38)
	(visible waypoint38 waypoint24)
	(visible waypoint24 waypoint43)
	(visible waypoint43 waypoint24)
	(visible waypoint25 waypoint12)
	(visible waypoint12 waypoint25)
	(visible waypoint25 waypoint19)
	(visible waypoint19 waypoint25)
	(visible waypoint25 waypoint36)
	(visible waypoint36 waypoint25)
	(visible waypoint25 waypoint42)
	(visible waypoint42 waypoint25)
	(visible waypoint25 waypoint48)
	(visible waypoint48 waypoint25)
	(visible waypoint26 waypoint19)
	(visible waypoint19 waypoint26)
	(visible waypoint26 waypoint22)
	(visible waypoint22 waypoint26)
	(visible waypoint27 waypoint4)
	(visible waypoint4 waypoint27)
	(visible waypoint27 waypoint14)
	(visible waypoint14 waypoint27)
	(visible waypoint27 waypoint15)
	(visible waypoint15 waypoint27)
	(visible waypoint27 waypoint49)
	(visible waypoint49 waypoint27)
	(visible waypoint28 waypoint8)
	(visible waypoint8 waypoint28)
	(visible waypoint28 waypoint11)
	(visible waypoint11 waypoint28)
	(visible waypoint28 waypoint12)
	(visible waypoint12 waypoint28)
	(visible waypoint28 waypoint13)
	(visible waypoint13 waypoint28)
	(visible waypoint28 waypoint18)
	(visible waypoint18 waypoint28)
	(visible waypoint28 waypoint30)
	(visible waypoint30 waypoint28)
	(visible waypoint28 waypoint32)
	(visible waypoint32 waypoint28)
	(visible waypoint29 waypoint3)
	(visible waypoint3 waypoint29)
	(visible waypoint29 waypoint11)
	(visible waypoint11 waypoint29)
	(visible waypoint29 waypoint30)
	(visible waypoint30 waypoint29)
	(visible waypoint29 waypoint39)
	(visible waypoint39 waypoint29)
	(visible waypoint30 waypoint26)
	(visible waypoint26 waypoint30)
	(visible waypoint31 waypoint46)
	(visible waypoint46 waypoint31)
	(visible waypoint32 waypoint15)
	(visible waypoint15 waypoint32)
	(visible waypoint32 waypoint20)
	(visible waypoint20 waypoint32)
	(visible waypoint32 waypoint25)
	(visible waypoint25 waypoint32)
	(visible waypoint32 waypoint27)
	(visible waypoint27 waypoint32)
	(visible waypoint33 waypoint17)
	(visible waypoint17 waypoint33)
	(visible waypoint33 waypoint35)
	(visible waypoint35 waypoint33)
	(visible waypoint34 waypoint33)
	(visible waypoint33 waypoint34)
	(visible waypoint34 waypoint36)
	(visible waypoint36 waypoint34)
	(visible waypoint35 waypoint1)
	(visible waypoint1 waypoint35)
	(visible waypoint35 waypoint6)
	(visible waypoint6 waypoint35)
	(visible waypoint35 waypoint7)
	(visible waypoint7 waypoint35)
	(visible waypoint35 waypoint32)
	(visible waypoint32 waypoint35)
	(visible waypoint35 waypoint42)
	(visible waypoint42 waypoint35)
	(visible waypoint35 waypoint43)
	(visible waypoint43 waypoint35)
	(visible waypoint36 waypoint17)
	(visible waypoint17 waypoint36)
	(visible waypoint36 waypoint41)
	(visible waypoint41 waypoint36)
	(visible waypoint37 waypoint21)
	(visible waypoint21 waypoint37)
	(visible waypoint37 waypoint28)
	(visible waypoint28 waypoint37)
	(visible waypoint37 waypoint30)
	(visible waypoint30 waypoint37)
	(visible waypoint37 waypoint35)
	(visible waypoint35 waypoint37)
	(visible waypoint37 waypoint45)
	(visible waypoint45 waypoint37)
	(visible waypoint38 waypoint5)
	(visible waypoint5 waypoint38)
	(visible waypoint38 waypoint25)
	(visible waypoint25 waypoint38)
	(visible waypoint38 waypoint35)
	(visible waypoint35 waypoint38)
	(visible waypoint38 waypoint36)
	(visible waypoint36 waypoint38)
	(visible waypoint39 waypoint7)
	(visible waypoint7 waypoint39)
	(visible waypoint39 waypoint18)
	(visible waypoint18 waypoint39)
	(visible waypoint39 waypoint21)
	(visible waypoint21 waypoint39)
	(visible waypoint40 waypoint3)
	(visible waypoint3 waypoint40)
	(visible waypoint40 waypoint24)
	(visible waypoint24 waypoint40)
	(visible waypoint40 waypoint43)
	(visible waypoint43 waypoint40)
	(visible waypoint40 waypoint45)
	(visible waypoint45 waypoint40)
	(visible waypoint40 waypoint46)
	(visible waypoint46 waypoint40)
	(visible waypoint41 waypoint1)
	(visible waypoint1 waypoint41)
	(visible waypoint41 waypoint28)
	(visible waypoint28 waypoint41)
	(visible waypoint41 waypoint40)
	(visible waypoint40 waypoint41)
	(visible waypoint42 waypoint4)
	(visible waypoint4 waypoint42)
	(visible waypoint42 waypoint15)
	(visible waypoint15 waypoint42)
	(visible waypoint42 waypoint18)
	(visible waypoint18 waypoint42)
	(visible waypoint42 waypoint43)
	(visible waypoint43 waypoint42)
	(visible waypoint43 waypoint0)
	(visible waypoint0 waypoint43)
	(visible waypoint43 waypoint16)
	(visible waypoint16 waypoint43)
	(visible waypoint43 waypoint22)
	(visible waypoint22 waypoint43)
	(visible waypoint43 waypoint27)
	(visible waypoint27 waypoint43)
	(visible waypoint43 waypoint31)
	(visible waypoint31 waypoint43)
	(visible waypoint43 waypoint37)
	(visible waypoint37 waypoint43)
	(visible waypoint43 waypoint46)
	(visible waypoint46 waypoint43)
	(visible waypoint44 waypoint14)
	(visible waypoint14 waypoint44)
	(visible waypoint44 waypoint19)
	(visible waypoint19 waypoint44)
	(visible waypoint45 waypoint1)
	(visible waypoint1 waypoint45)
	(visible waypoint45 waypoint8)
	(visible waypoint8 waypoint45)
	(visible waypoint45 waypoint12)
	(visible waypoint12 waypoint45)
	(visible waypoint45 waypoint13)
	(visible waypoint13 waypoint45)
	(visible waypoint45 waypoint26)
	(visible waypoint26 waypoint45)
	(visible waypoint45 waypoint29)
	(visible waypoint29 waypoint45)
	(visible waypoint45 waypoint30)
	(visible waypoint30 waypoint45)
	(visible waypoint45 waypoint31)
	(visible waypoint31 waypoint45)
	(visible waypoint45 waypoint32)
	(visible waypoint32 waypoint45)
	(visible waypoint46 waypoint16)
	(visible waypoint16 waypoint46)
	(visible waypoint46 waypoint19)
	(visible waypoint19 waypoint46)
	(visible waypoint46 waypoint33)
	(visible waypoint33 waypoint46)
	(visible waypoint46 waypoint39)
	(visible waypoint39 waypoint46)
	(visible waypoint46 waypoint44)
	(visible waypoint44 waypoint46)
	(visible waypoint46 waypoint49)
	(visible waypoint49 waypoint46)
	(visible waypoint47 waypoint12)
	(visible waypoint12 waypoint47)
	(visible waypoint47 waypoint15)
	(visible waypoint15 waypoint47)
	(visible waypoint47 waypoint22)
	(visible waypoint22 waypoint47)
	(visible waypoint47 waypoint23)
	(visible waypoint23 waypoint47)
	(visible waypoint47 waypoint31)
	(visible waypoint31 waypoint47)
	(visible waypoint47 waypoint39)
	(visible waypoint39 waypoint47)
	(visible waypoint47 waypoint41)
	(visible waypoint41 waypoint47)
	(visible waypoint48 waypoint2)
	(visible waypoint2 waypoint48)
	(visible waypoint48 waypoint32)
	(visible waypoint32 waypoint48)
	(visible waypoint48 waypoint42)
	(visible waypoint42 waypoint48)
	(visible waypoint49 waypoint12)
	(visible waypoint12 waypoint49)
	(visible waypoint49 waypoint30)
	(visible waypoint30 waypoint49)
	(visible waypoint49 waypoint33)
	(visible waypoint33 waypoint49)
	(at_soil_sample waypoint0)
	(at_rock_sample waypoint0)
	(at_soil_sample waypoint2)
	(at_rock_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint3)
	(at_soil_sample waypoint4)
	(at_rock_sample waypoint5)
	(at_rock_sample waypoint6)
	(at_soil_sample waypoint8)
	(at_rock_sample waypoint8)
	(at_soil_sample waypoint9)
	(at_rock_sample waypoint9)
	(at_rock_sample waypoint10)
	(at_soil_sample waypoint11)
	(at_rock_sample waypoint11)
	(at_rock_sample waypoint12)
	(at_soil_sample waypoint13)
	(at_rock_sample waypoint15)
	(at_soil_sample waypoint16)
	(at_rock_sample waypoint16)
	(at_soil_sample waypoint17)
	(at_soil_sample waypoint18)
	(at_rock_sample waypoint18)
	(at_soil_sample waypoint19)
	(at_soil_sample waypoint20)
	(at_rock_sample waypoint20)
	(at_rock_sample waypoint22)
	(at_soil_sample waypoint23)
	(at_rock_sample waypoint23)
	(at_rock_sample waypoint24)
	(at_soil_sample waypoint25)
	(at_rock_sample waypoint27)
	(at_rock_sample waypoint28)
	(at_rock_sample waypoint29)
	(at_soil_sample waypoint30)
	(at_soil_sample waypoint31)
	(at_soil_sample waypoint32)
	(at_rock_sample waypoint32)
	(at_rock_sample waypoint33)
	(at_rock_sample waypoint34)
	(at_soil_sample waypoint35)
	(at_rock_sample waypoint35)
	(at_soil_sample waypoint36)
	(at_rock_sample waypoint36)
	(at_rock_sample waypoint37)
	(at_soil_sample waypoint39)
	(at_rock_sample waypoint39)
	(at_soil_sample waypoint40)
	(at_rock_sample waypoint40)
	(at_soil_sample waypoint43)
	(at_rock_sample waypoint43)
	(at_rock_sample waypoint44)
	(at_soil_sample waypoint45)
	(at_rock_sample waypoint45)
	(at_soil_sample waypoint47)
	(at_rock_sample waypoint48)
	(at_soil_sample waypoint49)
	(at_lander general waypoint46)
	(channel_free general)
	(at rover0 waypoint40)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint40 waypoint3)
	(can_traverse rover0 waypoint3 waypoint40)
	(can_traverse rover0 waypoint40 waypoint11)
	(can_traverse rover0 waypoint11 waypoint40)
	(can_traverse rover0 waypoint40 waypoint12)
	(can_traverse rover0 waypoint12 waypoint40)
	(can_traverse rover0 waypoint40 waypoint24)
	(can_traverse rover0 waypoint24 waypoint40)
	(can_traverse rover0 waypoint40 waypoint43)
	(can_traverse rover0 waypoint43 waypoint40)
	(can_traverse rover0 waypoint40 waypoint45)
	(can_traverse rover0 waypoint45 waypoint40)
	(can_traverse rover0 waypoint3 waypoint8)
	(can_traverse rover0 waypoint8 waypoint3)
	(can_traverse rover0 waypoint3 waypoint22)
	(can_traverse rover0 waypoint22 waypoint3)
	(can_traverse rover0 waypoint3 waypoint28)
	(can_traverse rover0 waypoint28 waypoint3)
	(can_traverse rover0 waypoint3 waypoint29)
	(can_traverse rover0 waypoint29 waypoint3)
	(can_traverse rover0 waypoint3 waypoint31)
	(can_traverse rover0 waypoint31 waypoint3)
	(can_traverse rover0 waypoint3 waypoint36)
	(can_traverse rover0 waypoint36 waypoint3)
	(can_traverse rover0 waypoint11 waypoint0)
	(can_traverse rover0 waypoint0 waypoint11)
	(can_traverse rover0 waypoint11 waypoint14)
	(can_traverse rover0 waypoint14 waypoint11)
	(can_traverse rover0 waypoint11 waypoint15)
	(can_traverse rover0 waypoint15 waypoint11)
	(can_traverse rover0 waypoint11 waypoint19)
	(can_traverse rover0 waypoint19 waypoint11)
	(can_traverse rover0 waypoint12 waypoint9)
	(can_traverse rover0 waypoint9 waypoint12)
	(can_traverse rover0 waypoint12 waypoint13)
	(can_traverse rover0 waypoint13 waypoint12)
	(can_traverse rover0 waypoint12 waypoint25)
	(can_traverse rover0 waypoint25 waypoint12)
	(can_traverse rover0 waypoint12 waypoint49)
	(can_traverse rover0 waypoint49 waypoint12)
	(can_traverse rover0 waypoint24 waypoint16)
	(can_traverse rover0 waypoint16 waypoint24)
	(can_traverse rover0 waypoint24 waypoint38)
	(can_traverse rover0 waypoint38 waypoint24)
	(can_traverse rover0 waypoint43 waypoint35)
	(can_traverse rover0 waypoint35 waypoint43)
	(can_traverse rover0 waypoint43 waypoint37)
	(can_traverse rover0 waypoint37 waypoint43)
	(can_traverse rover0 waypoint43 waypoint46)
	(can_traverse rover0 waypoint46 waypoint43)
	(can_traverse rover0 waypoint45 waypoint1)
	(can_traverse rover0 waypoint1 waypoint45)
	(can_traverse rover0 waypoint45 waypoint6)
	(can_traverse rover0 waypoint6 waypoint45)
	(can_traverse rover0 waypoint45 waypoint23)
	(can_traverse rover0 waypoint23 waypoint45)
	(can_traverse rover0 waypoint45 waypoint32)
	(can_traverse rover0 waypoint32 waypoint45)
	(can_traverse rover0 waypoint8 waypoint5)
	(can_traverse rover0 waypoint5 waypoint8)
	(can_traverse rover0 waypoint8 waypoint10)
	(can_traverse rover0 waypoint10 waypoint8)
	(can_traverse rover0 waypoint8 waypoint21)
	(can_traverse rover0 waypoint21 waypoint8)
	(can_traverse rover0 waypoint8 waypoint47)
	(can_traverse rover0 waypoint47 waypoint8)
	(can_traverse rover0 waypoint22 waypoint4)
	(can_traverse rover0 waypoint4 waypoint22)
	(can_traverse rover0 waypoint22 waypoint17)
	(can_traverse rover0 waypoint17 waypoint22)
	(can_traverse rover0 waypoint22 waypoint26)
	(can_traverse rover0 waypoint26 waypoint22)
	(can_traverse rover0 waypoint22 waypoint27)
	(can_traverse rover0 waypoint27 waypoint22)
	(can_traverse rover0 waypoint22 waypoint33)
	(can_traverse rover0 waypoint33 waypoint22)
	(can_traverse rover0 waypoint22 waypoint48)
	(can_traverse rover0 waypoint48 waypoint22)
	(can_traverse rover0 waypoint28 waypoint18)
	(can_traverse rover0 waypoint18 waypoint28)
	(can_traverse rover0 waypoint28 waypoint30)
	(can_traverse rover0 waypoint30 waypoint28)
	(can_traverse rover0 waypoint28 waypoint41)
	(can_traverse rover0 waypoint41 waypoint28)
	(can_traverse rover0 waypoint29 waypoint39)
	(can_traverse rover0 waypoint39 waypoint29)
	(can_traverse rover0 waypoint36 waypoint34)
	(can_traverse rover0 waypoint34 waypoint36)
	(can_traverse rover0 waypoint14 waypoint44)
	(can_traverse rover0 waypoint44 waypoint14)
	(can_traverse rover0 waypoint15 waypoint42)
	(can_traverse rover0 waypoint42 waypoint15)
	(can_traverse rover0 waypoint19 waypoint20)
	(can_traverse rover0 waypoint20 waypoint19)
	(can_traverse rover0 waypoint13 waypoint7)
	(can_traverse rover0 waypoint7 waypoint13)
	(can_traverse rover0 waypoint48 waypoint2)
	(can_traverse rover0 waypoint2 waypoint48)
	(at rover1 waypoint19)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_rock_analysis rover1)
	(equipped_for_imaging rover1)
	(can_traverse rover1 waypoint19 waypoint5)
	(can_traverse rover1 waypoint5 waypoint19)
	(can_traverse rover1 waypoint19 waypoint11)
	(can_traverse rover1 waypoint11 waypoint19)
	(can_traverse rover1 waypoint19 waypoint17)
	(can_traverse rover1 waypoint17 waypoint19)
	(can_traverse rover1 waypoint19 waypoint20)
	(can_traverse rover1 waypoint20 waypoint19)
	(can_traverse rover1 waypoint19 waypoint22)
	(can_traverse rover1 waypoint22 waypoint19)
	(can_traverse rover1 waypoint19 waypoint30)
	(can_traverse rover1 waypoint30 waypoint19)
	(can_traverse rover1 waypoint19 waypoint44)
	(can_traverse rover1 waypoint44 waypoint19)
	(can_traverse rover1 waypoint5 waypoint4)
	(can_traverse rover1 waypoint4 waypoint5)
	(can_traverse rover1 waypoint5 waypoint8)
	(can_traverse rover1 waypoint8 waypoint5)
	(can_traverse rover1 waypoint5 waypoint10)
	(can_traverse rover1 waypoint10 waypoint5)
	(can_traverse rover1 waypoint5 waypoint38)
	(can_traverse rover1 waypoint38 waypoint5)
	(can_traverse rover1 waypoint5 waypoint39)
	(can_traverse rover1 waypoint39 waypoint5)
	(can_traverse rover1 waypoint5 waypoint46)
	(can_traverse rover1 waypoint46 waypoint5)
	(can_traverse rover1 waypoint5 waypoint49)
	(can_traverse rover1 waypoint49 waypoint5)
	(can_traverse rover1 waypoint11 waypoint0)
	(can_traverse rover1 waypoint0 waypoint11)
	(can_traverse rover1 waypoint11 waypoint3)
	(can_traverse rover1 waypoint3 waypoint11)
	(can_traverse rover1 waypoint11 waypoint14)
	(can_traverse rover1 waypoint14 waypoint11)
	(can_traverse rover1 waypoint11 waypoint15)
	(can_traverse rover1 waypoint15 waypoint11)
	(can_traverse rover1 waypoint11 waypoint28)
	(can_traverse rover1 waypoint28 waypoint11)
	(can_traverse rover1 waypoint11 waypoint40)
	(can_traverse rover1 waypoint40 waypoint11)
	(can_traverse rover1 waypoint17 waypoint33)
	(can_traverse rover1 waypoint33 waypoint17)
	(can_traverse rover1 waypoint20 waypoint31)
	(can_traverse rover1 waypoint31 waypoint20)
	(can_traverse rover1 waypoint22 waypoint6)
	(can_traverse rover1 waypoint6 waypoint22)
	(can_traverse rover1 waypoint22 waypoint26)
	(can_traverse rover1 waypoint26 waypoint22)
	(can_traverse rover1 waypoint22 waypoint27)
	(can_traverse rover1 waypoint27 waypoint22)
	(can_traverse rover1 waypoint30 waypoint9)
	(can_traverse rover1 waypoint9 waypoint30)
	(can_traverse rover1 waypoint30 waypoint29)
	(can_traverse rover1 waypoint29 waypoint30)
	(can_traverse rover1 waypoint30 waypoint37)
	(can_traverse rover1 waypoint37 waypoint30)
	(can_traverse rover1 waypoint44 waypoint2)
	(can_traverse rover1 waypoint2 waypoint44)
	(can_traverse rover1 waypoint44 waypoint7)
	(can_traverse rover1 waypoint7 waypoint44)
	(can_traverse rover1 waypoint44 waypoint12)
	(can_traverse rover1 waypoint12 waypoint44)
	(can_traverse rover1 waypoint4 waypoint23)
	(can_traverse rover1 waypoint23 waypoint4)
	(can_traverse rover1 waypoint4 waypoint42)
	(can_traverse rover1 waypoint42 waypoint4)
	(can_traverse rover1 waypoint8 waypoint13)
	(can_traverse rover1 waypoint13 waypoint8)
	(can_traverse rover1 waypoint38 waypoint1)
	(can_traverse rover1 waypoint1 waypoint38)
	(can_traverse rover1 waypoint38 waypoint25)
	(can_traverse rover1 waypoint25 waypoint38)
	(can_traverse rover1 waypoint38 waypoint35)
	(can_traverse rover1 waypoint35 waypoint38)
	(can_traverse rover1 waypoint38 waypoint36)
	(can_traverse rover1 waypoint36 waypoint38)
	(can_traverse rover1 waypoint39 waypoint18)
	(can_traverse rover1 waypoint18 waypoint39)
	(can_traverse rover1 waypoint46 waypoint16)
	(can_traverse rover1 waypoint16 waypoint46)
	(can_traverse rover1 waypoint0 waypoint43)
	(can_traverse rover1 waypoint43 waypoint0)
	(can_traverse rover1 waypoint3 waypoint24)
	(can_traverse rover1 waypoint24 waypoint3)
	(can_traverse rover1 waypoint15 waypoint41)
	(can_traverse rover1 waypoint41 waypoint15)
	(can_traverse rover1 waypoint15 waypoint47)
	(can_traverse rover1 waypoint47 waypoint15)
	(can_traverse rover1 waypoint28 waypoint32)
	(can_traverse rover1 waypoint32 waypoint28)
	(can_traverse rover1 waypoint33 waypoint34)
	(can_traverse rover1 waypoint34 waypoint33)
	(can_traverse rover1 waypoint6 waypoint45)
	(can_traverse rover1 waypoint45 waypoint6)
	(can_traverse rover1 waypoint25 waypoint48)
	(can_traverse rover1 waypoint48 waypoint25)
	(can_traverse rover1 waypoint16 waypoint21)
	(can_traverse rover1 waypoint21 waypoint16)
	(at rover2 waypoint37)
	(available rover2)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_rock_analysis rover2)
	(equipped_for_imaging rover2)
	(can_traverse rover2 waypoint37 waypoint1)
	(can_traverse rover2 waypoint1 waypoint37)
	(can_traverse rover2 waypoint37 waypoint10)
	(can_traverse rover2 waypoint10 waypoint37)
	(can_traverse rover2 waypoint37 waypoint21)
	(can_traverse rover2 waypoint21 waypoint37)
	(can_traverse rover2 waypoint37 waypoint28)
	(can_traverse rover2 waypoint28 waypoint37)
	(can_traverse rover2 waypoint37 waypoint35)
	(can_traverse rover2 waypoint35 waypoint37)
	(can_traverse rover2 waypoint37 waypoint43)
	(can_traverse rover2 waypoint43 waypoint37)
	(can_traverse rover2 waypoint37 waypoint45)
	(can_traverse rover2 waypoint45 waypoint37)
	(can_traverse rover2 waypoint1 waypoint0)
	(can_traverse rover2 waypoint0 waypoint1)
	(can_traverse rover2 waypoint1 waypoint13)
	(can_traverse rover2 waypoint13 waypoint1)
	(can_traverse rover2 waypoint1 waypoint14)
	(can_traverse rover2 waypoint14 waypoint1)
	(can_traverse rover2 waypoint10 waypoint6)
	(can_traverse rover2 waypoint6 waypoint10)
	(can_traverse rover2 waypoint10 waypoint8)
	(can_traverse rover2 waypoint8 waypoint10)
	(can_traverse rover2 waypoint10 waypoint27)
	(can_traverse rover2 waypoint27 waypoint10)
	(can_traverse rover2 waypoint21 waypoint4)
	(can_traverse rover2 waypoint4 waypoint21)
	(can_traverse rover2 waypoint21 waypoint16)
	(can_traverse rover2 waypoint16 waypoint21)
	(can_traverse rover2 waypoint21 waypoint39)
	(can_traverse rover2 waypoint39 waypoint21)
	(can_traverse rover2 waypoint28 waypoint2)
	(can_traverse rover2 waypoint2 waypoint28)
	(can_traverse rover2 waypoint28 waypoint3)
	(can_traverse rover2 waypoint3 waypoint28)
	(can_traverse rover2 waypoint28 waypoint11)
	(can_traverse rover2 waypoint11 waypoint28)
	(can_traverse rover2 waypoint28 waypoint12)
	(can_traverse rover2 waypoint12 waypoint28)
	(can_traverse rover2 waypoint28 waypoint18)
	(can_traverse rover2 waypoint18 waypoint28)
	(can_traverse rover2 waypoint28 waypoint19)
	(can_traverse rover2 waypoint19 waypoint28)
	(can_traverse rover2 waypoint28 waypoint30)
	(can_traverse rover2 waypoint30 waypoint28)
	(can_traverse rover2 waypoint28 waypoint32)
	(can_traverse rover2 waypoint32 waypoint28)
	(can_traverse rover2 waypoint28 waypoint41)
	(can_traverse rover2 waypoint41 waypoint28)
	(can_traverse rover2 waypoint35 waypoint7)
	(can_traverse rover2 waypoint7 waypoint35)
	(can_traverse rover2 waypoint35 waypoint9)
	(can_traverse rover2 waypoint9 waypoint35)
	(can_traverse rover2 waypoint35 waypoint33)
	(can_traverse rover2 waypoint33 waypoint35)
	(can_traverse rover2 waypoint35 waypoint38)
	(can_traverse rover2 waypoint38 waypoint35)
	(can_traverse rover2 waypoint35 waypoint42)
	(can_traverse rover2 waypoint42 waypoint35)
	(can_traverse rover2 waypoint43 waypoint22)
	(can_traverse rover2 waypoint22 waypoint43)
	(can_traverse rover2 waypoint43 waypoint24)
	(can_traverse rover2 waypoint24 waypoint43)
	(can_traverse rover2 waypoint43 waypoint31)
	(can_traverse rover2 waypoint31 waypoint43)
	(can_traverse rover2 waypoint45 waypoint23)
	(can_traverse rover2 waypoint23 waypoint45)
	(can_traverse rover2 waypoint45 waypoint29)
	(can_traverse rover2 waypoint29 waypoint45)
	(can_traverse rover2 waypoint0 waypoint20)
	(can_traverse rover2 waypoint20 waypoint0)
	(can_traverse rover2 waypoint14 waypoint49)
	(can_traverse rover2 waypoint49 waypoint14)
	(can_traverse rover2 waypoint6 waypoint25)
	(can_traverse rover2 waypoint25 waypoint6)
	(can_traverse rover2 waypoint8 waypoint5)
	(can_traverse rover2 waypoint5 waypoint8)
	(can_traverse rover2 waypoint27 waypoint15)
	(can_traverse rover2 waypoint15 waypoint27)
	(can_traverse rover2 waypoint4 waypoint26)
	(can_traverse rover2 waypoint26 waypoint4)
	(can_traverse rover2 waypoint16 waypoint46)
	(can_traverse rover2 waypoint46 waypoint16)
	(can_traverse rover2 waypoint39 waypoint17)
	(can_traverse rover2 waypoint17 waypoint39)
	(can_traverse rover2 waypoint39 waypoint47)
	(can_traverse rover2 waypoint47 waypoint39)
	(can_traverse rover2 waypoint2 waypoint44)
	(can_traverse rover2 waypoint44 waypoint2)
	(can_traverse rover2 waypoint2 waypoint48)
	(can_traverse rover2 waypoint48 waypoint2)
	(can_traverse rover2 waypoint3 waypoint36)
	(can_traverse rover2 waypoint36 waypoint3)
	(can_traverse rover2 waypoint3 waypoint40)
	(can_traverse rover2 waypoint40 waypoint3)
	(can_traverse rover2 waypoint33 waypoint34)
	(can_traverse rover2 waypoint34 waypoint33)
	(at rover3 waypoint48)
	(available rover3)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_rock_analysis rover3)
	(equipped_for_imaging rover3)
	(can_traverse rover3 waypoint48 waypoint2)
	(can_traverse rover3 waypoint2 waypoint48)
	(can_traverse rover3 waypoint48 waypoint22)
	(can_traverse rover3 waypoint22 waypoint48)
	(can_traverse rover3 waypoint48 waypoint25)
	(can_traverse rover3 waypoint25 waypoint48)
	(can_traverse rover3 waypoint48 waypoint32)
	(can_traverse rover3 waypoint32 waypoint48)
	(can_traverse rover3 waypoint48 waypoint42)
	(can_traverse rover3 waypoint42 waypoint48)
	(can_traverse rover3 waypoint2 waypoint15)
	(can_traverse rover3 waypoint15 waypoint2)
	(can_traverse rover3 waypoint2 waypoint28)
	(can_traverse rover3 waypoint28 waypoint2)
	(can_traverse rover3 waypoint2 waypoint44)
	(can_traverse rover3 waypoint44 waypoint2)
	(can_traverse rover3 waypoint22 waypoint4)
	(can_traverse rover3 waypoint4 waypoint22)
	(can_traverse rover3 waypoint22 waypoint13)
	(can_traverse rover3 waypoint13 waypoint22)
	(can_traverse rover3 waypoint22 waypoint17)
	(can_traverse rover3 waypoint17 waypoint22)
	(can_traverse rover3 waypoint22 waypoint19)
	(can_traverse rover3 waypoint19 waypoint22)
	(can_traverse rover3 waypoint22 waypoint26)
	(can_traverse rover3 waypoint26 waypoint22)
	(can_traverse rover3 waypoint22 waypoint38)
	(can_traverse rover3 waypoint38 waypoint22)
	(can_traverse rover3 waypoint22 waypoint39)
	(can_traverse rover3 waypoint39 waypoint22)
	(can_traverse rover3 waypoint22 waypoint43)
	(can_traverse rover3 waypoint43 waypoint22)
	(can_traverse rover3 waypoint22 waypoint47)
	(can_traverse rover3 waypoint47 waypoint22)
	(can_traverse rover3 waypoint25 waypoint6)
	(can_traverse rover3 waypoint6 waypoint25)
	(can_traverse rover3 waypoint25 waypoint12)
	(can_traverse rover3 waypoint12 waypoint25)
	(can_traverse rover3 waypoint25 waypoint36)
	(can_traverse rover3 waypoint36 waypoint25)
	(can_traverse rover3 waypoint32 waypoint27)
	(can_traverse rover3 waypoint27 waypoint32)
	(can_traverse rover3 waypoint32 waypoint35)
	(can_traverse rover3 waypoint35 waypoint32)
	(can_traverse rover3 waypoint42 waypoint18)
	(can_traverse rover3 waypoint18 waypoint42)
	(can_traverse rover3 waypoint15 waypoint11)
	(can_traverse rover3 waypoint11 waypoint15)
	(can_traverse rover3 waypoint15 waypoint16)
	(can_traverse rover3 waypoint16 waypoint15)
	(can_traverse rover3 waypoint28 waypoint0)
	(can_traverse rover3 waypoint0 waypoint28)
	(can_traverse rover3 waypoint28 waypoint3)
	(can_traverse rover3 waypoint3 waypoint28)
	(can_traverse rover3 waypoint28 waypoint8)
	(can_traverse rover3 waypoint8 waypoint28)
	(can_traverse rover3 waypoint28 waypoint10)
	(can_traverse rover3 waypoint10 waypoint28)
	(can_traverse rover3 waypoint28 waypoint30)
	(can_traverse rover3 waypoint30 waypoint28)
	(can_traverse rover3 waypoint28 waypoint41)
	(can_traverse rover3 waypoint41 waypoint28)
	(can_traverse rover3 waypoint44 waypoint14)
	(can_traverse rover3 waypoint14 waypoint44)
	(can_traverse rover3 waypoint44 waypoint46)
	(can_traverse rover3 waypoint46 waypoint44)
	(can_traverse rover3 waypoint4 waypoint5)
	(can_traverse rover3 waypoint5 waypoint4)
	(can_traverse rover3 waypoint4 waypoint7)
	(can_traverse rover3 waypoint7 waypoint4)
	(can_traverse rover3 waypoint4 waypoint21)
	(can_traverse rover3 waypoint21 waypoint4)
	(can_traverse rover3 waypoint4 waypoint23)
	(can_traverse rover3 waypoint23 waypoint4)
	(can_traverse rover3 waypoint17 waypoint33)
	(can_traverse rover3 waypoint33 waypoint17)
	(can_traverse rover3 waypoint19 waypoint20)
	(can_traverse rover3 waypoint20 waypoint19)
	(can_traverse rover3 waypoint26 waypoint45)
	(can_traverse rover3 waypoint45 waypoint26)
	(can_traverse rover3 waypoint38 waypoint24)
	(can_traverse rover3 waypoint24 waypoint38)
	(can_traverse rover3 waypoint39 waypoint29)
	(can_traverse rover3 waypoint29 waypoint39)
	(can_traverse rover3 waypoint43 waypoint31)
	(can_traverse rover3 waypoint31 waypoint43)
	(can_traverse rover3 waypoint12 waypoint40)
	(can_traverse rover3 waypoint40 waypoint12)
	(can_traverse rover3 waypoint36 waypoint34)
	(can_traverse rover3 waypoint34 waypoint36)
	(can_traverse rover3 waypoint27 waypoint49)
	(can_traverse rover3 waypoint49 waypoint27)
	(can_traverse rover3 waypoint35 waypoint1)
	(can_traverse rover3 waypoint1 waypoint35)
	(can_traverse rover3 waypoint35 waypoint9)
	(can_traverse rover3 waypoint9 waypoint35)
	(can_traverse rover3 waypoint35 waypoint37)
	(can_traverse rover3 waypoint37 waypoint35)
	(at rover4 waypoint38)
	(available rover4)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_imaging rover4)
	(can_traverse rover4 waypoint38 waypoint1)
	(can_traverse rover4 waypoint1 waypoint38)
	(can_traverse rover4 waypoint38 waypoint5)
	(can_traverse rover4 waypoint5 waypoint38)
	(can_traverse rover4 waypoint38 waypoint22)
	(can_traverse rover4 waypoint22 waypoint38)
	(can_traverse rover4 waypoint38 waypoint24)
	(can_traverse rover4 waypoint24 waypoint38)
	(can_traverse rover4 waypoint38 waypoint35)
	(can_traverse rover4 waypoint35 waypoint38)
	(can_traverse rover4 waypoint38 waypoint36)
	(can_traverse rover4 waypoint36 waypoint38)
	(can_traverse rover4 waypoint1 waypoint13)
	(can_traverse rover4 waypoint13 waypoint1)
	(can_traverse rover4 waypoint1 waypoint14)
	(can_traverse rover4 waypoint14 waypoint1)
	(can_traverse rover4 waypoint1 waypoint16)
	(can_traverse rover4 waypoint16 waypoint1)
	(can_traverse rover4 waypoint1 waypoint37)
	(can_traverse rover4 waypoint37 waypoint1)
	(can_traverse rover4 waypoint1 waypoint41)
	(can_traverse rover4 waypoint41 waypoint1)
	(can_traverse rover4 waypoint1 waypoint45)
	(can_traverse rover4 waypoint45 waypoint1)
	(can_traverse rover4 waypoint5 waypoint4)
	(can_traverse rover4 waypoint4 waypoint5)
	(can_traverse rover4 waypoint5 waypoint10)
	(can_traverse rover4 waypoint10 waypoint5)
	(can_traverse rover4 waypoint5 waypoint19)
	(can_traverse rover4 waypoint19 waypoint5)
	(can_traverse rover4 waypoint5 waypoint39)
	(can_traverse rover4 waypoint39 waypoint5)
	(can_traverse rover4 waypoint5 waypoint46)
	(can_traverse rover4 waypoint46 waypoint5)
	(can_traverse rover4 waypoint22 waypoint6)
	(can_traverse rover4 waypoint6 waypoint22)
	(can_traverse rover4 waypoint22 waypoint17)
	(can_traverse rover4 waypoint17 waypoint22)
	(can_traverse rover4 waypoint22 waypoint26)
	(can_traverse rover4 waypoint26 waypoint22)
	(can_traverse rover4 waypoint22 waypoint27)
	(can_traverse rover4 waypoint27 waypoint22)
	(can_traverse rover4 waypoint22 waypoint43)
	(can_traverse rover4 waypoint43 waypoint22)
	(can_traverse rover4 waypoint22 waypoint47)
	(can_traverse rover4 waypoint47 waypoint22)
	(can_traverse rover4 waypoint22 waypoint48)
	(can_traverse rover4 waypoint48 waypoint22)
	(can_traverse rover4 waypoint24 waypoint9)
	(can_traverse rover4 waypoint9 waypoint24)
	(can_traverse rover4 waypoint24 waypoint15)
	(can_traverse rover4 waypoint15 waypoint24)
	(can_traverse rover4 waypoint24 waypoint40)
	(can_traverse rover4 waypoint40 waypoint24)
	(can_traverse rover4 waypoint35 waypoint7)
	(can_traverse rover4 waypoint7 waypoint35)
	(can_traverse rover4 waypoint35 waypoint18)
	(can_traverse rover4 waypoint18 waypoint35)
	(can_traverse rover4 waypoint35 waypoint32)
	(can_traverse rover4 waypoint32 waypoint35)
	(can_traverse rover4 waypoint35 waypoint33)
	(can_traverse rover4 waypoint33 waypoint35)
	(can_traverse rover4 waypoint35 waypoint42)
	(can_traverse rover4 waypoint42 waypoint35)
	(can_traverse rover4 waypoint36 waypoint25)
	(can_traverse rover4 waypoint25 waypoint36)
	(can_traverse rover4 waypoint13 waypoint12)
	(can_traverse rover4 waypoint12 waypoint13)
	(can_traverse rover4 waypoint13 waypoint23)
	(can_traverse rover4 waypoint23 waypoint13)
	(can_traverse rover4 waypoint13 waypoint29)
	(can_traverse rover4 waypoint29 waypoint13)
	(can_traverse rover4 waypoint14 waypoint11)
	(can_traverse rover4 waypoint11 waypoint14)
	(can_traverse rover4 waypoint14 waypoint31)
	(can_traverse rover4 waypoint31 waypoint14)
	(can_traverse rover4 waypoint14 waypoint44)
	(can_traverse rover4 waypoint44 waypoint14)
	(can_traverse rover4 waypoint14 waypoint49)
	(can_traverse rover4 waypoint49 waypoint14)
	(can_traverse rover4 waypoint16 waypoint21)
	(can_traverse rover4 waypoint21 waypoint16)
	(can_traverse rover4 waypoint37 waypoint28)
	(can_traverse rover4 waypoint28 waypoint37)
	(can_traverse rover4 waypoint37 waypoint30)
	(can_traverse rover4 waypoint30 waypoint37)
	(can_traverse rover4 waypoint45 waypoint8)
	(can_traverse rover4 waypoint8 waypoint45)
	(can_traverse rover4 waypoint4 waypoint3)
	(can_traverse rover4 waypoint3 waypoint4)
	(can_traverse rover4 waypoint17 waypoint2)
	(can_traverse rover4 waypoint2 waypoint17)
	(can_traverse rover4 waypoint43 waypoint0)
	(can_traverse rover4 waypoint0 waypoint43)
	(can_traverse rover4 waypoint32 waypoint20)
	(can_traverse rover4 waypoint20 waypoint32)
	(can_traverse rover4 waypoint33 waypoint34)
	(can_traverse rover4 waypoint34 waypoint33)
	(at rover5 waypoint37)
	(available rover5)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_soil_analysis rover5)
	(equipped_for_rock_analysis rover5)
	(equipped_for_imaging rover5)
	(can_traverse rover5 waypoint37 waypoint1)
	(can_traverse rover5 waypoint1 waypoint37)
	(can_traverse rover5 waypoint37 waypoint10)
	(can_traverse rover5 waypoint10 waypoint37)
	(can_traverse rover5 waypoint37 waypoint30)
	(can_traverse rover5 waypoint30 waypoint37)
	(can_traverse rover5 waypoint37 waypoint35)
	(can_traverse rover5 waypoint35 waypoint37)
	(can_traverse rover5 waypoint37 waypoint43)
	(can_traverse rover5 waypoint43 waypoint37)
	(can_traverse rover5 waypoint37 waypoint45)
	(can_traverse rover5 waypoint45 waypoint37)
	(can_traverse rover5 waypoint1 waypoint0)
	(can_traverse rover5 waypoint0 waypoint1)
	(can_traverse rover5 waypoint1 waypoint13)
	(can_traverse rover5 waypoint13 waypoint1)
	(can_traverse rover5 waypoint1 waypoint14)
	(can_traverse rover5 waypoint14 waypoint1)
	(can_traverse rover5 waypoint1 waypoint16)
	(can_traverse rover5 waypoint16 waypoint1)
	(can_traverse rover5 waypoint1 waypoint38)
	(can_traverse rover5 waypoint38 waypoint1)
	(can_traverse rover5 waypoint1 waypoint41)
	(can_traverse rover5 waypoint41 waypoint1)
	(can_traverse rover5 waypoint10 waypoint5)
	(can_traverse rover5 waypoint5 waypoint10)
	(can_traverse rover5 waypoint10 waypoint8)
	(can_traverse rover5 waypoint8 waypoint10)
	(can_traverse rover5 waypoint10 waypoint27)
	(can_traverse rover5 waypoint27 waypoint10)
	(can_traverse rover5 waypoint10 waypoint28)
	(can_traverse rover5 waypoint28 waypoint10)
	(can_traverse rover5 waypoint30 waypoint9)
	(can_traverse rover5 waypoint9 waypoint30)
	(can_traverse rover5 waypoint30 waypoint19)
	(can_traverse rover5 waypoint19 waypoint30)
	(can_traverse rover5 waypoint30 waypoint20)
	(can_traverse rover5 waypoint20 waypoint30)
	(can_traverse rover5 waypoint30 waypoint29)
	(can_traverse rover5 waypoint29 waypoint30)
	(can_traverse rover5 waypoint35 waypoint6)
	(can_traverse rover5 waypoint6 waypoint35)
	(can_traverse rover5 waypoint35 waypoint7)
	(can_traverse rover5 waypoint7 waypoint35)
	(can_traverse rover5 waypoint35 waypoint18)
	(can_traverse rover5 waypoint18 waypoint35)
	(can_traverse rover5 waypoint35 waypoint32)
	(can_traverse rover5 waypoint32 waypoint35)
	(can_traverse rover5 waypoint35 waypoint33)
	(can_traverse rover5 waypoint33 waypoint35)
	(can_traverse rover5 waypoint35 waypoint42)
	(can_traverse rover5 waypoint42 waypoint35)
	(can_traverse rover5 waypoint43 waypoint24)
	(can_traverse rover5 waypoint24 waypoint43)
	(can_traverse rover5 waypoint43 waypoint31)
	(can_traverse rover5 waypoint31 waypoint43)
	(can_traverse rover5 waypoint43 waypoint40)
	(can_traverse rover5 waypoint40 waypoint43)
	(can_traverse rover5 waypoint45 waypoint23)
	(can_traverse rover5 waypoint23 waypoint45)
	(can_traverse rover5 waypoint0 waypoint26)
	(can_traverse rover5 waypoint26 waypoint0)
	(can_traverse rover5 waypoint13 waypoint12)
	(can_traverse rover5 waypoint12 waypoint13)
	(can_traverse rover5 waypoint13 waypoint22)
	(can_traverse rover5 waypoint22 waypoint13)
	(can_traverse rover5 waypoint14 waypoint49)
	(can_traverse rover5 waypoint49 waypoint14)
	(can_traverse rover5 waypoint16 waypoint15)
	(can_traverse rover5 waypoint15 waypoint16)
	(can_traverse rover5 waypoint16 waypoint21)
	(can_traverse rover5 waypoint21 waypoint16)
	(can_traverse rover5 waypoint38 waypoint25)
	(can_traverse rover5 waypoint25 waypoint38)
	(can_traverse rover5 waypoint38 waypoint36)
	(can_traverse rover5 waypoint36 waypoint38)
	(can_traverse rover5 waypoint41 waypoint47)
	(can_traverse rover5 waypoint47 waypoint41)
	(can_traverse rover5 waypoint5 waypoint4)
	(can_traverse rover5 waypoint4 waypoint5)
	(can_traverse rover5 waypoint5 waypoint17)
	(can_traverse rover5 waypoint17 waypoint5)
	(can_traverse rover5 waypoint5 waypoint39)
	(can_traverse rover5 waypoint39 waypoint5)
	(can_traverse rover5 waypoint5 waypoint46)
	(can_traverse rover5 waypoint46 waypoint5)
	(can_traverse rover5 waypoint8 waypoint3)
	(can_traverse rover5 waypoint3 waypoint8)
	(can_traverse rover5 waypoint28 waypoint2)
	(can_traverse rover5 waypoint2 waypoint28)
	(can_traverse rover5 waypoint19 waypoint11)
	(can_traverse rover5 waypoint11 waypoint19)
	(can_traverse rover5 waypoint7 waypoint44)
	(can_traverse rover5 waypoint44 waypoint7)
	(can_traverse rover5 waypoint32 waypoint48)
	(can_traverse rover5 waypoint48 waypoint32)
	(can_traverse rover5 waypoint33 waypoint34)
	(can_traverse rover5 waypoint34 waypoint33)
	(at rover6 waypoint26)
	(available rover6)
	(store_of rover6store rover6)
	(empty rover6store)
	(equipped_for_soil_analysis rover6)
	(equipped_for_rock_analysis rover6)
	(equipped_for_imaging rover6)
	(can_traverse rover6 waypoint26 waypoint0)
	(can_traverse rover6 waypoint0 waypoint26)
	(can_traverse rover6 waypoint26 waypoint19)
	(can_traverse rover6 waypoint19 waypoint26)
	(can_traverse rover6 waypoint26 waypoint22)
	(can_traverse rover6 waypoint22 waypoint26)
	(can_traverse rover6 waypoint0 waypoint20)
	(can_traverse rover6 waypoint20 waypoint0)
	(can_traverse rover6 waypoint0 waypoint28)
	(can_traverse rover6 waypoint28 waypoint0)
	(can_traverse rover6 waypoint0 waypoint43)
	(can_traverse rover6 waypoint43 waypoint0)
	(can_traverse rover6 waypoint19 waypoint5)
	(can_traverse rover6 waypoint5 waypoint19)
	(can_traverse rover6 waypoint19 waypoint11)
	(can_traverse rover6 waypoint11 waypoint19)
	(can_traverse rover6 waypoint19 waypoint25)
	(can_traverse rover6 waypoint25 waypoint19)
	(can_traverse rover6 waypoint19 waypoint30)
	(can_traverse rover6 waypoint30 waypoint19)
	(can_traverse rover6 waypoint19 waypoint33)
	(can_traverse rover6 waypoint33 waypoint19)
	(can_traverse rover6 waypoint19 waypoint44)
	(can_traverse rover6 waypoint44 waypoint19)
	(can_traverse rover6 waypoint19 waypoint46)
	(can_traverse rover6 waypoint46 waypoint19)
	(can_traverse rover6 waypoint22 waypoint3)
	(can_traverse rover6 waypoint3 waypoint22)
	(can_traverse rover6 waypoint22 waypoint6)
	(can_traverse rover6 waypoint6 waypoint22)
	(can_traverse rover6 waypoint22 waypoint13)
	(can_traverse rover6 waypoint13 waypoint22)
	(can_traverse rover6 waypoint22 waypoint17)
	(can_traverse rover6 waypoint17 waypoint22)
	(can_traverse rover6 waypoint22 waypoint38)
	(can_traverse rover6 waypoint38 waypoint22)
	(can_traverse rover6 waypoint22 waypoint47)
	(can_traverse rover6 waypoint47 waypoint22)
	(can_traverse rover6 waypoint20 waypoint31)
	(can_traverse rover6 waypoint31 waypoint20)
	(can_traverse rover6 waypoint20 waypoint32)
	(can_traverse rover6 waypoint32 waypoint20)
	(can_traverse rover6 waypoint28 waypoint2)
	(can_traverse rover6 waypoint2 waypoint28)
	(can_traverse rover6 waypoint28 waypoint8)
	(can_traverse rover6 waypoint8 waypoint28)
	(can_traverse rover6 waypoint28 waypoint18)
	(can_traverse rover6 waypoint18 waypoint28)
	(can_traverse rover6 waypoint28 waypoint41)
	(can_traverse rover6 waypoint41 waypoint28)
	(can_traverse rover6 waypoint43 waypoint14)
	(can_traverse rover6 waypoint14 waypoint43)
	(can_traverse rover6 waypoint43 waypoint16)
	(can_traverse rover6 waypoint16 waypoint43)
	(can_traverse rover6 waypoint43 waypoint27)
	(can_traverse rover6 waypoint27 waypoint43)
	(can_traverse rover6 waypoint43 waypoint37)
	(can_traverse rover6 waypoint37 waypoint43)
	(can_traverse rover6 waypoint43 waypoint40)
	(can_traverse rover6 waypoint40 waypoint43)
	(can_traverse rover6 waypoint43 waypoint42)
	(can_traverse rover6 waypoint42 waypoint43)
	(can_traverse rover6 waypoint5 waypoint4)
	(can_traverse rover6 waypoint4 waypoint5)
	(can_traverse rover6 waypoint5 waypoint39)
	(can_traverse rover6 waypoint39 waypoint5)
	(can_traverse rover6 waypoint5 waypoint49)
	(can_traverse rover6 waypoint49 waypoint5)
	(can_traverse rover6 waypoint11 waypoint15)
	(can_traverse rover6 waypoint15 waypoint11)
	(can_traverse rover6 waypoint11 waypoint29)
	(can_traverse rover6 waypoint29 waypoint11)
	(can_traverse rover6 waypoint25 waypoint12)
	(can_traverse rover6 waypoint12 waypoint25)
	(can_traverse rover6 waypoint25 waypoint36)
	(can_traverse rover6 waypoint36 waypoint25)
	(can_traverse rover6 waypoint25 waypoint48)
	(can_traverse rover6 waypoint48 waypoint25)
	(can_traverse rover6 waypoint33 waypoint34)
	(can_traverse rover6 waypoint34 waypoint33)
	(can_traverse rover6 waypoint44 waypoint7)
	(can_traverse rover6 waypoint7 waypoint44)
	(can_traverse rover6 waypoint44 waypoint23)
	(can_traverse rover6 waypoint23 waypoint44)
	(can_traverse rover6 waypoint3 waypoint24)
	(can_traverse rover6 waypoint24 waypoint3)
	(can_traverse rover6 waypoint6 waypoint10)
	(can_traverse rover6 waypoint10 waypoint6)
	(can_traverse rover6 waypoint6 waypoint35)
	(can_traverse rover6 waypoint35 waypoint6)
	(can_traverse rover6 waypoint6 waypoint45)
	(can_traverse rover6 waypoint45 waypoint6)
	(can_traverse rover6 waypoint13 waypoint1)
	(can_traverse rover6 waypoint1 waypoint13)
	(can_traverse rover6 waypoint8 waypoint21)
	(can_traverse rover6 waypoint21 waypoint8)
	(can_traverse rover6 waypoint14 waypoint9)
	(can_traverse rover6 waypoint9 waypoint14)
	(at rover7 waypoint30)
	(available rover7)
	(store_of rover7store rover7)
	(empty rover7store)
	(equipped_for_rock_analysis rover7)
	(equipped_for_imaging rover7)
	(can_traverse rover7 waypoint30 waypoint9)
	(can_traverse rover7 waypoint9 waypoint30)
	(can_traverse rover7 waypoint30 waypoint19)
	(can_traverse rover7 waypoint19 waypoint30)
	(can_traverse rover7 waypoint30 waypoint20)
	(can_traverse rover7 waypoint20 waypoint30)
	(can_traverse rover7 waypoint30 waypoint28)
	(can_traverse rover7 waypoint28 waypoint30)
	(can_traverse rover7 waypoint30 waypoint29)
	(can_traverse rover7 waypoint29 waypoint30)
	(can_traverse rover7 waypoint30 waypoint45)
	(can_traverse rover7 waypoint45 waypoint30)
	(can_traverse rover7 waypoint30 waypoint49)
	(can_traverse rover7 waypoint49 waypoint30)
	(can_traverse rover7 waypoint9 waypoint6)
	(can_traverse rover7 waypoint6 waypoint9)
	(can_traverse rover7 waypoint9 waypoint7)
	(can_traverse rover7 waypoint7 waypoint9)
	(can_traverse rover7 waypoint9 waypoint12)
	(can_traverse rover7 waypoint12 waypoint9)
	(can_traverse rover7 waypoint9 waypoint23)
	(can_traverse rover7 waypoint23 waypoint9)
	(can_traverse rover7 waypoint9 waypoint35)
	(can_traverse rover7 waypoint35 waypoint9)
	(can_traverse rover7 waypoint19 waypoint11)
	(can_traverse rover7 waypoint11 waypoint19)
	(can_traverse rover7 waypoint19 waypoint17)
	(can_traverse rover7 waypoint17 waypoint19)
	(can_traverse rover7 waypoint19 waypoint22)
	(can_traverse rover7 waypoint22 waypoint19)
	(can_traverse rover7 waypoint19 waypoint25)
	(can_traverse rover7 waypoint25 waypoint19)
	(can_traverse rover7 waypoint19 waypoint44)
	(can_traverse rover7 waypoint44 waypoint19)
	(can_traverse rover7 waypoint20 waypoint32)
	(can_traverse rover7 waypoint32 waypoint20)
	(can_traverse rover7 waypoint28 waypoint2)
	(can_traverse rover7 waypoint2 waypoint28)
	(can_traverse rover7 waypoint28 waypoint3)
	(can_traverse rover7 waypoint3 waypoint28)
	(can_traverse rover7 waypoint28 waypoint8)
	(can_traverse rover7 waypoint8 waypoint28)
	(can_traverse rover7 waypoint28 waypoint13)
	(can_traverse rover7 waypoint13 waypoint28)
	(can_traverse rover7 waypoint28 waypoint18)
	(can_traverse rover7 waypoint18 waypoint28)
	(can_traverse rover7 waypoint28 waypoint41)
	(can_traverse rover7 waypoint41 waypoint28)
	(can_traverse rover7 waypoint29 waypoint39)
	(can_traverse rover7 waypoint39 waypoint29)
	(can_traverse rover7 waypoint45 waypoint1)
	(can_traverse rover7 waypoint1 waypoint45)
	(can_traverse rover7 waypoint45 waypoint26)
	(can_traverse rover7 waypoint26 waypoint45)
	(can_traverse rover7 waypoint45 waypoint31)
	(can_traverse rover7 waypoint31 waypoint45)
	(can_traverse rover7 waypoint45 waypoint37)
	(can_traverse rover7 waypoint37 waypoint45)
	(can_traverse rover7 waypoint49 waypoint5)
	(can_traverse rover7 waypoint5 waypoint49)
	(can_traverse rover7 waypoint49 waypoint14)
	(can_traverse rover7 waypoint14 waypoint49)
	(can_traverse rover7 waypoint49 waypoint27)
	(can_traverse rover7 waypoint27 waypoint49)
	(can_traverse rover7 waypoint49 waypoint33)
	(can_traverse rover7 waypoint33 waypoint49)
	(can_traverse rover7 waypoint49 waypoint46)
	(can_traverse rover7 waypoint46 waypoint49)
	(can_traverse rover7 waypoint7 waypoint4)
	(can_traverse rover7 waypoint4 waypoint7)
	(can_traverse rover7 waypoint12 waypoint15)
	(can_traverse rover7 waypoint15 waypoint12)
	(can_traverse rover7 waypoint12 waypoint40)
	(can_traverse rover7 waypoint40 waypoint12)
	(can_traverse rover7 waypoint23 waypoint16)
	(can_traverse rover7 waypoint16 waypoint23)
	(can_traverse rover7 waypoint23 waypoint47)
	(can_traverse rover7 waypoint47 waypoint23)
	(can_traverse rover7 waypoint35 waypoint42)
	(can_traverse rover7 waypoint42 waypoint35)
	(can_traverse rover7 waypoint35 waypoint43)
	(can_traverse rover7 waypoint43 waypoint35)
	(can_traverse rover7 waypoint11 waypoint0)
	(can_traverse rover7 waypoint0 waypoint11)
	(can_traverse rover7 waypoint22 waypoint38)
	(can_traverse rover7 waypoint38 waypoint22)
	(can_traverse rover7 waypoint22 waypoint48)
	(can_traverse rover7 waypoint48 waypoint22)
	(can_traverse rover7 waypoint3 waypoint24)
	(can_traverse rover7 waypoint24 waypoint3)
	(can_traverse rover7 waypoint8 waypoint10)
	(can_traverse rover7 waypoint10 waypoint8)
	(can_traverse rover7 waypoint8 waypoint21)
	(can_traverse rover7 waypoint21 waypoint8)
	(can_traverse rover7 waypoint41 waypoint36)
	(can_traverse rover7 waypoint36 waypoint41)
	(can_traverse rover7 waypoint33 waypoint34)
	(can_traverse rover7 waypoint34 waypoint33)
	(at rover8 waypoint47)
	(available rover8)
	(store_of rover8store rover8)
	(empty rover8store)
	(equipped_for_soil_analysis rover8)
	(equipped_for_rock_analysis rover8)
	(can_traverse rover8 waypoint47 waypoint8)
	(can_traverse rover8 waypoint8 waypoint47)
	(can_traverse rover8 waypoint47 waypoint12)
	(can_traverse rover8 waypoint12 waypoint47)
	(can_traverse rover8 waypoint47 waypoint15)
	(can_traverse rover8 waypoint15 waypoint47)
	(can_traverse rover8 waypoint47 waypoint22)
	(can_traverse rover8 waypoint22 waypoint47)
	(can_traverse rover8 waypoint47 waypoint23)
	(can_traverse rover8 waypoint23 waypoint47)
	(can_traverse rover8 waypoint47 waypoint31)
	(can_traverse rover8 waypoint31 waypoint47)
	(can_traverse rover8 waypoint47 waypoint39)
	(can_traverse rover8 waypoint39 waypoint47)
	(can_traverse rover8 waypoint8 waypoint3)
	(can_traverse rover8 waypoint3 waypoint8)
	(can_traverse rover8 waypoint8 waypoint5)
	(can_traverse rover8 waypoint5 waypoint8)
	(can_traverse rover8 waypoint8 waypoint6)
	(can_traverse rover8 waypoint6 waypoint8)
	(can_traverse rover8 waypoint8 waypoint13)
	(can_traverse rover8 waypoint13 waypoint8)
	(can_traverse rover8 waypoint8 waypoint21)
	(can_traverse rover8 waypoint21 waypoint8)
	(can_traverse rover8 waypoint8 waypoint28)
	(can_traverse rover8 waypoint28 waypoint8)
	(can_traverse rover8 waypoint8 waypoint29)
	(can_traverse rover8 waypoint29 waypoint8)
	(can_traverse rover8 waypoint8 waypoint45)
	(can_traverse rover8 waypoint45 waypoint8)
	(can_traverse rover8 waypoint12 waypoint9)
	(can_traverse rover8 waypoint9 waypoint12)
	(can_traverse rover8 waypoint12 waypoint18)
	(can_traverse rover8 waypoint18 waypoint12)
	(can_traverse rover8 waypoint12 waypoint32)
	(can_traverse rover8 waypoint32 waypoint12)
	(can_traverse rover8 waypoint12 waypoint40)
	(can_traverse rover8 waypoint40 waypoint12)
	(can_traverse rover8 waypoint12 waypoint44)
	(can_traverse rover8 waypoint44 waypoint12)
	(can_traverse rover8 waypoint12 waypoint49)
	(can_traverse rover8 waypoint49 waypoint12)
	(can_traverse rover8 waypoint15 waypoint2)
	(can_traverse rover8 waypoint2 waypoint15)
	(can_traverse rover8 waypoint15 waypoint11)
	(can_traverse rover8 waypoint11 waypoint15)
	(can_traverse rover8 waypoint15 waypoint17)
	(can_traverse rover8 waypoint17 waypoint15)
	(can_traverse rover8 waypoint15 waypoint24)
	(can_traverse rover8 waypoint24 waypoint15)
	(can_traverse rover8 waypoint15 waypoint27)
	(can_traverse rover8 waypoint27 waypoint15)
	(can_traverse rover8 waypoint15 waypoint41)
	(can_traverse rover8 waypoint41 waypoint15)
	(can_traverse rover8 waypoint15 waypoint42)
	(can_traverse rover8 waypoint42 waypoint15)
	(can_traverse rover8 waypoint22 waypoint19)
	(can_traverse rover8 waypoint19 waypoint22)
	(can_traverse rover8 waypoint22 waypoint26)
	(can_traverse rover8 waypoint26 waypoint22)
	(can_traverse rover8 waypoint22 waypoint38)
	(can_traverse rover8 waypoint38 waypoint22)
	(can_traverse rover8 waypoint22 waypoint43)
	(can_traverse rover8 waypoint43 waypoint22)
	(can_traverse rover8 waypoint22 waypoint48)
	(can_traverse rover8 waypoint48 waypoint22)
	(can_traverse rover8 waypoint23 waypoint4)
	(can_traverse rover8 waypoint4 waypoint23)
	(can_traverse rover8 waypoint23 waypoint34)
	(can_traverse rover8 waypoint34 waypoint23)
	(can_traverse rover8 waypoint31 waypoint14)
	(can_traverse rover8 waypoint14 waypoint31)
	(can_traverse rover8 waypoint31 waypoint20)
	(can_traverse rover8 waypoint20 waypoint31)
	(can_traverse rover8 waypoint31 waypoint46)
	(can_traverse rover8 waypoint46 waypoint31)
	(can_traverse rover8 waypoint39 waypoint7)
	(can_traverse rover8 waypoint7 waypoint39)
	(can_traverse rover8 waypoint3 waypoint36)
	(can_traverse rover8 waypoint36 waypoint3)
	(can_traverse rover8 waypoint5 waypoint10)
	(can_traverse rover8 waypoint10 waypoint5)
	(can_traverse rover8 waypoint6 waypoint25)
	(can_traverse rover8 waypoint25 waypoint6)
	(can_traverse rover8 waypoint6 waypoint35)
	(can_traverse rover8 waypoint35 waypoint6)
	(can_traverse rover8 waypoint21 waypoint16)
	(can_traverse rover8 waypoint16 waypoint21)
	(can_traverse rover8 waypoint21 waypoint37)
	(can_traverse rover8 waypoint37 waypoint21)
	(can_traverse rover8 waypoint28 waypoint0)
	(can_traverse rover8 waypoint0 waypoint28)
	(can_traverse rover8 waypoint28 waypoint30)
	(can_traverse rover8 waypoint30 waypoint28)
	(can_traverse rover8 waypoint45 waypoint1)
	(can_traverse rover8 waypoint1 waypoint45)
	(can_traverse rover8 waypoint49 waypoint33)
	(can_traverse rover8 waypoint33 waypoint49)
	(at rover9 waypoint31)
	(available rover9)
	(store_of rover9store rover9)
	(empty rover9store)
	(equipped_for_soil_analysis rover9)
	(equipped_for_rock_analysis rover9)
	(equipped_for_imaging rover9)
	(can_traverse rover9 waypoint31 waypoint3)
	(can_traverse rover9 waypoint3 waypoint31)
	(can_traverse rover9 waypoint31 waypoint14)
	(can_traverse rover9 waypoint14 waypoint31)
	(can_traverse rover9 waypoint31 waypoint20)
	(can_traverse rover9 waypoint20 waypoint31)
	(can_traverse rover9 waypoint31 waypoint45)
	(can_traverse rover9 waypoint45 waypoint31)
	(can_traverse rover9 waypoint31 waypoint46)
	(can_traverse rover9 waypoint46 waypoint31)
	(can_traverse rover9 waypoint3 waypoint4)
	(can_traverse rover9 waypoint4 waypoint3)
	(can_traverse rover9 waypoint3 waypoint8)
	(can_traverse rover9 waypoint8 waypoint3)
	(can_traverse rover9 waypoint3 waypoint24)
	(can_traverse rover9 waypoint24 waypoint3)
	(can_traverse rover9 waypoint3 waypoint29)
	(can_traverse rover9 waypoint29 waypoint3)
	(can_traverse rover9 waypoint3 waypoint36)
	(can_traverse rover9 waypoint36 waypoint3)
	(can_traverse rover9 waypoint3 waypoint40)
	(can_traverse rover9 waypoint40 waypoint3)
	(can_traverse rover9 waypoint14 waypoint1)
	(can_traverse rover9 waypoint1 waypoint14)
	(can_traverse rover9 waypoint14 waypoint9)
	(can_traverse rover9 waypoint9 waypoint14)
	(can_traverse rover9 waypoint14 waypoint11)
	(can_traverse rover9 waypoint11 waypoint14)
	(can_traverse rover9 waypoint14 waypoint43)
	(can_traverse rover9 waypoint43 waypoint14)
	(can_traverse rover9 waypoint14 waypoint44)
	(can_traverse rover9 waypoint44 waypoint14)
	(can_traverse rover9 waypoint14 waypoint49)
	(can_traverse rover9 waypoint49 waypoint14)
	(can_traverse rover9 waypoint20 waypoint0)
	(can_traverse rover9 waypoint0 waypoint20)
	(can_traverse rover9 waypoint20 waypoint19)
	(can_traverse rover9 waypoint19 waypoint20)
	(can_traverse rover9 waypoint20 waypoint30)
	(can_traverse rover9 waypoint30 waypoint20)
	(can_traverse rover9 waypoint20 waypoint32)
	(can_traverse rover9 waypoint32 waypoint20)
	(can_traverse rover9 waypoint45 waypoint12)
	(can_traverse rover9 waypoint12 waypoint45)
	(can_traverse rover9 waypoint45 waypoint13)
	(can_traverse rover9 waypoint13 waypoint45)
	(can_traverse rover9 waypoint45 waypoint23)
	(can_traverse rover9 waypoint23 waypoint45)
	(can_traverse rover9 waypoint45 waypoint26)
	(can_traverse rover9 waypoint26 waypoint45)
	(can_traverse rover9 waypoint45 waypoint37)
	(can_traverse rover9 waypoint37 waypoint45)
	(can_traverse rover9 waypoint46 waypoint5)
	(can_traverse rover9 waypoint5 waypoint46)
	(can_traverse rover9 waypoint46 waypoint16)
	(can_traverse rover9 waypoint16 waypoint46)
	(can_traverse rover9 waypoint46 waypoint33)
	(can_traverse rover9 waypoint33 waypoint46)
	(can_traverse rover9 waypoint46 waypoint39)
	(can_traverse rover9 waypoint39 waypoint46)
	(can_traverse rover9 waypoint4 waypoint7)
	(can_traverse rover9 waypoint7 waypoint4)
	(can_traverse rover9 waypoint4 waypoint21)
	(can_traverse rover9 waypoint21 waypoint4)
	(can_traverse rover9 waypoint4 waypoint22)
	(can_traverse rover9 waypoint22 waypoint4)
	(can_traverse rover9 waypoint4 waypoint27)
	(can_traverse rover9 waypoint27 waypoint4)
	(can_traverse rover9 waypoint4 waypoint42)
	(can_traverse rover9 waypoint42 waypoint4)
	(can_traverse rover9 waypoint8 waypoint6)
	(can_traverse rover9 waypoint6 waypoint8)
	(can_traverse rover9 waypoint8 waypoint10)
	(can_traverse rover9 waypoint10 waypoint8)
	(can_traverse rover9 waypoint8 waypoint28)
	(can_traverse rover9 waypoint28 waypoint8)
	(can_traverse rover9 waypoint8 waypoint47)
	(can_traverse rover9 waypoint47 waypoint8)
	(can_traverse rover9 waypoint24 waypoint15)
	(can_traverse rover9 waypoint15 waypoint24)
	(can_traverse rover9 waypoint24 waypoint38)
	(can_traverse rover9 waypoint38 waypoint24)
	(can_traverse rover9 waypoint36 waypoint17)
	(can_traverse rover9 waypoint17 waypoint36)
	(can_traverse rover9 waypoint36 waypoint34)
	(can_traverse rover9 waypoint34 waypoint36)
	(can_traverse rover9 waypoint36 waypoint41)
	(can_traverse rover9 waypoint41 waypoint36)
	(can_traverse rover9 waypoint9 waypoint35)
	(can_traverse rover9 waypoint35 waypoint9)
	(can_traverse rover9 waypoint44 waypoint2)
	(can_traverse rover9 waypoint2 waypoint44)
	(can_traverse rover9 waypoint19 waypoint25)
	(can_traverse rover9 waypoint25 waypoint19)
	(can_traverse rover9 waypoint32 waypoint48)
	(can_traverse rover9 waypoint48 waypoint32)
	(on_board camera0 rover7)
	(calibration_target camera0 objective7)
	(supports camera0 low_res)
	(on_board camera1 rover2)
	(calibration_target camera1 objective3)
	(supports camera1 low_res)
	(on_board camera2 rover7)
	(calibration_target camera2 objective2)
	(supports camera2 colour)
	(on_board camera3 rover2)
	(calibration_target camera3 objective0)
	(supports camera3 colour)
	(supports camera3 low_res)
	(on_board camera4 rover1)
	(calibration_target camera4 objective6)
	(supports camera4 colour)
	(on_board camera5 rover0)
	(calibration_target camera5 objective3)
	(supports camera5 low_res)
	(on_board camera6 rover7)
	(calibration_target camera6 objective3)
	(supports camera6 colour)
	(supports camera6 low_res)
	(on_board camera7 rover9)
	(calibration_target camera7 objective2)
	(supports camera7 colour)
	(supports camera7 low_res)
	(on_board camera8 rover9)
	(calibration_target camera8 objective2)
	(supports camera8 high_res)
	(supports camera8 low_res)
	(on_board camera9 rover6)
	(calibration_target camera9 objective0)
	(supports camera9 low_res)
	(on_board camera10 rover6)
	(calibration_target camera10 objective0)
	(supports camera10 colour)
	(supports camera10 low_res)
	(on_board camera11 rover0)
	(calibration_target camera11 objective4)
	(supports camera11 low_res)
	(on_board camera12 rover2)
	(calibration_target camera12 objective0)
	(supports camera12 high_res)
	(supports camera12 low_res)
	(on_board camera13 rover3)
	(calibration_target camera13 objective0)
	(supports camera13 low_res)
	(on_board camera14 rover4)
	(calibration_target camera14 objective2)
	(supports camera14 colour)
	(supports camera14 high_res)
	(supports camera14 low_res)
	(on_board camera15 rover5)
	(calibration_target camera15 objective5)
	(supports camera15 high_res)
	(supports camera15 low_res)
	(visible_from objective0 waypoint0)
	(visible_from objective0 waypoint1)
	(visible_from objective0 waypoint2)
	(visible_from objective0 waypoint3)
	(visible_from objective0 waypoint4)
	(visible_from objective0 waypoint5)
	(visible_from objective0 waypoint6)
	(visible_from objective0 waypoint7)
	(visible_from objective0 waypoint8)
	(visible_from objective0 waypoint9)
	(visible_from objective0 waypoint10)
	(visible_from objective0 waypoint11)
	(visible_from objective0 waypoint12)
	(visible_from objective0 waypoint13)
	(visible_from objective0 waypoint14)
	(visible_from objective0 waypoint15)
	(visible_from objective0 waypoint16)
	(visible_from objective0 waypoint17)
	(visible_from objective0 waypoint18)
	(visible_from objective0 waypoint19)
	(visible_from objective0 waypoint20)
	(visible_from objective0 waypoint21)
	(visible_from objective0 waypoint22)
	(visible_from objective0 waypoint23)
	(visible_from objective0 waypoint24)
	(visible_from objective0 waypoint25)
	(visible_from objective0 waypoint26)
	(visible_from objective0 waypoint27)
	(visible_from objective0 waypoint28)
	(visible_from objective0 waypoint29)
	(visible_from objective1 waypoint0)
	(visible_from objective1 waypoint1)
	(visible_from objective1 waypoint2)
	(visible_from objective1 waypoint3)
	(visible_from objective1 waypoint4)
	(visible_from objective1 waypoint5)
	(visible_from objective1 waypoint6)
	(visible_from objective1 waypoint7)
	(visible_from objective1 waypoint8)
	(visible_from objective1 waypoint9)
	(visible_from objective1 waypoint10)
	(visible_from objective1 waypoint11)
	(visible_from objective1 waypoint12)
	(visible_from objective1 waypoint13)
	(visible_from objective1 waypoint14)
	(visible_from objective1 waypoint15)
	(visible_from objective1 waypoint16)
	(visible_from objective1 waypoint17)
	(visible_from objective1 waypoint18)
	(visible_from objective1 waypoint19)
	(visible_from objective1 waypoint20)
	(visible_from objective1 waypoint21)
	(visible_from objective1 waypoint22)
	(visible_from objective1 waypoint23)
	(visible_from objective1 waypoint24)
	(visible_from objective1 waypoint25)
	(visible_from objective1 waypoint26)
	(visible_from objective1 waypoint27)
	(visible_from objective1 waypoint28)
	(visible_from objective1 waypoint29)
	(visible_from objective1 waypoint30)
	(visible_from objective1 waypoint31)
	(visible_from objective1 waypoint32)
	(visible_from objective1 waypoint33)
	(visible_from objective1 waypoint34)
	(visible_from objective1 waypoint35)
	(visible_from objective1 waypoint36)
	(visible_from objective1 waypoint37)
	(visible_from objective1 waypoint38)
	(visible_from objective1 waypoint39)
	(visible_from objective1 waypoint40)
	(visible_from objective1 waypoint41)
	(visible_from objective1 waypoint42)
	(visible_from objective1 waypoint43)
	(visible_from objective1 waypoint44)
	(visible_from objective1 waypoint45)
	(visible_from objective1 waypoint46)
	(visible_from objective1 waypoint47)
	(visible_from objective1 waypoint48)
	(visible_from objective2 waypoint0)
	(visible_from objective2 waypoint1)
	(visible_from objective2 waypoint2)
	(visible_from objective2 waypoint3)
	(visible_from objective2 waypoint4)
	(visible_from objective2 waypoint5)
	(visible_from objective2 waypoint6)
	(visible_from objective2 waypoint7)
	(visible_from objective2 waypoint8)
	(visible_from objective2 waypoint9)
	(visible_from objective3 waypoint0)
	(visible_from objective3 waypoint1)
	(visible_from objective3 waypoint2)
	(visible_from objective3 waypoint3)
	(visible_from objective3 waypoint4)
	(visible_from objective3 waypoint5)
	(visible_from objective3 waypoint6)
	(visible_from objective3 waypoint7)
	(visible_from objective3 waypoint8)
	(visible_from objective3 waypoint9)
	(visible_from objective3 waypoint10)
	(visible_from objective3 waypoint11)
	(visible_from objective3 waypoint12)
	(visible_from objective3 waypoint13)
	(visible_from objective3 waypoint14)
	(visible_from objective3 waypoint15)
	(visible_from objective3 waypoint16)
	(visible_from objective3 waypoint17)
	(visible_from objective3 waypoint18)
	(visible_from objective3 waypoint19)
	(visible_from objective3 waypoint20)
	(visible_from objective3 waypoint21)
	(visible_from objective3 waypoint22)
	(visible_from objective3 waypoint23)
	(visible_from objective3 waypoint24)
	(visible_from objective3 waypoint25)
	(visible_from objective3 waypoint26)
	(visible_from objective3 waypoint27)
	(visible_from objective3 waypoint28)
	(visible_from objective3 waypoint29)
	(visible_from objective3 waypoint30)
	(visible_from objective3 waypoint31)
	(visible_from objective3 waypoint32)
	(visible_from objective3 waypoint33)
	(visible_from objective3 waypoint34)
	(visible_from objective3 waypoint35)
	(visible_from objective3 waypoint36)
	(visible_from objective3 waypoint37)
	(visible_from objective3 waypoint38)
	(visible_from objective3 waypoint39)
	(visible_from objective3 waypoint40)
	(visible_from objective3 waypoint41)
	(visible_from objective3 waypoint42)
	(visible_from objective4 waypoint0)
	(visible_from objective4 waypoint1)
	(visible_from objective4 waypoint2)
	(visible_from objective4 waypoint3)
	(visible_from objective4 waypoint4)
	(visible_from objective4 waypoint5)
	(visible_from objective4 waypoint6)
	(visible_from objective4 waypoint7)
	(visible_from objective4 waypoint8)
	(visible_from objective4 waypoint9)
	(visible_from objective4 waypoint10)
	(visible_from objective4 waypoint11)
	(visible_from objective4 waypoint12)
	(visible_from objective4 waypoint13)
	(visible_from objective4 waypoint14)
	(visible_from objective4 waypoint15)
	(visible_from objective4 waypoint16)
	(visible_from objective4 waypoint17)
	(visible_from objective4 waypoint18)
	(visible_from objective4 waypoint19)
	(visible_from objective4 waypoint20)
	(visible_from objective4 waypoint21)
	(visible_from objective4 waypoint22)
	(visible_from objective4 waypoint23)
	(visible_from objective4 waypoint24)
	(visible_from objective4 waypoint25)
	(visible_from objective4 waypoint26)
	(visible_from objective4 waypoint27)
	(visible_from objective4 waypoint28)
	(visible_from objective4 waypoint29)
	(visible_from objective4 waypoint30)
	(visible_from objective4 waypoint31)
	(visible_from objective4 waypoint32)
	(visible_from objective4 waypoint33)
	(visible_from objective4 waypoint34)
	(visible_from objective5 waypoint0)
	(visible_from objective5 waypoint1)
	(visible_from objective5 waypoint2)
	(visible_from objective5 waypoint3)
	(visible_from objective5 waypoint4)
	(visible_from objective5 waypoint5)
	(visible_from objective5 waypoint6)
	(visible_from objective5 waypoint7)
	(visible_from objective5 waypoint8)
	(visible_from objective5 waypoint9)
	(visible_from objective5 waypoint10)
	(visible_from objective5 waypoint11)
	(visible_from objective5 waypoint12)
	(visible_from objective5 waypoint13)
	(visible_from objective5 waypoint14)
	(visible_from objective5 waypoint15)
	(visible_from objective5 waypoint16)
	(visible_from objective5 waypoint17)
	(visible_from objective5 waypoint18)
	(visible_from objective5 waypoint19)
	(visible_from objective5 waypoint20)
	(visible_from objective5 waypoint21)
	(visible_from objective5 waypoint22)
	(visible_from objective5 waypoint23)
	(visible_from objective5 waypoint24)
	(visible_from objective5 waypoint25)
	(visible_from objective5 waypoint26)
	(visible_from objective5 waypoint27)
	(visible_from objective5 waypoint28)
	(visible_from objective5 waypoint29)
	(visible_from objective5 waypoint30)
	(visible_from objective5 waypoint31)
	(visible_from objective5 waypoint32)
	(visible_from objective5 waypoint33)
	(visible_from objective5 waypoint34)
	(visible_from objective5 waypoint35)
	(visible_from objective5 waypoint36)
	(visible_from objective5 waypoint37)
	(visible_from objective5 waypoint38)
	(visible_from objective5 waypoint39)
	(visible_from objective5 waypoint40)
	(visible_from objective5 waypoint41)
	(visible_from objective5 waypoint42)
	(visible_from objective5 waypoint43)
	(visible_from objective5 waypoint44)
	(visible_from objective6 waypoint0)
	(visible_from objective6 waypoint1)
	(visible_from objective6 waypoint2)
	(visible_from objective6 waypoint3)
	(visible_from objective6 waypoint4)
	(visible_from objective6 waypoint5)
	(visible_from objective6 waypoint6)
	(visible_from objective6 waypoint7)
	(visible_from objective6 waypoint8)
	(visible_from objective6 waypoint9)
	(visible_from objective6 waypoint10)
	(visible_from objective6 waypoint11)
	(visible_from objective6 waypoint12)
	(visible_from objective6 waypoint13)
	(visible_from objective6 waypoint14)
	(visible_from objective6 waypoint15)
	(visible_from objective6 waypoint16)
	(visible_from objective6 waypoint17)
	(visible_from objective6 waypoint18)
	(visible_from objective6 waypoint19)
	(visible_from objective6 waypoint20)
	(visible_from objective7 waypoint0)
	(visible_from objective7 waypoint1)
	(visible_from objective7 waypoint2)
	(visible_from objective7 waypoint3)
	(visible_from objective7 waypoint4)
	(visible_from objective7 waypoint5)
)

(:goal (and
(communicated_soil_data waypoint36)
(communicated_soil_data waypoint25)
(communicated_soil_data waypoint19)
(communicated_soil_data waypoint47)
(communicated_soil_data waypoint32)
(communicated_soil_data waypoint4)
(communicated_soil_data waypoint8)
(communicated_soil_data waypoint13)
(communicated_soil_data waypoint23)
(communicated_soil_data waypoint16)
(communicated_soil_data waypoint45)
(communicated_soil_data waypoint0)
(communicated_soil_data waypoint31)
(communicated_soil_data waypoint43)
(communicated_soil_data waypoint20)
(communicated_soil_data waypoint49)
(communicated_soil_data waypoint35)
(communicated_soil_data waypoint9)
(communicated_soil_data waypoint3)
(communicated_soil_data waypoint40)
(communicated_soil_data waypoint11)
(communicated_soil_data waypoint30)
(communicated_rock_data waypoint0)
(communicated_rock_data waypoint34)
(communicated_rock_data waypoint15)
(communicated_rock_data waypoint11)
(communicated_rock_data waypoint3)
(communicated_rock_data waypoint44)
(communicated_rock_data waypoint36)
(communicated_rock_data waypoint5)
(communicated_rock_data waypoint8)
(communicated_rock_data waypoint23)
(communicated_rock_data waypoint48)
(communicated_rock_data waypoint39)
(communicated_rock_data waypoint35)
(communicated_rock_data waypoint10)
(communicated_rock_data waypoint28)
(communicated_image_data objective5 low_res)
(communicated_image_data objective2 low_res)
(communicated_image_data objective1 high_res)
(communicated_image_data objective4 low_res)
(communicated_image_data objective4 high_res)
(communicated_image_data objective3 colour)
	)
)
)
