(define (problem roverprob8218) (:domain rover)
(:objects
	general - lander
	colour high_res low_res - mode
	rover0 rover1 rover2 rover3 rover4 rover5 rover6 rover7 rover8 rover9 - rover
	rover0store rover1store rover2store rover3store rover4store rover5store rover6store rover7store rover8store rover9store - store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 waypoint40 waypoint41 waypoint42 waypoint43 waypoint44 waypoint45 waypoint46 waypoint47 waypoint48 waypoint49 - waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 camera11 camera12 camera13 camera14 camera15 camera16 camera17 - camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - objective
	)
(:init
	(visible waypoint0 waypoint5)
	(visible waypoint5 waypoint0)
	(visible waypoint0 waypoint14)
	(visible waypoint14 waypoint0)
	(visible waypoint0 waypoint31)
	(visible waypoint31 waypoint0)
	(visible waypoint0 waypoint32)
	(visible waypoint32 waypoint0)
	(visible waypoint0 waypoint34)
	(visible waypoint34 waypoint0)
	(visible waypoint0 waypoint49)
	(visible waypoint49 waypoint0)
	(visible waypoint1 waypoint15)
	(visible waypoint15 waypoint1)
	(visible waypoint1 waypoint21)
	(visible waypoint21 waypoint1)
	(visible waypoint1 waypoint25)
	(visible waypoint25 waypoint1)
	(visible waypoint1 waypoint48)
	(visible waypoint48 waypoint1)
	(visible waypoint2 waypoint8)
	(visible waypoint8 waypoint2)
	(visible waypoint2 waypoint10)
	(visible waypoint10 waypoint2)
	(visible waypoint2 waypoint13)
	(visible waypoint13 waypoint2)
	(visible waypoint2 waypoint20)
	(visible waypoint20 waypoint2)
	(visible waypoint2 waypoint21)
	(visible waypoint21 waypoint2)
	(visible waypoint2 waypoint36)
	(visible waypoint36 waypoint2)
	(visible waypoint3 waypoint0)
	(visible waypoint0 waypoint3)
	(visible waypoint3 waypoint20)
	(visible waypoint20 waypoint3)
	(visible waypoint3 waypoint40)
	(visible waypoint40 waypoint3)
	(visible waypoint4 waypoint1)
	(visible waypoint1 waypoint4)
	(visible waypoint4 waypoint12)
	(visible waypoint12 waypoint4)
	(visible waypoint4 waypoint22)
	(visible waypoint22 waypoint4)
	(visible waypoint4 waypoint31)
	(visible waypoint31 waypoint4)
	(visible waypoint4 waypoint41)
	(visible waypoint41 waypoint4)
	(visible waypoint4 waypoint44)
	(visible waypoint44 waypoint4)
	(visible waypoint4 waypoint47)
	(visible waypoint47 waypoint4)
	(visible waypoint5 waypoint18)
	(visible waypoint18 waypoint5)
	(visible waypoint5 waypoint31)
	(visible waypoint31 waypoint5)
	(visible waypoint5 waypoint34)
	(visible waypoint34 waypoint5)
	(visible waypoint6 waypoint5)
	(visible waypoint5 waypoint6)
	(visible waypoint6 waypoint10)
	(visible waypoint10 waypoint6)
	(visible waypoint6 waypoint36)
	(visible waypoint36 waypoint6)
	(visible waypoint6 waypoint40)
	(visible waypoint40 waypoint6)
	(visible waypoint7 waypoint12)
	(visible waypoint12 waypoint7)
	(visible waypoint7 waypoint13)
	(visible waypoint13 waypoint7)
	(visible waypoint7 waypoint25)
	(visible waypoint25 waypoint7)
	(visible waypoint7 waypoint35)
	(visible waypoint35 waypoint7)
	(visible waypoint8 waypoint1)
	(visible waypoint1 waypoint8)
	(visible waypoint8 waypoint20)
	(visible waypoint20 waypoint8)
	(visible waypoint8 waypoint42)
	(visible waypoint42 waypoint8)
	(visible waypoint9 waypoint14)
	(visible waypoint14 waypoint9)
	(visible waypoint9 waypoint17)
	(visible waypoint17 waypoint9)
	(visible waypoint9 waypoint31)
	(visible waypoint31 waypoint9)
	(visible waypoint9 waypoint33)
	(visible waypoint33 waypoint9)
	(visible waypoint9 waypoint47)
	(visible waypoint47 waypoint9)
	(visible waypoint10 waypoint20)
	(visible waypoint20 waypoint10)
	(visible waypoint11 waypoint1)
	(visible waypoint1 waypoint11)
	(visible waypoint11 waypoint5)
	(visible waypoint5 waypoint11)
	(visible waypoint11 waypoint9)
	(visible waypoint9 waypoint11)
	(visible waypoint11 waypoint13)
	(visible waypoint13 waypoint11)
	(visible waypoint11 waypoint45)
	(visible waypoint45 waypoint11)
	(visible waypoint11 waypoint48)
	(visible waypoint48 waypoint11)
	(visible waypoint12 waypoint16)
	(visible waypoint16 waypoint12)
	(visible waypoint12 waypoint19)
	(visible waypoint19 waypoint12)
	(visible waypoint12 waypoint22)
	(visible waypoint22 waypoint12)
	(visible waypoint12 waypoint35)
	(visible waypoint35 waypoint12)
	(visible waypoint12 waypoint36)
	(visible waypoint36 waypoint12)
	(visible waypoint12 waypoint43)
	(visible waypoint43 waypoint12)
	(visible waypoint13 waypoint4)
	(visible waypoint4 waypoint13)
	(visible waypoint13 waypoint26)
	(visible waypoint26 waypoint13)
	(visible waypoint13 waypoint30)
	(visible waypoint30 waypoint13)
	(visible waypoint13 waypoint47)
	(visible waypoint47 waypoint13)
	(visible waypoint14 waypoint13)
	(visible waypoint13 waypoint14)
	(visible waypoint14 waypoint31)
	(visible waypoint31 waypoint14)
	(visible waypoint14 waypoint35)
	(visible waypoint35 waypoint14)
	(visible waypoint14 waypoint36)
	(visible waypoint36 waypoint14)
	(visible waypoint14 waypoint49)
	(visible waypoint49 waypoint14)
	(visible waypoint15 waypoint10)
	(visible waypoint10 waypoint15)
	(visible waypoint15 waypoint32)
	(visible waypoint32 waypoint15)
	(visible waypoint15 waypoint47)
	(visible waypoint47 waypoint15)
	(visible waypoint16 waypoint21)
	(visible waypoint21 waypoint16)
	(visible waypoint16 waypoint28)
	(visible waypoint28 waypoint16)
	(visible waypoint16 waypoint35)
	(visible waypoint35 waypoint16)
	(visible waypoint16 waypoint42)
	(visible waypoint42 waypoint16)
	(visible waypoint16 waypoint47)
	(visible waypoint47 waypoint16)
	(visible waypoint16 waypoint49)
	(visible waypoint49 waypoint16)
	(visible waypoint17 waypoint38)
	(visible waypoint38 waypoint17)
	(visible waypoint17 waypoint44)
	(visible waypoint44 waypoint17)
	(visible waypoint17 waypoint49)
	(visible waypoint49 waypoint17)
	(visible waypoint18 waypoint20)
	(visible waypoint20 waypoint18)
	(visible waypoint18 waypoint22)
	(visible waypoint22 waypoint18)
	(visible waypoint18 waypoint26)
	(visible waypoint26 waypoint18)
	(visible waypoint18 waypoint32)
	(visible waypoint32 waypoint18)
	(visible waypoint18 waypoint37)
	(visible waypoint37 waypoint18)
	(visible waypoint19 waypoint1)
	(visible waypoint1 waypoint19)
	(visible waypoint19 waypoint6)
	(visible waypoint6 waypoint19)
	(visible waypoint19 waypoint10)
	(visible waypoint10 waypoint19)
	(visible waypoint19 waypoint18)
	(visible waypoint18 waypoint19)
	(visible waypoint19 waypoint24)
	(visible waypoint24 waypoint19)
	(visible waypoint19 waypoint27)
	(visible waypoint27 waypoint19)
	(visible waypoint19 waypoint29)
	(visible waypoint29 waypoint19)
	(visible waypoint20 waypoint4)
	(visible waypoint4 waypoint20)
	(visible waypoint20 waypoint27)
	(visible waypoint27 waypoint20)
	(visible waypoint21 waypoint17)
	(visible waypoint17 waypoint21)
	(visible waypoint21 waypoint23)
	(visible waypoint23 waypoint21)
	(visible waypoint21 waypoint26)
	(visible waypoint26 waypoint21)
	(visible waypoint21 waypoint35)
	(visible waypoint35 waypoint21)
	(visible waypoint22 waypoint11)
	(visible waypoint11 waypoint22)
	(visible waypoint22 waypoint14)
	(visible waypoint14 waypoint22)
	(visible waypoint22 waypoint23)
	(visible waypoint23 waypoint22)
	(visible waypoint22 waypoint37)
	(visible waypoint37 waypoint22)
	(visible waypoint22 waypoint44)
	(visible waypoint44 waypoint22)
	(visible waypoint23 waypoint2)
	(visible waypoint2 waypoint23)
	(visible waypoint23 waypoint4)
	(visible waypoint4 waypoint23)
	(visible waypoint23 waypoint17)
	(visible waypoint17 waypoint23)
	(visible waypoint23 waypoint33)
	(visible waypoint33 waypoint23)
	(visible waypoint23 waypoint46)
	(visible waypoint46 waypoint23)
	(visible waypoint24 waypoint34)
	(visible waypoint34 waypoint24)
	(visible waypoint24 waypoint41)
	(visible waypoint41 waypoint24)
	(visible waypoint25 waypoint14)
	(visible waypoint14 waypoint25)
	(visible waypoint25 waypoint16)
	(visible waypoint16 waypoint25)
	(visible waypoint25 waypoint19)
	(visible waypoint19 waypoint25)
	(visible waypoint25 waypoint41)
	(visible waypoint41 waypoint25)
	(visible waypoint25 waypoint44)
	(visible waypoint44 waypoint25)
	(visible waypoint25 waypoint45)
	(visible waypoint45 waypoint25)
	(visible waypoint25 waypoint48)
	(visible waypoint48 waypoint25)
	(visible waypoint26 waypoint3)
	(visible waypoint3 waypoint26)
	(visible waypoint26 waypoint8)
	(visible waypoint8 waypoint26)
	(visible waypoint26 waypoint28)
	(visible waypoint28 waypoint26)
	(visible waypoint26 waypoint37)
	(visible waypoint37 waypoint26)
	(visible waypoint26 waypoint40)
	(visible waypoint40 waypoint26)
	(visible waypoint26 waypoint45)
	(visible waypoint45 waypoint26)
	(visible waypoint27 waypoint3)
	(visible waypoint3 waypoint27)
	(visible waypoint27 waypoint39)
	(visible waypoint39 waypoint27)
	(visible waypoint27 waypoint44)
	(visible waypoint44 waypoint27)
	(visible waypoint28 waypoint1)
	(visible waypoint1 waypoint28)
	(visible waypoint28 waypoint11)
	(visible waypoint11 waypoint28)
	(visible waypoint28 waypoint27)
	(visible waypoint27 waypoint28)
	(visible waypoint28 waypoint29)
	(visible waypoint29 waypoint28)
	(visible waypoint28 waypoint34)
	(visible waypoint34 waypoint28)
	(visible waypoint28 waypoint35)
	(visible waypoint35 waypoint28)
	(visible waypoint28 waypoint42)
	(visible waypoint42 waypoint28)
	(visible waypoint29 waypoint10)
	(visible waypoint10 waypoint29)
	(visible waypoint29 waypoint14)
	(visible waypoint14 waypoint29)
	(visible waypoint29 waypoint45)
	(visible waypoint45 waypoint29)
	(visible waypoint30 waypoint15)
	(visible waypoint15 waypoint30)
	(visible waypoint30 waypoint27)
	(visible waypoint27 waypoint30)
	(visible waypoint30 waypoint37)
	(visible waypoint37 waypoint30)
	(visible waypoint30 waypoint42)
	(visible waypoint42 waypoint30)
	(visible waypoint31 waypoint44)
	(visible waypoint44 waypoint31)
	(visible waypoint32 waypoint4)
	(visible waypoint4 waypoint32)
	(visible waypoint32 waypoint6)
	(visible waypoint6 waypoint32)
	(visible waypoint32 waypoint20)
	(visible waypoint20 waypoint32)
	(visible waypoint32 waypoint33)
	(visible waypoint33 waypoint32)
	(visible waypoint32 waypoint43)
	(visible waypoint43 waypoint32)
	(visible waypoint33 waypoint8)
	(visible waypoint8 waypoint33)
	(visible waypoint33 waypoint34)
	(visible waypoint34 waypoint33)
	(visible waypoint33 waypoint41)
	(visible waypoint41 waypoint33)
	(visible waypoint33 waypoint42)
	(visible waypoint42 waypoint33)
	(visible waypoint33 waypoint45)
	(visible waypoint45 waypoint33)
	(visible waypoint33 waypoint49)
	(visible waypoint49 waypoint33)
	(visible waypoint34 waypoint11)
	(visible waypoint11 waypoint34)
	(visible waypoint34 waypoint21)
	(visible waypoint21 waypoint34)
	(visible waypoint34 waypoint29)
	(visible waypoint29 waypoint34)
	(visible waypoint34 waypoint44)
	(visible waypoint44 waypoint34)
	(visible waypoint34 waypoint47)
	(visible waypoint47 waypoint34)
	(visible waypoint34 waypoint48)
	(visible waypoint48 waypoint34)
	(visible waypoint34 waypoint49)
	(visible waypoint49 waypoint34)
	(visible waypoint35 waypoint8)
	(visible waypoint8 waypoint35)
	(visible waypoint35 waypoint10)
	(visible waypoint10 waypoint35)
	(visible waypoint35 waypoint19)
	(visible waypoint19 waypoint35)
	(visible waypoint35 waypoint20)
	(visible waypoint20 waypoint35)
	(visible waypoint35 waypoint31)
	(visible waypoint31 waypoint35)
	(visible waypoint35 waypoint44)
	(visible waypoint44 waypoint35)
	(visible waypoint36 waypoint19)
	(visible waypoint19 waypoint36)
	(visible waypoint36 waypoint28)
	(visible waypoint28 waypoint36)
	(visible waypoint37 waypoint10)
	(visible waypoint10 waypoint37)
	(visible waypoint37 waypoint17)
	(visible waypoint17 waypoint37)
	(visible waypoint37 waypoint47)
	(visible waypoint47 waypoint37)
	(visible waypoint38 waypoint31)
	(visible waypoint31 waypoint38)
	(visible waypoint38 waypoint33)
	(visible waypoint33 waypoint38)
	(visible waypoint38 waypoint41)
	(visible waypoint41 waypoint38)
	(visible waypoint38 waypoint42)
	(visible waypoint42 waypoint38)
	(visible waypoint38 waypoint44)
	(visible waypoint44 waypoint38)
	(visible waypoint39 waypoint1)
	(visible waypoint1 waypoint39)
	(visible waypoint39 waypoint6)
	(visible waypoint6 waypoint39)
	(visible waypoint39 waypoint12)
	(visible waypoint12 waypoint39)
	(visible waypoint39 waypoint45)
	(visible waypoint45 waypoint39)
	(visible waypoint39 waypoint46)
	(visible waypoint46 waypoint39)
	(visible waypoint40 waypoint12)
	(visible waypoint12 waypoint40)
	(visible waypoint41 waypoint1)
	(visible waypoint1 waypoint41)
	(visible waypoint41 waypoint7)
	(visible waypoint7 waypoint41)
	(visible waypoint41 waypoint11)
	(visible waypoint11 waypoint41)
	(visible waypoint41 waypoint14)
	(visible waypoint14 waypoint41)
	(visible waypoint42 waypoint0)
	(visible waypoint0 waypoint42)
	(visible waypoint42 waypoint7)
	(visible waypoint7 waypoint42)
	(visible waypoint42 waypoint10)
	(visible waypoint10 waypoint42)
	(visible waypoint42 waypoint12)
	(visible waypoint12 waypoint42)
	(visible waypoint42 waypoint18)
	(visible waypoint18 waypoint42)
	(visible waypoint42 waypoint34)
	(visible waypoint34 waypoint42)
	(visible waypoint42 waypoint39)
	(visible waypoint39 waypoint42)
	(visible waypoint42 waypoint44)
	(visible waypoint44 waypoint42)
	(visible waypoint43 waypoint0)
	(visible waypoint0 waypoint43)
	(visible waypoint43 waypoint2)
	(visible waypoint2 waypoint43)
	(visible waypoint43 waypoint3)
	(visible waypoint3 waypoint43)
	(visible waypoint43 waypoint11)
	(visible waypoint11 waypoint43)
	(visible waypoint43 waypoint18)
	(visible waypoint18 waypoint43)
	(visible waypoint43 waypoint21)
	(visible waypoint21 waypoint43)
	(visible waypoint43 waypoint24)
	(visible waypoint24 waypoint43)
	(visible waypoint43 waypoint31)
	(visible waypoint31 waypoint43)
	(visible waypoint43 waypoint33)
	(visible waypoint33 waypoint43)
	(visible waypoint43 waypoint37)
	(visible waypoint37 waypoint43)
	(visible waypoint43 waypoint39)
	(visible waypoint39 waypoint43)
	(visible waypoint43 waypoint41)
	(visible waypoint41 waypoint43)
	(visible waypoint44 waypoint11)
	(visible waypoint11 waypoint44)
	(visible waypoint44 waypoint15)
	(visible waypoint15 waypoint44)
	(visible waypoint44 waypoint33)
	(visible waypoint33 waypoint44)
	(visible waypoint44 waypoint48)
	(visible waypoint48 waypoint44)
	(visible waypoint45 waypoint1)
	(visible waypoint1 waypoint45)
	(visible waypoint45 waypoint7)
	(visible waypoint7 waypoint45)
	(visible waypoint45 waypoint27)
	(visible waypoint27 waypoint45)
	(visible waypoint45 waypoint36)
	(visible waypoint36 waypoint45)
	(visible waypoint45 waypoint37)
	(visible waypoint37 waypoint45)
	(visible waypoint45 waypoint38)
	(visible waypoint38 waypoint45)
	(visible waypoint46 waypoint21)
	(visible waypoint21 waypoint46)
	(visible waypoint47 waypoint3)
	(visible waypoint3 waypoint47)
	(visible waypoint47 waypoint14)
	(visible waypoint14 waypoint47)
	(visible waypoint47 waypoint26)
	(visible waypoint26 waypoint47)
	(visible waypoint48 waypoint13)
	(visible waypoint13 waypoint48)
	(visible waypoint49 waypoint6)
	(visible waypoint6 waypoint49)
	(visible waypoint49 waypoint7)
	(visible waypoint7 waypoint49)
	(visible waypoint49 waypoint24)
	(visible waypoint24 waypoint49)
	(visible waypoint49 waypoint27)
	(visible waypoint27 waypoint49)
	(visible waypoint49 waypoint48)
	(visible waypoint48 waypoint49)
	(at_soil_sample waypoint0)
	(at_rock_sample waypoint0)
	(at_rock_sample waypoint2)
	(at_soil_sample waypoint4)
	(at_rock_sample waypoint4)
	(at_soil_sample waypoint5)
	(at_soil_sample waypoint6)
	(at_rock_sample waypoint6)
	(at_rock_sample waypoint7)
	(at_rock_sample waypoint11)
	(at_rock_sample waypoint12)
	(at_soil_sample waypoint13)
	(at_rock_sample waypoint13)
	(at_rock_sample waypoint14)
	(at_soil_sample waypoint16)
	(at_soil_sample waypoint17)
	(at_rock_sample waypoint17)
	(at_soil_sample waypoint18)
	(at_rock_sample waypoint18)
	(at_soil_sample waypoint20)
	(at_rock_sample waypoint20)
	(at_soil_sample waypoint21)
	(at_rock_sample waypoint21)
	(at_rock_sample waypoint22)
	(at_rock_sample waypoint23)
	(at_soil_sample waypoint24)
	(at_rock_sample waypoint24)
	(at_soil_sample waypoint25)
	(at_rock_sample waypoint25)
	(at_rock_sample waypoint26)
	(at_soil_sample waypoint28)
	(at_rock_sample waypoint28)
	(at_rock_sample waypoint31)
	(at_soil_sample waypoint33)
	(at_rock_sample waypoint37)
	(at_rock_sample waypoint38)
	(at_rock_sample waypoint39)
	(at_rock_sample waypoint40)
	(at_soil_sample waypoint42)
	(at_rock_sample waypoint42)
	(at_rock_sample waypoint45)
	(at_soil_sample waypoint48)
	(at_rock_sample waypoint48)
	(at_soil_sample waypoint49)
	(at_rock_sample waypoint49)
	(at_lander general waypoint35)
	(channel_free general)
	(at rover0 waypoint35)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint35 waypoint7)
	(can_traverse rover0 waypoint7 waypoint35)
	(can_traverse rover0 waypoint35 waypoint8)
	(can_traverse rover0 waypoint8 waypoint35)
	(can_traverse rover0 waypoint35 waypoint12)
	(can_traverse rover0 waypoint12 waypoint35)
	(can_traverse rover0 waypoint35 waypoint14)
	(can_traverse rover0 waypoint14 waypoint35)
	(can_traverse rover0 waypoint35 waypoint19)
	(can_traverse rover0 waypoint19 waypoint35)
	(can_traverse rover0 waypoint35 waypoint21)
	(can_traverse rover0 waypoint21 waypoint35)
	(can_traverse rover0 waypoint35 waypoint28)
	(can_traverse rover0 waypoint28 waypoint35)
	(can_traverse rover0 waypoint35 waypoint44)
	(can_traverse rover0 waypoint44 waypoint35)
	(can_traverse rover0 waypoint7 waypoint13)
	(can_traverse rover0 waypoint13 waypoint7)
	(can_traverse rover0 waypoint7 waypoint25)
	(can_traverse rover0 waypoint25 waypoint7)
	(can_traverse rover0 waypoint7 waypoint41)
	(can_traverse rover0 waypoint41 waypoint7)
	(can_traverse rover0 waypoint7 waypoint42)
	(can_traverse rover0 waypoint42 waypoint7)
	(can_traverse rover0 waypoint8 waypoint1)
	(can_traverse rover0 waypoint1 waypoint8)
	(can_traverse rover0 waypoint8 waypoint26)
	(can_traverse rover0 waypoint26 waypoint8)
	(can_traverse rover0 waypoint12 waypoint4)
	(can_traverse rover0 waypoint4 waypoint12)
	(can_traverse rover0 waypoint12 waypoint16)
	(can_traverse rover0 waypoint16 waypoint12)
	(can_traverse rover0 waypoint12 waypoint22)
	(can_traverse rover0 waypoint22 waypoint12)
	(can_traverse rover0 waypoint12 waypoint39)
	(can_traverse rover0 waypoint39 waypoint12)
	(can_traverse rover0 waypoint12 waypoint43)
	(can_traverse rover0 waypoint43 waypoint12)
	(can_traverse rover0 waypoint14 waypoint0)
	(can_traverse rover0 waypoint0 waypoint14)
	(can_traverse rover0 waypoint14 waypoint9)
	(can_traverse rover0 waypoint9 waypoint14)
	(can_traverse rover0 waypoint14 waypoint29)
	(can_traverse rover0 waypoint29 waypoint14)
	(can_traverse rover0 waypoint14 waypoint49)
	(can_traverse rover0 waypoint49 waypoint14)
	(can_traverse rover0 waypoint19 waypoint6)
	(can_traverse rover0 waypoint6 waypoint19)
	(can_traverse rover0 waypoint19 waypoint10)
	(can_traverse rover0 waypoint10 waypoint19)
	(can_traverse rover0 waypoint19 waypoint24)
	(can_traverse rover0 waypoint24 waypoint19)
	(can_traverse rover0 waypoint19 waypoint27)
	(can_traverse rover0 waypoint27 waypoint19)
	(can_traverse rover0 waypoint21 waypoint2)
	(can_traverse rover0 waypoint2 waypoint21)
	(can_traverse rover0 waypoint21 waypoint23)
	(can_traverse rover0 waypoint23 waypoint21)
	(can_traverse rover0 waypoint21 waypoint34)
	(can_traverse rover0 waypoint34 waypoint21)
	(can_traverse rover0 waypoint21 waypoint46)
	(can_traverse rover0 waypoint46 waypoint21)
	(can_traverse rover0 waypoint28 waypoint11)
	(can_traverse rover0 waypoint11 waypoint28)
	(can_traverse rover0 waypoint28 waypoint36)
	(can_traverse rover0 waypoint36 waypoint28)
	(can_traverse rover0 waypoint44 waypoint15)
	(can_traverse rover0 waypoint15 waypoint44)
	(can_traverse rover0 waypoint44 waypoint17)
	(can_traverse rover0 waypoint17 waypoint44)
	(can_traverse rover0 waypoint44 waypoint31)
	(can_traverse rover0 waypoint31 waypoint44)
	(can_traverse rover0 waypoint44 waypoint33)
	(can_traverse rover0 waypoint33 waypoint44)
	(can_traverse rover0 waypoint44 waypoint38)
	(can_traverse rover0 waypoint38 waypoint44)
	(can_traverse rover0 waypoint13 waypoint30)
	(can_traverse rover0 waypoint30 waypoint13)
	(can_traverse rover0 waypoint13 waypoint47)
	(can_traverse rover0 waypoint47 waypoint13)
	(can_traverse rover0 waypoint13 waypoint48)
	(can_traverse rover0 waypoint48 waypoint13)
	(can_traverse rover0 waypoint25 waypoint45)
	(can_traverse rover0 waypoint45 waypoint25)
	(can_traverse rover0 waypoint26 waypoint3)
	(can_traverse rover0 waypoint3 waypoint26)
	(can_traverse rover0 waypoint26 waypoint37)
	(can_traverse rover0 waypoint37 waypoint26)
	(can_traverse rover0 waypoint26 waypoint40)
	(can_traverse rover0 waypoint40 waypoint26)
	(can_traverse rover0 waypoint4 waypoint32)
	(can_traverse rover0 waypoint32 waypoint4)
	(can_traverse rover0 waypoint43 waypoint18)
	(can_traverse rover0 waypoint18 waypoint43)
	(can_traverse rover0 waypoint6 waypoint5)
	(can_traverse rover0 waypoint5 waypoint6)
	(can_traverse rover0 waypoint10 waypoint20)
	(can_traverse rover0 waypoint20 waypoint10)
	(at rover1 waypoint29)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_rock_analysis rover1)
	(equipped_for_imaging rover1)
	(can_traverse rover1 waypoint29 waypoint10)
	(can_traverse rover1 waypoint10 waypoint29)
	(can_traverse rover1 waypoint29 waypoint19)
	(can_traverse rover1 waypoint19 waypoint29)
	(can_traverse rover1 waypoint29 waypoint28)
	(can_traverse rover1 waypoint28 waypoint29)
	(can_traverse rover1 waypoint29 waypoint34)
	(can_traverse rover1 waypoint34 waypoint29)
	(can_traverse rover1 waypoint10 waypoint2)
	(can_traverse rover1 waypoint2 waypoint10)
	(can_traverse rover1 waypoint10 waypoint6)
	(can_traverse rover1 waypoint6 waypoint10)
	(can_traverse rover1 waypoint10 waypoint15)
	(can_traverse rover1 waypoint15 waypoint10)
	(can_traverse rover1 waypoint10 waypoint20)
	(can_traverse rover1 waypoint20 waypoint10)
	(can_traverse rover1 waypoint10 waypoint35)
	(can_traverse rover1 waypoint35 waypoint10)
	(can_traverse rover1 waypoint10 waypoint37)
	(can_traverse rover1 waypoint37 waypoint10)
	(can_traverse rover1 waypoint19 waypoint1)
	(can_traverse rover1 waypoint1 waypoint19)
	(can_traverse rover1 waypoint19 waypoint12)
	(can_traverse rover1 waypoint12 waypoint19)
	(can_traverse rover1 waypoint19 waypoint18)
	(can_traverse rover1 waypoint18 waypoint19)
	(can_traverse rover1 waypoint19 waypoint25)
	(can_traverse rover1 waypoint25 waypoint19)
	(can_traverse rover1 waypoint19 waypoint27)
	(can_traverse rover1 waypoint27 waypoint19)
	(can_traverse rover1 waypoint19 waypoint36)
	(can_traverse rover1 waypoint36 waypoint19)
	(can_traverse rover1 waypoint28 waypoint11)
	(can_traverse rover1 waypoint11 waypoint28)
	(can_traverse rover1 waypoint28 waypoint16)
	(can_traverse rover1 waypoint16 waypoint28)
	(can_traverse rover1 waypoint28 waypoint26)
	(can_traverse rover1 waypoint26 waypoint28)
	(can_traverse rover1 waypoint28 waypoint42)
	(can_traverse rover1 waypoint42 waypoint28)
	(can_traverse rover1 waypoint34 waypoint0)
	(can_traverse rover1 waypoint0 waypoint34)
	(can_traverse rover1 waypoint34 waypoint24)
	(can_traverse rover1 waypoint24 waypoint34)
	(can_traverse rover1 waypoint34 waypoint33)
	(can_traverse rover1 waypoint33 waypoint34)
	(can_traverse rover1 waypoint34 waypoint44)
	(can_traverse rover1 waypoint44 waypoint34)
	(can_traverse rover1 waypoint34 waypoint49)
	(can_traverse rover1 waypoint49 waypoint34)
	(can_traverse rover1 waypoint2 waypoint8)
	(can_traverse rover1 waypoint8 waypoint2)
	(can_traverse rover1 waypoint2 waypoint13)
	(can_traverse rover1 waypoint13 waypoint2)
	(can_traverse rover1 waypoint2 waypoint21)
	(can_traverse rover1 waypoint21 waypoint2)
	(can_traverse rover1 waypoint2 waypoint23)
	(can_traverse rover1 waypoint23 waypoint2)
	(can_traverse rover1 waypoint6 waypoint5)
	(can_traverse rover1 waypoint5 waypoint6)
	(can_traverse rover1 waypoint6 waypoint32)
	(can_traverse rover1 waypoint32 waypoint6)
	(can_traverse rover1 waypoint6 waypoint39)
	(can_traverse rover1 waypoint39 waypoint6)
	(can_traverse rover1 waypoint6 waypoint40)
	(can_traverse rover1 waypoint40 waypoint6)
	(can_traverse rover1 waypoint20 waypoint4)
	(can_traverse rover1 waypoint4 waypoint20)
	(can_traverse rover1 waypoint35 waypoint7)
	(can_traverse rover1 waypoint7 waypoint35)
	(can_traverse rover1 waypoint37 waypoint17)
	(can_traverse rover1 waypoint17 waypoint37)
	(can_traverse rover1 waypoint37 waypoint22)
	(can_traverse rover1 waypoint22 waypoint37)
	(can_traverse rover1 waypoint37 waypoint45)
	(can_traverse rover1 waypoint45 waypoint37)
	(can_traverse rover1 waypoint37 waypoint47)
	(can_traverse rover1 waypoint47 waypoint37)
	(can_traverse rover1 waypoint1 waypoint48)
	(can_traverse rover1 waypoint48 waypoint1)
	(can_traverse rover1 waypoint18 waypoint43)
	(can_traverse rover1 waypoint43 waypoint18)
	(can_traverse rover1 waypoint25 waypoint41)
	(can_traverse rover1 waypoint41 waypoint25)
	(can_traverse rover1 waypoint27 waypoint3)
	(can_traverse rover1 waypoint3 waypoint27)
	(can_traverse rover1 waypoint27 waypoint30)
	(can_traverse rover1 waypoint30 waypoint27)
	(can_traverse rover1 waypoint33 waypoint9)
	(can_traverse rover1 waypoint9 waypoint33)
	(can_traverse rover1 waypoint33 waypoint38)
	(can_traverse rover1 waypoint38 waypoint33)
	(can_traverse rover1 waypoint44 waypoint31)
	(can_traverse rover1 waypoint31 waypoint44)
	(can_traverse rover1 waypoint49 waypoint14)
	(can_traverse rover1 waypoint14 waypoint49)
	(can_traverse rover1 waypoint21 waypoint46)
	(can_traverse rover1 waypoint46 waypoint21)
	(at rover2 waypoint42)
	(available rover2)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_soil_analysis rover2)
	(equipped_for_imaging rover2)
	(can_traverse rover2 waypoint42 waypoint0)
	(can_traverse rover2 waypoint0 waypoint42)
	(can_traverse rover2 waypoint42 waypoint8)
	(can_traverse rover2 waypoint8 waypoint42)
	(can_traverse rover2 waypoint42 waypoint10)
	(can_traverse rover2 waypoint10 waypoint42)
	(can_traverse rover2 waypoint42 waypoint16)
	(can_traverse rover2 waypoint16 waypoint42)
	(can_traverse rover2 waypoint42 waypoint18)
	(can_traverse rover2 waypoint18 waypoint42)
	(can_traverse rover2 waypoint42 waypoint28)
	(can_traverse rover2 waypoint28 waypoint42)
	(can_traverse rover2 waypoint42 waypoint30)
	(can_traverse rover2 waypoint30 waypoint42)
	(can_traverse rover2 waypoint42 waypoint33)
	(can_traverse rover2 waypoint33 waypoint42)
	(can_traverse rover2 waypoint42 waypoint34)
	(can_traverse rover2 waypoint34 waypoint42)
	(can_traverse rover2 waypoint42 waypoint38)
	(can_traverse rover2 waypoint38 waypoint42)
	(can_traverse rover2 waypoint42 waypoint39)
	(can_traverse rover2 waypoint39 waypoint42)
	(can_traverse rover2 waypoint42 waypoint44)
	(can_traverse rover2 waypoint44 waypoint42)
	(can_traverse rover2 waypoint0 waypoint3)
	(can_traverse rover2 waypoint3 waypoint0)
	(can_traverse rover2 waypoint0 waypoint14)
	(can_traverse rover2 waypoint14 waypoint0)
	(can_traverse rover2 waypoint0 waypoint31)
	(can_traverse rover2 waypoint31 waypoint0)
	(can_traverse rover2 waypoint0 waypoint32)
	(can_traverse rover2 waypoint32 waypoint0)
	(can_traverse rover2 waypoint0 waypoint49)
	(can_traverse rover2 waypoint49 waypoint0)
	(can_traverse rover2 waypoint8 waypoint1)
	(can_traverse rover2 waypoint1 waypoint8)
	(can_traverse rover2 waypoint8 waypoint2)
	(can_traverse rover2 waypoint2 waypoint8)
	(can_traverse rover2 waypoint8 waypoint20)
	(can_traverse rover2 waypoint20 waypoint8)
	(can_traverse rover2 waypoint8 waypoint26)
	(can_traverse rover2 waypoint26 waypoint8)
	(can_traverse rover2 waypoint8 waypoint35)
	(can_traverse rover2 waypoint35 waypoint8)
	(can_traverse rover2 waypoint10 waypoint6)
	(can_traverse rover2 waypoint6 waypoint10)
	(can_traverse rover2 waypoint10 waypoint15)
	(can_traverse rover2 waypoint15 waypoint10)
	(can_traverse rover2 waypoint10 waypoint19)
	(can_traverse rover2 waypoint19 waypoint10)
	(can_traverse rover2 waypoint10 waypoint29)
	(can_traverse rover2 waypoint29 waypoint10)
	(can_traverse rover2 waypoint10 waypoint37)
	(can_traverse rover2 waypoint37 waypoint10)
	(can_traverse rover2 waypoint16 waypoint12)
	(can_traverse rover2 waypoint12 waypoint16)
	(can_traverse rover2 waypoint16 waypoint21)
	(can_traverse rover2 waypoint21 waypoint16)
	(can_traverse rover2 waypoint18 waypoint22)
	(can_traverse rover2 waypoint22 waypoint18)
	(can_traverse rover2 waypoint18 waypoint43)
	(can_traverse rover2 waypoint43 waypoint18)
	(can_traverse rover2 waypoint28 waypoint11)
	(can_traverse rover2 waypoint11 waypoint28)
	(can_traverse rover2 waypoint28 waypoint27)
	(can_traverse rover2 waypoint27 waypoint28)
	(can_traverse rover2 waypoint28 waypoint36)
	(can_traverse rover2 waypoint36 waypoint28)
	(can_traverse rover2 waypoint30 waypoint13)
	(can_traverse rover2 waypoint13 waypoint30)
	(can_traverse rover2 waypoint33 waypoint9)
	(can_traverse rover2 waypoint9 waypoint33)
	(can_traverse rover2 waypoint34 waypoint5)
	(can_traverse rover2 waypoint5 waypoint34)
	(can_traverse rover2 waypoint34 waypoint47)
	(can_traverse rover2 waypoint47 waypoint34)
	(can_traverse rover2 waypoint34 waypoint48)
	(can_traverse rover2 waypoint48 waypoint34)
	(can_traverse rover2 waypoint39 waypoint45)
	(can_traverse rover2 waypoint45 waypoint39)
	(can_traverse rover2 waypoint39 waypoint46)
	(can_traverse rover2 waypoint46 waypoint39)
	(can_traverse rover2 waypoint44 waypoint17)
	(can_traverse rover2 waypoint17 waypoint44)
	(can_traverse rover2 waypoint44 waypoint25)
	(can_traverse rover2 waypoint25 waypoint44)
	(can_traverse rover2 waypoint3 waypoint40)
	(can_traverse rover2 waypoint40 waypoint3)
	(can_traverse rover2 waypoint14 waypoint41)
	(can_traverse rover2 waypoint41 waypoint14)
	(can_traverse rover2 waypoint31 waypoint4)
	(can_traverse rover2 waypoint4 waypoint31)
	(can_traverse rover2 waypoint2 waypoint23)
	(can_traverse rover2 waypoint23 waypoint2)
	(can_traverse rover2 waypoint19 waypoint24)
	(can_traverse rover2 waypoint24 waypoint19)
	(can_traverse rover2 waypoint12 waypoint7)
	(can_traverse rover2 waypoint7 waypoint12)
	(at rover3 waypoint3)
	(available rover3)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_soil_analysis rover3)
	(equipped_for_imaging rover3)
	(can_traverse rover3 waypoint3 waypoint0)
	(can_traverse rover3 waypoint0 waypoint3)
	(can_traverse rover3 waypoint3 waypoint20)
	(can_traverse rover3 waypoint20 waypoint3)
	(can_traverse rover3 waypoint3 waypoint26)
	(can_traverse rover3 waypoint26 waypoint3)
	(can_traverse rover3 waypoint3 waypoint27)
	(can_traverse rover3 waypoint27 waypoint3)
	(can_traverse rover3 waypoint3 waypoint40)
	(can_traverse rover3 waypoint40 waypoint3)
	(can_traverse rover3 waypoint3 waypoint43)
	(can_traverse rover3 waypoint43 waypoint3)
	(can_traverse rover3 waypoint3 waypoint47)
	(can_traverse rover3 waypoint47 waypoint3)
	(can_traverse rover3 waypoint0 waypoint5)
	(can_traverse rover3 waypoint5 waypoint0)
	(can_traverse rover3 waypoint0 waypoint14)
	(can_traverse rover3 waypoint14 waypoint0)
	(can_traverse rover3 waypoint0 waypoint31)
	(can_traverse rover3 waypoint31 waypoint0)
	(can_traverse rover3 waypoint0 waypoint34)
	(can_traverse rover3 waypoint34 waypoint0)
	(can_traverse rover3 waypoint0 waypoint42)
	(can_traverse rover3 waypoint42 waypoint0)
	(can_traverse rover3 waypoint0 waypoint49)
	(can_traverse rover3 waypoint49 waypoint0)
	(can_traverse rover3 waypoint20 waypoint2)
	(can_traverse rover3 waypoint2 waypoint20)
	(can_traverse rover3 waypoint20 waypoint4)
	(can_traverse rover3 waypoint4 waypoint20)
	(can_traverse rover3 waypoint20 waypoint10)
	(can_traverse rover3 waypoint10 waypoint20)
	(can_traverse rover3 waypoint20 waypoint35)
	(can_traverse rover3 waypoint35 waypoint20)
	(can_traverse rover3 waypoint26 waypoint8)
	(can_traverse rover3 waypoint8 waypoint26)
	(can_traverse rover3 waypoint26 waypoint13)
	(can_traverse rover3 waypoint13 waypoint26)
	(can_traverse rover3 waypoint26 waypoint18)
	(can_traverse rover3 waypoint18 waypoint26)
	(can_traverse rover3 waypoint26 waypoint21)
	(can_traverse rover3 waypoint21 waypoint26)
	(can_traverse rover3 waypoint26 waypoint28)
	(can_traverse rover3 waypoint28 waypoint26)
	(can_traverse rover3 waypoint26 waypoint37)
	(can_traverse rover3 waypoint37 waypoint26)
	(can_traverse rover3 waypoint26 waypoint45)
	(can_traverse rover3 waypoint45 waypoint26)
	(can_traverse rover3 waypoint27 waypoint30)
	(can_traverse rover3 waypoint30 waypoint27)
	(can_traverse rover3 waypoint27 waypoint39)
	(can_traverse rover3 waypoint39 waypoint27)
	(can_traverse rover3 waypoint40 waypoint6)
	(can_traverse rover3 waypoint6 waypoint40)
	(can_traverse rover3 waypoint40 waypoint12)
	(can_traverse rover3 waypoint12 waypoint40)
	(can_traverse rover3 waypoint43 waypoint11)
	(can_traverse rover3 waypoint11 waypoint43)
	(can_traverse rover3 waypoint43 waypoint24)
	(can_traverse rover3 waypoint24 waypoint43)
	(can_traverse rover3 waypoint43 waypoint32)
	(can_traverse rover3 waypoint32 waypoint43)
	(can_traverse rover3 waypoint43 waypoint33)
	(can_traverse rover3 waypoint33 waypoint43)
	(can_traverse rover3 waypoint43 waypoint41)
	(can_traverse rover3 waypoint41 waypoint43)
	(can_traverse rover3 waypoint47 waypoint9)
	(can_traverse rover3 waypoint9 waypoint47)
	(can_traverse rover3 waypoint47 waypoint15)
	(can_traverse rover3 waypoint15 waypoint47)
	(can_traverse rover3 waypoint47 waypoint16)
	(can_traverse rover3 waypoint16 waypoint47)
	(can_traverse rover3 waypoint14 waypoint22)
	(can_traverse rover3 waypoint22 waypoint14)
	(can_traverse rover3 waypoint14 waypoint36)
	(can_traverse rover3 waypoint36 waypoint14)
	(can_traverse rover3 waypoint31 waypoint38)
	(can_traverse rover3 waypoint38 waypoint31)
	(can_traverse rover3 waypoint31 waypoint44)
	(can_traverse rover3 waypoint44 waypoint31)
	(can_traverse rover3 waypoint34 waypoint29)
	(can_traverse rover3 waypoint29 waypoint34)
	(can_traverse rover3 waypoint34 waypoint48)
	(can_traverse rover3 waypoint48 waypoint34)
	(can_traverse rover3 waypoint42 waypoint7)
	(can_traverse rover3 waypoint7 waypoint42)
	(can_traverse rover3 waypoint10 waypoint19)
	(can_traverse rover3 waypoint19 waypoint10)
	(can_traverse rover3 waypoint8 waypoint1)
	(can_traverse rover3 waypoint1 waypoint8)
	(can_traverse rover3 waypoint21 waypoint17)
	(can_traverse rover3 waypoint17 waypoint21)
	(can_traverse rover3 waypoint39 waypoint46)
	(can_traverse rover3 waypoint46 waypoint39)
	(can_traverse rover3 waypoint33 waypoint23)
	(can_traverse rover3 waypoint23 waypoint33)
	(can_traverse rover3 waypoint41 waypoint25)
	(can_traverse rover3 waypoint25 waypoint41)
	(at rover4 waypoint29)
	(available rover4)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_soil_analysis rover4)
	(equipped_for_imaging rover4)
	(can_traverse rover4 waypoint29 waypoint10)
	(can_traverse rover4 waypoint10 waypoint29)
	(can_traverse rover4 waypoint29 waypoint14)
	(can_traverse rover4 waypoint14 waypoint29)
	(can_traverse rover4 waypoint29 waypoint19)
	(can_traverse rover4 waypoint19 waypoint29)
	(can_traverse rover4 waypoint29 waypoint45)
	(can_traverse rover4 waypoint45 waypoint29)
	(can_traverse rover4 waypoint10 waypoint6)
	(can_traverse rover4 waypoint6 waypoint10)
	(can_traverse rover4 waypoint10 waypoint15)
	(can_traverse rover4 waypoint15 waypoint10)
	(can_traverse rover4 waypoint10 waypoint20)
	(can_traverse rover4 waypoint20 waypoint10)
	(can_traverse rover4 waypoint10 waypoint35)
	(can_traverse rover4 waypoint35 waypoint10)
	(can_traverse rover4 waypoint10 waypoint42)
	(can_traverse rover4 waypoint42 waypoint10)
	(can_traverse rover4 waypoint14 waypoint0)
	(can_traverse rover4 waypoint0 waypoint14)
	(can_traverse rover4 waypoint14 waypoint9)
	(can_traverse rover4 waypoint9 waypoint14)
	(can_traverse rover4 waypoint14 waypoint13)
	(can_traverse rover4 waypoint13 waypoint14)
	(can_traverse rover4 waypoint14 waypoint22)
	(can_traverse rover4 waypoint22 waypoint14)
	(can_traverse rover4 waypoint14 waypoint25)
	(can_traverse rover4 waypoint25 waypoint14)
	(can_traverse rover4 waypoint14 waypoint36)
	(can_traverse rover4 waypoint36 waypoint14)
	(can_traverse rover4 waypoint14 waypoint41)
	(can_traverse rover4 waypoint41 waypoint14)
	(can_traverse rover4 waypoint14 waypoint47)
	(can_traverse rover4 waypoint47 waypoint14)
	(can_traverse rover4 waypoint14 waypoint49)
	(can_traverse rover4 waypoint49 waypoint14)
	(can_traverse rover4 waypoint19 waypoint24)
	(can_traverse rover4 waypoint24 waypoint19)
	(can_traverse rover4 waypoint19 waypoint27)
	(can_traverse rover4 waypoint27 waypoint19)
	(can_traverse rover4 waypoint45 waypoint11)
	(can_traverse rover4 waypoint11 waypoint45)
	(can_traverse rover4 waypoint45 waypoint26)
	(can_traverse rover4 waypoint26 waypoint45)
	(can_traverse rover4 waypoint45 waypoint37)
	(can_traverse rover4 waypoint37 waypoint45)
	(can_traverse rover4 waypoint45 waypoint38)
	(can_traverse rover4 waypoint38 waypoint45)
	(can_traverse rover4 waypoint6 waypoint32)
	(can_traverse rover4 waypoint32 waypoint6)
	(can_traverse rover4 waypoint6 waypoint39)
	(can_traverse rover4 waypoint39 waypoint6)
	(can_traverse rover4 waypoint6 waypoint40)
	(can_traverse rover4 waypoint40 waypoint6)
	(can_traverse rover4 waypoint15 waypoint30)
	(can_traverse rover4 waypoint30 waypoint15)
	(can_traverse rover4 waypoint15 waypoint44)
	(can_traverse rover4 waypoint44 waypoint15)
	(can_traverse rover4 waypoint20 waypoint2)
	(can_traverse rover4 waypoint2 waypoint20)
	(can_traverse rover4 waypoint20 waypoint4)
	(can_traverse rover4 waypoint4 waypoint20)
	(can_traverse rover4 waypoint20 waypoint8)
	(can_traverse rover4 waypoint8 waypoint20)
	(can_traverse rover4 waypoint35 waypoint12)
	(can_traverse rover4 waypoint12 waypoint35)
	(can_traverse rover4 waypoint35 waypoint16)
	(can_traverse rover4 waypoint16 waypoint35)
	(can_traverse rover4 waypoint35 waypoint28)
	(can_traverse rover4 waypoint28 waypoint35)
	(can_traverse rover4 waypoint35 waypoint31)
	(can_traverse rover4 waypoint31 waypoint35)
	(can_traverse rover4 waypoint42 waypoint18)
	(can_traverse rover4 waypoint18 waypoint42)
	(can_traverse rover4 waypoint0 waypoint34)
	(can_traverse rover4 waypoint34 waypoint0)
	(can_traverse rover4 waypoint0 waypoint43)
	(can_traverse rover4 waypoint43 waypoint0)
	(can_traverse rover4 waypoint9 waypoint17)
	(can_traverse rover4 waypoint17 waypoint9)
	(can_traverse rover4 waypoint9 waypoint33)
	(can_traverse rover4 waypoint33 waypoint9)
	(can_traverse rover4 waypoint13 waypoint7)
	(can_traverse rover4 waypoint7 waypoint13)
	(can_traverse rover4 waypoint22 waypoint23)
	(can_traverse rover4 waypoint23 waypoint22)
	(can_traverse rover4 waypoint25 waypoint1)
	(can_traverse rover4 waypoint1 waypoint25)
	(can_traverse rover4 waypoint25 waypoint48)
	(can_traverse rover4 waypoint48 waypoint25)
	(at rover5 waypoint1)
	(available rover5)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_rock_analysis rover5)
	(equipped_for_imaging rover5)
	(can_traverse rover5 waypoint1 waypoint4)
	(can_traverse rover5 waypoint4 waypoint1)
	(can_traverse rover5 waypoint1 waypoint11)
	(can_traverse rover5 waypoint11 waypoint1)
	(can_traverse rover5 waypoint1 waypoint15)
	(can_traverse rover5 waypoint15 waypoint1)
	(can_traverse rover5 waypoint1 waypoint21)
	(can_traverse rover5 waypoint21 waypoint1)
	(can_traverse rover5 waypoint1 waypoint25)
	(can_traverse rover5 waypoint25 waypoint1)
	(can_traverse rover5 waypoint1 waypoint39)
	(can_traverse rover5 waypoint39 waypoint1)
	(can_traverse rover5 waypoint1 waypoint41)
	(can_traverse rover5 waypoint41 waypoint1)
	(can_traverse rover5 waypoint1 waypoint45)
	(can_traverse rover5 waypoint45 waypoint1)
	(can_traverse rover5 waypoint1 waypoint48)
	(can_traverse rover5 waypoint48 waypoint1)
	(can_traverse rover5 waypoint4 waypoint31)
	(can_traverse rover5 waypoint31 waypoint4)
	(can_traverse rover5 waypoint4 waypoint47)
	(can_traverse rover5 waypoint47 waypoint4)
	(can_traverse rover5 waypoint11 waypoint5)
	(can_traverse rover5 waypoint5 waypoint11)
	(can_traverse rover5 waypoint11 waypoint13)
	(can_traverse rover5 waypoint13 waypoint11)
	(can_traverse rover5 waypoint11 waypoint34)
	(can_traverse rover5 waypoint34 waypoint11)
	(can_traverse rover5 waypoint15 waypoint10)
	(can_traverse rover5 waypoint10 waypoint15)
	(can_traverse rover5 waypoint15 waypoint30)
	(can_traverse rover5 waypoint30 waypoint15)
	(can_traverse rover5 waypoint15 waypoint32)
	(can_traverse rover5 waypoint32 waypoint15)
	(can_traverse rover5 waypoint15 waypoint44)
	(can_traverse rover5 waypoint44 waypoint15)
	(can_traverse rover5 waypoint21 waypoint16)
	(can_traverse rover5 waypoint16 waypoint21)
	(can_traverse rover5 waypoint21 waypoint17)
	(can_traverse rover5 waypoint17 waypoint21)
	(can_traverse rover5 waypoint21 waypoint23)
	(can_traverse rover5 waypoint23 waypoint21)
	(can_traverse rover5 waypoint21 waypoint26)
	(can_traverse rover5 waypoint26 waypoint21)
	(can_traverse rover5 waypoint21 waypoint43)
	(can_traverse rover5 waypoint43 waypoint21)
	(can_traverse rover5 waypoint21 waypoint46)
	(can_traverse rover5 waypoint46 waypoint21)
	(can_traverse rover5 waypoint25 waypoint7)
	(can_traverse rover5 waypoint7 waypoint25)
	(can_traverse rover5 waypoint25 waypoint14)
	(can_traverse rover5 waypoint14 waypoint25)
	(can_traverse rover5 waypoint25 waypoint19)
	(can_traverse rover5 waypoint19 waypoint25)
	(can_traverse rover5 waypoint39 waypoint6)
	(can_traverse rover5 waypoint6 waypoint39)
	(can_traverse rover5 waypoint39 waypoint12)
	(can_traverse rover5 waypoint12 waypoint39)
	(can_traverse rover5 waypoint41 waypoint24)
	(can_traverse rover5 waypoint24 waypoint41)
	(can_traverse rover5 waypoint41 waypoint33)
	(can_traverse rover5 waypoint33 waypoint41)
	(can_traverse rover5 waypoint45 waypoint29)
	(can_traverse rover5 waypoint29 waypoint45)
	(can_traverse rover5 waypoint45 waypoint36)
	(can_traverse rover5 waypoint36 waypoint45)
	(can_traverse rover5 waypoint45 waypoint37)
	(can_traverse rover5 waypoint37 waypoint45)
	(can_traverse rover5 waypoint45 waypoint38)
	(can_traverse rover5 waypoint38 waypoint45)
	(can_traverse rover5 waypoint48 waypoint49)
	(can_traverse rover5 waypoint49 waypoint48)
	(can_traverse rover5 waypoint31 waypoint0)
	(can_traverse rover5 waypoint0 waypoint31)
	(can_traverse rover5 waypoint31 waypoint35)
	(can_traverse rover5 waypoint35 waypoint31)
	(can_traverse rover5 waypoint47 waypoint9)
	(can_traverse rover5 waypoint9 waypoint47)
	(can_traverse rover5 waypoint5 waypoint18)
	(can_traverse rover5 waypoint18 waypoint5)
	(can_traverse rover5 waypoint13 waypoint2)
	(can_traverse rover5 waypoint2 waypoint13)
	(can_traverse rover5 waypoint34 waypoint28)
	(can_traverse rover5 waypoint28 waypoint34)
	(can_traverse rover5 waypoint10 waypoint20)
	(can_traverse rover5 waypoint20 waypoint10)
	(can_traverse rover5 waypoint10 waypoint42)
	(can_traverse rover5 waypoint42 waypoint10)
	(can_traverse rover5 waypoint44 waypoint22)
	(can_traverse rover5 waypoint22 waypoint44)
	(can_traverse rover5 waypoint44 waypoint27)
	(can_traverse rover5 waypoint27 waypoint44)
	(can_traverse rover5 waypoint26 waypoint3)
	(can_traverse rover5 waypoint3 waypoint26)
	(can_traverse rover5 waypoint26 waypoint8)
	(can_traverse rover5 waypoint8 waypoint26)
	(can_traverse rover5 waypoint6 waypoint40)
	(can_traverse rover5 waypoint40 waypoint6)
	(at rover6 waypoint35)
	(available rover6)
	(store_of rover6store rover6)
	(empty rover6store)
	(equipped_for_soil_analysis rover6)
	(equipped_for_imaging rover6)
	(can_traverse rover6 waypoint35 waypoint7)
	(can_traverse rover6 waypoint7 waypoint35)
	(can_traverse rover6 waypoint35 waypoint12)
	(can_traverse rover6 waypoint12 waypoint35)
	(can_traverse rover6 waypoint35 waypoint16)
	(can_traverse rover6 waypoint16 waypoint35)
	(can_traverse rover6 waypoint35 waypoint21)
	(can_traverse rover6 waypoint21 waypoint35)
	(can_traverse rover6 waypoint35 waypoint28)
	(can_traverse rover6 waypoint28 waypoint35)
	(can_traverse rover6 waypoint35 waypoint44)
	(can_traverse rover6 waypoint44 waypoint35)
	(can_traverse rover6 waypoint7 waypoint13)
	(can_traverse rover6 waypoint13 waypoint7)
	(can_traverse rover6 waypoint7 waypoint25)
	(can_traverse rover6 waypoint25 waypoint7)
	(can_traverse rover6 waypoint7 waypoint41)
	(can_traverse rover6 waypoint41 waypoint7)
	(can_traverse rover6 waypoint7 waypoint42)
	(can_traverse rover6 waypoint42 waypoint7)
	(can_traverse rover6 waypoint7 waypoint45)
	(can_traverse rover6 waypoint45 waypoint7)
	(can_traverse rover6 waypoint7 waypoint49)
	(can_traverse rover6 waypoint49 waypoint7)
	(can_traverse rover6 waypoint12 waypoint4)
	(can_traverse rover6 waypoint4 waypoint12)
	(can_traverse rover6 waypoint12 waypoint19)
	(can_traverse rover6 waypoint19 waypoint12)
	(can_traverse rover6 waypoint12 waypoint22)
	(can_traverse rover6 waypoint22 waypoint12)
	(can_traverse rover6 waypoint12 waypoint40)
	(can_traverse rover6 waypoint40 waypoint12)
	(can_traverse rover6 waypoint16 waypoint47)
	(can_traverse rover6 waypoint47 waypoint16)
	(can_traverse rover6 waypoint21 waypoint2)
	(can_traverse rover6 waypoint2 waypoint21)
	(can_traverse rover6 waypoint21 waypoint17)
	(can_traverse rover6 waypoint17 waypoint21)
	(can_traverse rover6 waypoint21 waypoint26)
	(can_traverse rover6 waypoint26 waypoint21)
	(can_traverse rover6 waypoint21 waypoint34)
	(can_traverse rover6 waypoint34 waypoint21)
	(can_traverse rover6 waypoint21 waypoint43)
	(can_traverse rover6 waypoint43 waypoint21)
	(can_traverse rover6 waypoint21 waypoint46)
	(can_traverse rover6 waypoint46 waypoint21)
	(can_traverse rover6 waypoint28 waypoint11)
	(can_traverse rover6 waypoint11 waypoint28)
	(can_traverse rover6 waypoint28 waypoint27)
	(can_traverse rover6 waypoint27 waypoint28)
	(can_traverse rover6 waypoint28 waypoint29)
	(can_traverse rover6 waypoint29 waypoint28)
	(can_traverse rover6 waypoint28 waypoint36)
	(can_traverse rover6 waypoint36 waypoint28)
	(can_traverse rover6 waypoint44 waypoint15)
	(can_traverse rover6 waypoint15 waypoint44)
	(can_traverse rover6 waypoint44 waypoint33)
	(can_traverse rover6 waypoint33 waypoint44)
	(can_traverse rover6 waypoint44 waypoint38)
	(can_traverse rover6 waypoint38 waypoint44)
	(can_traverse rover6 waypoint13 waypoint14)
	(can_traverse rover6 waypoint14 waypoint13)
	(can_traverse rover6 waypoint13 waypoint48)
	(can_traverse rover6 waypoint48 waypoint13)
	(can_traverse rover6 waypoint25 waypoint1)
	(can_traverse rover6 waypoint1 waypoint25)
	(can_traverse rover6 waypoint41 waypoint24)
	(can_traverse rover6 waypoint24 waypoint41)
	(can_traverse rover6 waypoint42 waypoint0)
	(can_traverse rover6 waypoint0 waypoint42)
	(can_traverse rover6 waypoint42 waypoint10)
	(can_traverse rover6 waypoint10 waypoint42)
	(can_traverse rover6 waypoint42 waypoint18)
	(can_traverse rover6 waypoint18 waypoint42)
	(can_traverse rover6 waypoint42 waypoint39)
	(can_traverse rover6 waypoint39 waypoint42)
	(can_traverse rover6 waypoint45 waypoint37)
	(can_traverse rover6 waypoint37 waypoint45)
	(can_traverse rover6 waypoint49 waypoint6)
	(can_traverse rover6 waypoint6 waypoint49)
	(can_traverse rover6 waypoint4 waypoint20)
	(can_traverse rover6 waypoint20 waypoint4)
	(can_traverse rover6 waypoint4 waypoint23)
	(can_traverse rover6 waypoint23 waypoint4)
	(can_traverse rover6 waypoint4 waypoint32)
	(can_traverse rover6 waypoint32 waypoint4)
	(can_traverse rover6 waypoint47 waypoint3)
	(can_traverse rover6 waypoint3 waypoint47)
	(can_traverse rover6 waypoint2 waypoint8)
	(can_traverse rover6 waypoint8 waypoint2)
	(can_traverse rover6 waypoint17 waypoint9)
	(can_traverse rover6 waypoint9 waypoint17)
	(can_traverse rover6 waypoint34 waypoint5)
	(can_traverse rover6 waypoint5 waypoint34)
	(can_traverse rover6 waypoint43 waypoint31)
	(can_traverse rover6 waypoint31 waypoint43)
	(can_traverse rover6 waypoint15 waypoint30)
	(can_traverse rover6 waypoint30 waypoint15)
	(at rover7 waypoint6)
	(available rover7)
	(store_of rover7store rover7)
	(empty rover7store)
	(equipped_for_imaging rover7)
	(can_traverse rover7 waypoint6 waypoint5)
	(can_traverse rover7 waypoint5 waypoint6)
	(can_traverse rover7 waypoint6 waypoint10)
	(can_traverse rover7 waypoint10 waypoint6)
	(can_traverse rover7 waypoint6 waypoint19)
	(can_traverse rover7 waypoint19 waypoint6)
	(can_traverse rover7 waypoint6 waypoint40)
	(can_traverse rover7 waypoint40 waypoint6)
	(can_traverse rover7 waypoint5 waypoint0)
	(can_traverse rover7 waypoint0 waypoint5)
	(can_traverse rover7 waypoint5 waypoint18)
	(can_traverse rover7 waypoint18 waypoint5)
	(can_traverse rover7 waypoint5 waypoint31)
	(can_traverse rover7 waypoint31 waypoint5)
	(can_traverse rover7 waypoint5 waypoint34)
	(can_traverse rover7 waypoint34 waypoint5)
	(can_traverse rover7 waypoint10 waypoint35)
	(can_traverse rover7 waypoint35 waypoint10)
	(can_traverse rover7 waypoint10 waypoint42)
	(can_traverse rover7 waypoint42 waypoint10)
	(can_traverse rover7 waypoint19 waypoint24)
	(can_traverse rover7 waypoint24 waypoint19)
	(can_traverse rover7 waypoint19 waypoint25)
	(can_traverse rover7 waypoint25 waypoint19)
	(can_traverse rover7 waypoint19 waypoint29)
	(can_traverse rover7 waypoint29 waypoint19)
	(can_traverse rover7 waypoint19 waypoint36)
	(can_traverse rover7 waypoint36 waypoint19)
	(can_traverse rover7 waypoint40 waypoint12)
	(can_traverse rover7 waypoint12 waypoint40)
	(can_traverse rover7 waypoint0 waypoint14)
	(can_traverse rover7 waypoint14 waypoint0)
	(can_traverse rover7 waypoint0 waypoint43)
	(can_traverse rover7 waypoint43 waypoint0)
	(can_traverse rover7 waypoint0 waypoint49)
	(can_traverse rover7 waypoint49 waypoint0)
	(can_traverse rover7 waypoint18 waypoint20)
	(can_traverse rover7 waypoint20 waypoint18)
	(can_traverse rover7 waypoint18 waypoint22)
	(can_traverse rover7 waypoint22 waypoint18)
	(can_traverse rover7 waypoint18 waypoint32)
	(can_traverse rover7 waypoint32 waypoint18)
	(can_traverse rover7 waypoint31 waypoint4)
	(can_traverse rover7 waypoint4 waypoint31)
	(can_traverse rover7 waypoint31 waypoint38)
	(can_traverse rover7 waypoint38 waypoint31)
	(can_traverse rover7 waypoint34 waypoint11)
	(can_traverse rover7 waypoint11 waypoint34)
	(can_traverse rover7 waypoint34 waypoint21)
	(can_traverse rover7 waypoint21 waypoint34)
	(can_traverse rover7 waypoint34 waypoint28)
	(can_traverse rover7 waypoint28 waypoint34)
	(can_traverse rover7 waypoint34 waypoint33)
	(can_traverse rover7 waypoint33 waypoint34)
	(can_traverse rover7 waypoint34 waypoint44)
	(can_traverse rover7 waypoint44 waypoint34)
	(can_traverse rover7 waypoint34 waypoint47)
	(can_traverse rover7 waypoint47 waypoint34)
	(can_traverse rover7 waypoint34 waypoint48)
	(can_traverse rover7 waypoint48 waypoint34)
	(can_traverse rover7 waypoint35 waypoint7)
	(can_traverse rover7 waypoint7 waypoint35)
	(can_traverse rover7 waypoint35 waypoint16)
	(can_traverse rover7 waypoint16 waypoint35)
	(can_traverse rover7 waypoint42 waypoint8)
	(can_traverse rover7 waypoint8 waypoint42)
	(can_traverse rover7 waypoint42 waypoint39)
	(can_traverse rover7 waypoint39 waypoint42)
	(can_traverse rover7 waypoint25 waypoint41)
	(can_traverse rover7 waypoint41 waypoint25)
	(can_traverse rover7 waypoint29 waypoint45)
	(can_traverse rover7 waypoint45 waypoint29)
	(can_traverse rover7 waypoint36 waypoint2)
	(can_traverse rover7 waypoint2 waypoint36)
	(can_traverse rover7 waypoint14 waypoint13)
	(can_traverse rover7 waypoint13 waypoint14)
	(at rover8 waypoint18)
	(available rover8)
	(store_of rover8store rover8)
	(empty rover8store)
	(equipped_for_soil_analysis rover8)
	(equipped_for_rock_analysis rover8)
	(equipped_for_imaging rover8)
	(can_traverse rover8 waypoint18 waypoint5)
	(can_traverse rover8 waypoint5 waypoint18)
	(can_traverse rover8 waypoint18 waypoint19)
	(can_traverse rover8 waypoint19 waypoint18)
	(can_traverse rover8 waypoint18 waypoint20)
	(can_traverse rover8 waypoint20 waypoint18)
	(can_traverse rover8 waypoint18 waypoint22)
	(can_traverse rover8 waypoint22 waypoint18)
	(can_traverse rover8 waypoint18 waypoint26)
	(can_traverse rover8 waypoint26 waypoint18)
	(can_traverse rover8 waypoint18 waypoint37)
	(can_traverse rover8 waypoint37 waypoint18)
	(can_traverse rover8 waypoint18 waypoint43)
	(can_traverse rover8 waypoint43 waypoint18)
	(can_traverse rover8 waypoint5 waypoint0)
	(can_traverse rover8 waypoint0 waypoint5)
	(can_traverse rover8 waypoint5 waypoint6)
	(can_traverse rover8 waypoint6 waypoint5)
	(can_traverse rover8 waypoint5 waypoint31)
	(can_traverse rover8 waypoint31 waypoint5)
	(can_traverse rover8 waypoint5 waypoint34)
	(can_traverse rover8 waypoint34 waypoint5)
	(can_traverse rover8 waypoint19 waypoint10)
	(can_traverse rover8 waypoint10 waypoint19)
	(can_traverse rover8 waypoint19 waypoint29)
	(can_traverse rover8 waypoint29 waypoint19)
	(can_traverse rover8 waypoint19 waypoint35)
	(can_traverse rover8 waypoint35 waypoint19)
	(can_traverse rover8 waypoint20 waypoint2)
	(can_traverse rover8 waypoint2 waypoint20)
	(can_traverse rover8 waypoint20 waypoint3)
	(can_traverse rover8 waypoint3 waypoint20)
	(can_traverse rover8 waypoint20 waypoint4)
	(can_traverse rover8 waypoint4 waypoint20)
	(can_traverse rover8 waypoint20 waypoint8)
	(can_traverse rover8 waypoint8 waypoint20)
	(can_traverse rover8 waypoint20 waypoint27)
	(can_traverse rover8 waypoint27 waypoint20)
	(can_traverse rover8 waypoint22 waypoint11)
	(can_traverse rover8 waypoint11 waypoint22)
	(can_traverse rover8 waypoint22 waypoint12)
	(can_traverse rover8 waypoint12 waypoint22)
	(can_traverse rover8 waypoint22 waypoint14)
	(can_traverse rover8 waypoint14 waypoint22)
	(can_traverse rover8 waypoint22 waypoint23)
	(can_traverse rover8 waypoint23 waypoint22)
	(can_traverse rover8 waypoint26 waypoint13)
	(can_traverse rover8 waypoint13 waypoint26)
	(can_traverse rover8 waypoint26 waypoint21)
	(can_traverse rover8 waypoint21 waypoint26)
	(can_traverse rover8 waypoint26 waypoint40)
	(can_traverse rover8 waypoint40 waypoint26)
	(can_traverse rover8 waypoint26 waypoint47)
	(can_traverse rover8 waypoint47 waypoint26)
	(can_traverse rover8 waypoint37 waypoint17)
	(can_traverse rover8 waypoint17 waypoint37)
	(can_traverse rover8 waypoint37 waypoint30)
	(can_traverse rover8 waypoint30 waypoint37)
	(can_traverse rover8 waypoint37 waypoint45)
	(can_traverse rover8 waypoint45 waypoint37)
	(can_traverse rover8 waypoint43 waypoint24)
	(can_traverse rover8 waypoint24 waypoint43)
	(can_traverse rover8 waypoint43 waypoint32)
	(can_traverse rover8 waypoint32 waypoint43)
	(can_traverse rover8 waypoint43 waypoint41)
	(can_traverse rover8 waypoint41 waypoint43)
	(can_traverse rover8 waypoint0 waypoint42)
	(can_traverse rover8 waypoint42 waypoint0)
	(can_traverse rover8 waypoint6 waypoint36)
	(can_traverse rover8 waypoint36 waypoint6)
	(can_traverse rover8 waypoint6 waypoint39)
	(can_traverse rover8 waypoint39 waypoint6)
	(can_traverse rover8 waypoint6 waypoint49)
	(can_traverse rover8 waypoint49 waypoint6)
	(can_traverse rover8 waypoint31 waypoint9)
	(can_traverse rover8 waypoint9 waypoint31)
	(can_traverse rover8 waypoint31 waypoint38)
	(can_traverse rover8 waypoint38 waypoint31)
	(can_traverse rover8 waypoint31 waypoint44)
	(can_traverse rover8 waypoint44 waypoint31)
	(can_traverse rover8 waypoint34 waypoint33)
	(can_traverse rover8 waypoint33 waypoint34)
	(can_traverse rover8 waypoint10 waypoint15)
	(can_traverse rover8 waypoint15 waypoint10)
	(can_traverse rover8 waypoint35 waypoint7)
	(can_traverse rover8 waypoint7 waypoint35)
	(can_traverse rover8 waypoint35 waypoint16)
	(can_traverse rover8 waypoint16 waypoint35)
	(can_traverse rover8 waypoint35 waypoint28)
	(can_traverse rover8 waypoint28 waypoint35)
	(can_traverse rover8 waypoint4 waypoint1)
	(can_traverse rover8 waypoint1 waypoint4)
	(can_traverse rover8 waypoint11 waypoint48)
	(can_traverse rover8 waypoint48 waypoint11)
	(can_traverse rover8 waypoint14 waypoint25)
	(can_traverse rover8 waypoint25 waypoint14)
	(can_traverse rover8 waypoint23 waypoint46)
	(can_traverse rover8 waypoint46 waypoint23)
	(at rover9 waypoint8)
	(available rover9)
	(store_of rover9store rover9)
	(empty rover9store)
	(equipped_for_imaging rover9)
	(can_traverse rover9 waypoint8 waypoint1)
	(can_traverse rover9 waypoint1 waypoint8)
	(can_traverse rover9 waypoint8 waypoint2)
	(can_traverse rover9 waypoint2 waypoint8)
	(can_traverse rover9 waypoint8 waypoint20)
	(can_traverse rover9 waypoint20 waypoint8)
	(can_traverse rover9 waypoint8 waypoint33)
	(can_traverse rover9 waypoint33 waypoint8)
	(can_traverse rover9 waypoint8 waypoint35)
	(can_traverse rover9 waypoint35 waypoint8)
	(can_traverse rover9 waypoint8 waypoint42)
	(can_traverse rover9 waypoint42 waypoint8)
	(can_traverse rover9 waypoint1 waypoint15)
	(can_traverse rover9 waypoint15 waypoint1)
	(can_traverse rover9 waypoint1 waypoint19)
	(can_traverse rover9 waypoint19 waypoint1)
	(can_traverse rover9 waypoint1 waypoint21)
	(can_traverse rover9 waypoint21 waypoint1)
	(can_traverse rover9 waypoint1 waypoint28)
	(can_traverse rover9 waypoint28 waypoint1)
	(can_traverse rover9 waypoint1 waypoint41)
	(can_traverse rover9 waypoint41 waypoint1)
	(can_traverse rover9 waypoint1 waypoint45)
	(can_traverse rover9 waypoint45 waypoint1)
	(can_traverse rover9 waypoint1 waypoint48)
	(can_traverse rover9 waypoint48 waypoint1)
	(can_traverse rover9 waypoint2 waypoint10)
	(can_traverse rover9 waypoint10 waypoint2)
	(can_traverse rover9 waypoint2 waypoint13)
	(can_traverse rover9 waypoint13 waypoint2)
	(can_traverse rover9 waypoint2 waypoint23)
	(can_traverse rover9 waypoint23 waypoint2)
	(can_traverse rover9 waypoint2 waypoint36)
	(can_traverse rover9 waypoint36 waypoint2)
	(can_traverse rover9 waypoint2 waypoint43)
	(can_traverse rover9 waypoint43 waypoint2)
	(can_traverse rover9 waypoint20 waypoint3)
	(can_traverse rover9 waypoint3 waypoint20)
	(can_traverse rover9 waypoint20 waypoint4)
	(can_traverse rover9 waypoint4 waypoint20)
	(can_traverse rover9 waypoint20 waypoint27)
	(can_traverse rover9 waypoint27 waypoint20)
	(can_traverse rover9 waypoint33 waypoint9)
	(can_traverse rover9 waypoint9 waypoint33)
	(can_traverse rover9 waypoint33 waypoint38)
	(can_traverse rover9 waypoint38 waypoint33)
	(can_traverse rover9 waypoint33 waypoint44)
	(can_traverse rover9 waypoint44 waypoint33)
	(can_traverse rover9 waypoint33 waypoint49)
	(can_traverse rover9 waypoint49 waypoint33)
	(can_traverse rover9 waypoint35 waypoint7)
	(can_traverse rover9 waypoint7 waypoint35)
	(can_traverse rover9 waypoint35 waypoint14)
	(can_traverse rover9 waypoint14 waypoint35)
	(can_traverse rover9 waypoint35 waypoint16)
	(can_traverse rover9 waypoint16 waypoint35)
	(can_traverse rover9 waypoint42 waypoint0)
	(can_traverse rover9 waypoint0 waypoint42)
	(can_traverse rover9 waypoint42 waypoint12)
	(can_traverse rover9 waypoint12 waypoint42)
	(can_traverse rover9 waypoint42 waypoint30)
	(can_traverse rover9 waypoint30 waypoint42)
	(can_traverse rover9 waypoint42 waypoint34)
	(can_traverse rover9 waypoint34 waypoint42)
	(can_traverse rover9 waypoint15 waypoint32)
	(can_traverse rover9 waypoint32 waypoint15)
	(can_traverse rover9 waypoint19 waypoint6)
	(can_traverse rover9 waypoint6 waypoint19)
	(can_traverse rover9 waypoint19 waypoint18)
	(can_traverse rover9 waypoint18 waypoint19)
	(can_traverse rover9 waypoint19 waypoint24)
	(can_traverse rover9 waypoint24 waypoint19)
	(can_traverse rover9 waypoint19 waypoint25)
	(can_traverse rover9 waypoint25 waypoint19)
	(can_traverse rover9 waypoint19 waypoint29)
	(can_traverse rover9 waypoint29 waypoint19)
	(can_traverse rover9 waypoint21 waypoint26)
	(can_traverse rover9 waypoint26 waypoint21)
	(can_traverse rover9 waypoint28 waypoint11)
	(can_traverse rover9 waypoint11 waypoint28)
	(can_traverse rover9 waypoint45 waypoint37)
	(can_traverse rover9 waypoint37 waypoint45)
	(can_traverse rover9 waypoint45 waypoint39)
	(can_traverse rover9 waypoint39 waypoint45)
	(can_traverse rover9 waypoint13 waypoint47)
	(can_traverse rover9 waypoint47 waypoint13)
	(can_traverse rover9 waypoint23 waypoint17)
	(can_traverse rover9 waypoint17 waypoint23)
	(can_traverse rover9 waypoint23 waypoint22)
	(can_traverse rover9 waypoint22 waypoint23)
	(on_board camera0 rover5)
	(calibration_target camera0 objective0)
	(supports camera0 low_res)
	(on_board camera1 rover9)
	(calibration_target camera1 objective5)
	(supports camera1 colour)
	(supports camera1 high_res)
	(on_board camera2 rover5)
	(calibration_target camera2 objective2)
	(supports camera2 colour)
	(on_board camera3 rover2)
	(calibration_target camera3 objective7)
	(supports camera3 colour)
	(supports camera3 high_res)
	(supports camera3 low_res)
	(on_board camera4 rover2)
	(calibration_target camera4 objective7)
	(supports camera4 colour)
	(supports camera4 high_res)
	(on_board camera5 rover9)
	(calibration_target camera5 objective2)
	(supports camera5 colour)
	(on_board camera6 rover9)
	(calibration_target camera6 objective5)
	(supports camera6 high_res)
	(on_board camera7 rover8)
	(calibration_target camera7 objective5)
	(supports camera7 colour)
	(supports camera7 high_res)
	(on_board camera8 rover8)
	(calibration_target camera8 objective2)
	(supports camera8 high_res)
	(supports camera8 low_res)
	(on_board camera9 rover0)
	(calibration_target camera9 objective7)
	(supports camera9 high_res)
	(supports camera9 low_res)
	(on_board camera10 rover0)
	(calibration_target camera10 objective1)
	(supports camera10 colour)
	(on_board camera11 rover6)
	(calibration_target camera11 objective5)
	(supports camera11 high_res)
	(on_board camera12 rover0)
	(calibration_target camera12 objective2)
	(supports camera12 colour)
	(supports camera12 low_res)
	(on_board camera13 rover0)
	(calibration_target camera13 objective2)
	(supports camera13 low_res)
	(on_board camera14 rover1)
	(calibration_target camera14 objective2)
	(supports camera14 colour)
	(on_board camera15 rover3)
	(calibration_target camera15 objective6)
	(supports camera15 colour)
	(on_board camera16 rover4)
	(calibration_target camera16 objective1)
	(supports camera16 colour)
	(supports camera16 high_res)
	(on_board camera17 rover7)
	(calibration_target camera17 objective6)
	(supports camera17 colour)
	(visible_from objective0 waypoint0)
	(visible_from objective0 waypoint1)
	(visible_from objective0 waypoint2)
	(visible_from objective0 waypoint3)
	(visible_from objective0 waypoint4)
	(visible_from objective0 waypoint5)
	(visible_from objective0 waypoint6)
	(visible_from objective0 waypoint7)
	(visible_from objective0 waypoint8)
	(visible_from objective0 waypoint9)
	(visible_from objective0 waypoint10)
	(visible_from objective0 waypoint11)
	(visible_from objective0 waypoint12)
	(visible_from objective0 waypoint13)
	(visible_from objective0 waypoint14)
	(visible_from objective0 waypoint15)
	(visible_from objective0 waypoint16)
	(visible_from objective0 waypoint17)
	(visible_from objective0 waypoint18)
	(visible_from objective0 waypoint19)
	(visible_from objective0 waypoint20)
	(visible_from objective0 waypoint21)
	(visible_from objective0 waypoint22)
	(visible_from objective0 waypoint23)
	(visible_from objective0 waypoint24)
	(visible_from objective0 waypoint25)
	(visible_from objective0 waypoint26)
	(visible_from objective0 waypoint27)
	(visible_from objective0 waypoint28)
	(visible_from objective0 waypoint29)
	(visible_from objective1 waypoint0)
	(visible_from objective1 waypoint1)
	(visible_from objective1 waypoint2)
	(visible_from objective1 waypoint3)
	(visible_from objective1 waypoint4)
	(visible_from objective1 waypoint5)
	(visible_from objective1 waypoint6)
	(visible_from objective1 waypoint7)
	(visible_from objective1 waypoint8)
	(visible_from objective1 waypoint9)
	(visible_from objective1 waypoint10)
	(visible_from objective1 waypoint11)
	(visible_from objective1 waypoint12)
	(visible_from objective1 waypoint13)
	(visible_from objective1 waypoint14)
	(visible_from objective1 waypoint15)
	(visible_from objective2 waypoint0)
	(visible_from objective2 waypoint1)
	(visible_from objective2 waypoint2)
	(visible_from objective2 waypoint3)
	(visible_from objective2 waypoint4)
	(visible_from objective2 waypoint5)
	(visible_from objective2 waypoint6)
	(visible_from objective2 waypoint7)
	(visible_from objective2 waypoint8)
	(visible_from objective2 waypoint9)
	(visible_from objective2 waypoint10)
	(visible_from objective2 waypoint11)
	(visible_from objective2 waypoint12)
	(visible_from objective2 waypoint13)
	(visible_from objective2 waypoint14)
	(visible_from objective2 waypoint15)
	(visible_from objective2 waypoint16)
	(visible_from objective2 waypoint17)
	(visible_from objective2 waypoint18)
	(visible_from objective2 waypoint19)
	(visible_from objective2 waypoint20)
	(visible_from objective2 waypoint21)
	(visible_from objective2 waypoint22)
	(visible_from objective2 waypoint23)
	(visible_from objective2 waypoint24)
	(visible_from objective2 waypoint25)
	(visible_from objective2 waypoint26)
	(visible_from objective2 waypoint27)
	(visible_from objective2 waypoint28)
	(visible_from objective2 waypoint29)
	(visible_from objective2 waypoint30)
	(visible_from objective2 waypoint31)
	(visible_from objective3 waypoint0)
	(visible_from objective3 waypoint1)
	(visible_from objective3 waypoint2)
	(visible_from objective3 waypoint3)
	(visible_from objective3 waypoint4)
	(visible_from objective3 waypoint5)
	(visible_from objective3 waypoint6)
	(visible_from objective3 waypoint7)
	(visible_from objective3 waypoint8)
	(visible_from objective3 waypoint9)
	(visible_from objective3 waypoint10)
	(visible_from objective3 waypoint11)
	(visible_from objective3 waypoint12)
	(visible_from objective3 waypoint13)
	(visible_from objective3 waypoint14)
	(visible_from objective3 waypoint15)
	(visible_from objective3 waypoint16)
	(visible_from objective3 waypoint17)
	(visible_from objective3 waypoint18)
	(visible_from objective3 waypoint19)
	(visible_from objective3 waypoint20)
	(visible_from objective3 waypoint21)
	(visible_from objective3 waypoint22)
	(visible_from objective3 waypoint23)
	(visible_from objective3 waypoint24)
	(visible_from objective3 waypoint25)
	(visible_from objective3 waypoint26)
	(visible_from objective3 waypoint27)
	(visible_from objective3 waypoint28)
	(visible_from objective3 waypoint29)
	(visible_from objective3 waypoint30)
	(visible_from objective3 waypoint31)
	(visible_from objective3 waypoint32)
	(visible_from objective3 waypoint33)
	(visible_from objective3 waypoint34)
	(visible_from objective3 waypoint35)
	(visible_from objective3 waypoint36)
	(visible_from objective3 waypoint37)
	(visible_from objective3 waypoint38)
	(visible_from objective3 waypoint39)
	(visible_from objective3 waypoint40)
	(visible_from objective3 waypoint41)
	(visible_from objective3 waypoint42)
	(visible_from objective3 waypoint43)
	(visible_from objective3 waypoint44)
	(visible_from objective3 waypoint45)
	(visible_from objective3 waypoint46)
	(visible_from objective3 waypoint47)
	(visible_from objective4 waypoint0)
	(visible_from objective4 waypoint1)
	(visible_from objective4 waypoint2)
	(visible_from objective4 waypoint3)
	(visible_from objective4 waypoint4)
	(visible_from objective4 waypoint5)
	(visible_from objective4 waypoint6)
	(visible_from objective4 waypoint7)
	(visible_from objective4 waypoint8)
	(visible_from objective4 waypoint9)
	(visible_from objective4 waypoint10)
	(visible_from objective4 waypoint11)
	(visible_from objective4 waypoint12)
	(visible_from objective4 waypoint13)
	(visible_from objective4 waypoint14)
	(visible_from objective4 waypoint15)
	(visible_from objective4 waypoint16)
	(visible_from objective4 waypoint17)
	(visible_from objective4 waypoint18)
	(visible_from objective4 waypoint19)
	(visible_from objective5 waypoint0)
	(visible_from objective5 waypoint1)
	(visible_from objective5 waypoint2)
	(visible_from objective5 waypoint3)
	(visible_from objective5 waypoint4)
	(visible_from objective5 waypoint5)
	(visible_from objective5 waypoint6)
	(visible_from objective5 waypoint7)
	(visible_from objective5 waypoint8)
	(visible_from objective5 waypoint9)
	(visible_from objective5 waypoint10)
	(visible_from objective5 waypoint11)
	(visible_from objective5 waypoint12)
	(visible_from objective6 waypoint0)
	(visible_from objective6 waypoint1)
	(visible_from objective6 waypoint2)
	(visible_from objective6 waypoint3)
	(visible_from objective6 waypoint4)
	(visible_from objective6 waypoint5)
	(visible_from objective6 waypoint6)
	(visible_from objective6 waypoint7)
	(visible_from objective6 waypoint8)
	(visible_from objective7 waypoint0)
	(visible_from objective7 waypoint1)
	(visible_from objective7 waypoint2)
	(visible_from objective7 waypoint3)
	(visible_from objective7 waypoint4)
	(visible_from objective7 waypoint5)
	(visible_from objective7 waypoint6)
	(visible_from objective7 waypoint7)
	(visible_from objective7 waypoint8)
	(visible_from objective7 waypoint9)
)

(:goal (and
(communicated_soil_data waypoint49)
(communicated_soil_data waypoint48)
(communicated_soil_data waypoint18)
(communicated_soil_data waypoint17)
(communicated_soil_data waypoint0)
(communicated_soil_data waypoint16)
(communicated_soil_data waypoint28)
(communicated_soil_data waypoint25)
(communicated_soil_data waypoint4)
(communicated_soil_data waypoint33)
(communicated_soil_data waypoint5)
(communicated_soil_data waypoint24)
(communicated_soil_data waypoint42)
(communicated_soil_data waypoint21)
(communicated_rock_data waypoint11)
(communicated_rock_data waypoint28)
(communicated_rock_data waypoint39)
(communicated_rock_data waypoint6)
(communicated_rock_data waypoint24)
(communicated_rock_data waypoint48)
(communicated_rock_data waypoint38)
(communicated_rock_data waypoint13)
(communicated_rock_data waypoint23)
(communicated_rock_data waypoint49)
(communicated_rock_data waypoint40)
(communicated_rock_data waypoint25)
(communicated_rock_data waypoint26)
(communicated_rock_data waypoint20)
(communicated_image_data objective3 colour)
(communicated_image_data objective2 colour)
(communicated_image_data objective2 high_res)
(communicated_image_data objective1 colour)
(communicated_image_data objective0 high_res)
(communicated_image_data objective7 colour)
(communicated_image_data objective4 colour)
(communicated_image_data objective3 high_res)
(communicated_image_data objective6 colour)
	)
)
)
