
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain satellite)
    (:requirements :typing)
    (:types
        satellite - object
        direction - object
        instrument - object
        mode - object
        object
    )

    (:constants
        
    )

    (:predicates
        (pointing ?x1 - satellite ?x2 - direction)
        (have_image ?x1 - direction ?x2 - mode)
        (power_on ?x1 - instrument)
        (on_board ?x1 - instrument ?x2 - satellite)
        (power_avail ?x1 - satellite)
        (supports ?x1 - instrument ?x2 - mode)
        (calibrated ?x1 - instrument)
        (calibration_target ?x1 - instrument ?x2 - direction)
    )

    (:functions
        
    )

    

    
    (:action calibrate_1
     :parameters (?x0 - satellite ?x1 - instrument ?x2 - direction)
     :precondition (and (calibration_target ?x1 ?x2) (pointing ?x0 ?x2) (on_board ?x1 ?x0) (power_on ?x1))
     :effect (and
        (calibrated ?x1))
    )


    (:action switch_off_1
     :parameters (?x0 - instrument ?x1 - satellite)
     :precondition (and (on_board ?x0 ?x1) (calibrated ?x0) (power_on ?x0))
     :effect (and
        (power_avail ?x1)
        (not (power_on ?x0)))
    )


    (:action take_image_1
     :parameters (?x0 - satellite ?x1 - direction ?x2 - instrument ?x3 - mode)
     :precondition (and (power_on ?x2) (pointing ?x0 ?x1) (calibrated ?x2) (supports ?x2 ?x3) (on_board ?x2 ?x0))
     :effect (and
        (have_image ?x1 ?x3))
    )


    (:action switch_on_1
     :parameters (?x0 - instrument ?x1 - satellite)
     :precondition (and (on_board ?x0 ?x1) (power_avail ?x1))
     :effect (and
        (power_on ?x0)
        (not (calibrated ?x0))
        (not (power_avail ?x1)))
    )


    (:action turn_to_1
     :parameters (?x0 - satellite ?x1 - direction ?x2 - direction)
     :precondition (pointing ?x0 ?x2)
     :effect (and
        (pointing ?x0 ?x1)
        (not (pointing ?x0 ?x2)))
    )

)