(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite2 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite3 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite4 - satellite
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	thermograph3 - mode
	thermograph4 - mode
	thermograph0 - mode
	image1 - mode
	thermograph2 - mode
	infrared5 - mode
	image6 - mode
	groundstation4 - direction
	groundstation0 - direction
	star1 - direction
	groundstation2 - direction
	star3 - direction
	phenomenon5 - direction
	phenomenon6 - direction
	phenomenon7 - direction
	planet8 - direction
	phenomenon9 - direction
	phenomenon10 - direction
	planet11 - direction
	planet12 - direction
	planet13 - direction
	phenomenon14 - direction
	phenomenon15 - direction
	phenomenon16 - direction
	phenomenon17 - direction
	planet18 - direction
	phenomenon19 - direction
	phenomenon20 - direction
	star21 - direction
	planet22 - direction
	star23 - direction
	phenomenon24 - direction
)
(:init
	(supports instrument0 infrared5)
	(supports instrument0 thermograph2)
	(calibration_target instrument0 star3)
	(supports instrument1 thermograph3)
	(supports instrument1 thermograph0)
	(supports instrument1 thermograph4)
	(calibration_target instrument1 star3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 planet8)
	(supports instrument2 thermograph3)
	(supports instrument2 image1)
	(calibration_target instrument2 star1)
	(supports instrument3 image1)
	(calibration_target instrument3 star3)
	(supports instrument4 thermograph3)
	(supports instrument4 thermograph0)
	(supports instrument4 thermograph4)
	(calibration_target instrument4 star1)
	(supports instrument5 thermograph4)
	(supports instrument5 image6)
	(calibration_target instrument5 groundstation4)
	(supports instrument6 infrared5)
	(calibration_target instrument6 groundstation4)
	(supports instrument7 image6)
	(calibration_target instrument7 groundstation0)
	(supports instrument8 thermograph3)
	(calibration_target instrument8 groundstation2)
	(supports instrument9 thermograph3)
	(supports instrument9 image1)
	(calibration_target instrument9 groundstation0)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(power_avail satellite1)
	(pointing satellite1 phenomenon16)
	(supports instrument10 image1)
	(supports instrument10 image6)
	(calibration_target instrument10 star3)
	(supports instrument11 image6)
	(supports instrument11 thermograph3)
	(calibration_target instrument11 star1)
	(supports instrument12 thermograph0)
	(calibration_target instrument12 groundstation0)
	(supports instrument13 thermograph2)
	(supports instrument13 infrared5)
	(calibration_target instrument13 star1)
	(supports instrument14 infrared5)
	(supports instrument14 thermograph3)
	(supports instrument14 image1)
	(calibration_target instrument14 groundstation2)
	(supports instrument15 infrared5)
	(calibration_target instrument15 groundstation2)
	(supports instrument16 thermograph2)
	(supports instrument16 image6)
	(calibration_target instrument16 star3)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(power_avail satellite2)
	(pointing satellite2 star1)
	(supports instrument17 image1)
	(calibration_target instrument17 groundstation4)
	(supports instrument18 thermograph2)
	(calibration_target instrument18 star3)
	(supports instrument19 thermograph2)
	(calibration_target instrument19 groundstation0)
	(supports instrument20 thermograph2)
	(calibration_target instrument20 star3)
	(supports instrument21 thermograph2)
	(supports instrument21 image6)
	(supports instrument21 thermograph3)
	(calibration_target instrument21 star3)
	(supports instrument22 infrared5)
	(supports instrument22 image1)
	(supports instrument22 thermograph3)
	(calibration_target instrument22 groundstation0)
	(supports instrument23 thermograph2)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 star1)
	(supports instrument24 image6)
	(supports instrument24 infrared5)
	(calibration_target instrument24 groundstation4)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(power_avail satellite3)
	(pointing satellite3 phenomenon7)
	(supports instrument25 thermograph3)
	(supports instrument25 image1)
	(calibration_target instrument25 groundstation0)
	(supports instrument26 image1)
	(supports instrument26 thermograph2)
	(supports instrument26 thermograph0)
	(calibration_target instrument26 groundstation2)
	(supports instrument27 thermograph4)
	(supports instrument27 image1)
	(supports instrument27 infrared5)
	(calibration_target instrument27 star1)
	(supports instrument28 thermograph2)
	(supports instrument28 image1)
	(calibration_target instrument28 star1)
	(supports instrument29 image6)
	(calibration_target instrument29 star1)
	(supports instrument30 thermograph0)
	(supports instrument30 infrared5)
	(calibration_target instrument30 groundstation2)
	(supports instrument31 image1)
	(supports instrument31 thermograph2)
	(calibration_target instrument31 groundstation2)
	(supports instrument32 thermograph2)
	(calibration_target instrument32 star3)
	(supports instrument33 image6)
	(supports instrument33 infrared5)
	(calibration_target instrument33 star3)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(power_avail satellite4)
	(pointing satellite4 planet11)
)
(:goal (and
	(pointing satellite0 planet13)
	(have_image phenomenon5 thermograph2)
	(have_image phenomenon6 thermograph4)
	(have_image phenomenon6 image6)
	(have_image phenomenon7 infrared5)
	(have_image phenomenon7 thermograph4)
	(have_image planet8 thermograph2)
	(have_image phenomenon10 thermograph4)
	(have_image phenomenon10 thermograph0)
	(have_image planet11 thermograph3)
	(have_image planet12 thermograph2)
	(have_image planet12 image6)
	(have_image planet13 image1)
	(have_image planet13 image6)
	(have_image phenomenon14 image1)
	(have_image phenomenon14 thermograph3)
	(have_image phenomenon15 thermograph4)
	(have_image phenomenon16 image1)
	(have_image phenomenon17 thermograph3)
	(have_image phenomenon17 thermograph4)
	(have_image planet18 thermograph4)
	(have_image planet18 thermograph3)
	(have_image phenomenon19 thermograph0)
	(have_image phenomenon20 image6)
	(have_image star21 image6)
	(have_image star23 image1)
	(have_image phenomenon24 thermograph4)
	(have_image phenomenon24 thermograph2)
))

)
