(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite2 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite3 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite4 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	thermograph0 - mode
	thermograph3 - mode
	image6 - mode
	infrared5 - mode
	image8 - mode
	thermograph7 - mode
	image1 - mode
	thermograph2 - mode
	thermograph4 - mode
	groundstation0 - direction
	star3 - direction
	star4 - direction
	star1 - direction
	groundstation2 - direction
	star5 - direction
	star6 - direction
	phenomenon7 - direction
	star8 - direction
	star9 - direction
	planet10 - direction
	phenomenon11 - direction
	phenomenon12 - direction
	phenomenon13 - direction
	planet14 - direction
	phenomenon15 - direction
	phenomenon16 - direction
	phenomenon17 - direction
	phenomenon18 - direction
	star19 - direction
	star20 - direction
	star21 - direction
	planet22 - direction
	phenomenon23 - direction
	phenomenon24 - direction
)
(:init
	(supports instrument0 image1)
	(supports instrument0 thermograph3)
	(calibration_target instrument0 star3)
	(supports instrument1 infrared5)
	(calibration_target instrument1 star3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 star8)
	(supports instrument2 image1)
	(supports instrument2 thermograph3)
	(supports instrument2 image8)
	(calibration_target instrument2 star4)
	(supports instrument3 thermograph2)
	(supports instrument3 thermograph4)
	(supports instrument3 image1)
	(calibration_target instrument3 groundstation0)
	(supports instrument4 infrared5)
	(supports instrument4 image1)
	(calibration_target instrument4 groundstation2)
	(supports instrument5 image6)
	(supports instrument5 image1)
	(calibration_target instrument5 star3)
	(supports instrument6 image8)
	(supports instrument6 thermograph2)
	(calibration_target instrument6 star3)
	(supports instrument7 image6)
	(supports instrument7 thermograph4)
	(supports instrument7 infrared5)
	(calibration_target instrument7 star4)
	(supports instrument8 thermograph3)
	(supports instrument8 thermograph0)
	(calibration_target instrument8 groundstation2)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(power_avail satellite1)
	(pointing satellite1 phenomenon16)
	(supports instrument9 thermograph0)
	(calibration_target instrument9 star4)
	(supports instrument10 thermograph0)
	(calibration_target instrument10 star1)
	(supports instrument11 thermograph0)
	(calibration_target instrument11 star4)
	(supports instrument12 thermograph0)
	(supports instrument12 thermograph4)
	(supports instrument12 thermograph2)
	(calibration_target instrument12 star4)
	(supports instrument13 image8)
	(supports instrument13 infrared5)
	(supports instrument13 thermograph3)
	(calibration_target instrument13 star1)
	(supports instrument14 thermograph4)
	(supports instrument14 thermograph7)
	(calibration_target instrument14 groundstation0)
	(supports instrument15 thermograph2)
	(supports instrument15 image8)
	(calibration_target instrument15 groundstation2)
	(supports instrument16 thermograph3)
	(supports instrument16 image1)
	(calibration_target instrument16 groundstation2)
	(supports instrument17 thermograph4)
	(supports instrument17 infrared5)
	(supports instrument17 thermograph0)
	(calibration_target instrument17 star1)
	(supports instrument18 infrared5)
	(supports instrument18 thermograph2)
	(supports instrument18 image6)
	(calibration_target instrument18 star3)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(power_avail satellite2)
	(pointing satellite2 groundstation2)
	(supports instrument19 thermograph0)
	(supports instrument19 image6)
	(calibration_target instrument19 star3)
	(supports instrument20 thermograph7)
	(calibration_target instrument20 star3)
	(supports instrument21 image1)
	(supports instrument21 thermograph3)
	(calibration_target instrument21 star1)
	(supports instrument22 infrared5)
	(supports instrument22 image6)
	(calibration_target instrument22 star1)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(power_avail satellite3)
	(pointing satellite3 phenomenon7)
	(supports instrument23 infrared5)
	(supports instrument23 image6)
	(calibration_target instrument23 star1)
	(supports instrument24 infrared5)
	(calibration_target instrument24 star4)
	(supports instrument25 thermograph7)
	(supports instrument25 image8)
	(supports instrument25 thermograph2)
	(calibration_target instrument25 star1)
	(supports instrument26 thermograph4)
	(supports instrument26 thermograph2)
	(supports instrument26 image1)
	(calibration_target instrument26 groundstation2)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(power_avail satellite4)
	(pointing satellite4 star21)
)
(:goal (and
	(pointing satellite0 phenomenon11)
	(pointing satellite1 planet22)
	(pointing satellite2 groundstation0)
	(have_image star5 image8)
	(have_image star5 thermograph0)
	(have_image star5 thermograph7)
	(have_image star6 image8)
	(have_image star6 image6)
	(have_image star6 thermograph2)
	(have_image phenomenon7 image8)
	(have_image phenomenon7 thermograph3)
	(have_image phenomenon7 image6)
	(have_image star8 thermograph4)
	(have_image star9 infrared5)
	(have_image star9 thermograph4)
	(have_image star9 image1)
	(have_image planet10 infrared5)
	(have_image planet10 image8)
	(have_image planet10 thermograph4)
	(have_image phenomenon11 image1)
	(have_image phenomenon11 image8)
	(have_image phenomenon12 thermograph2)
	(have_image phenomenon12 image8)
	(have_image phenomenon13 image1)
	(have_image planet14 thermograph2)
	(have_image phenomenon15 thermograph3)
	(have_image phenomenon15 thermograph7)
	(have_image phenomenon15 image8)
	(have_image phenomenon16 thermograph4)
	(have_image phenomenon16 image1)
	(have_image phenomenon17 thermograph7)
	(have_image phenomenon17 infrared5)
	(have_image phenomenon17 thermograph4)
	(have_image phenomenon18 thermograph0)
	(have_image phenomenon18 thermograph4)
	(have_image star19 thermograph7)
	(have_image star19 thermograph0)
	(have_image star19 thermograph2)
	(have_image star20 thermograph2)
	(have_image star20 thermograph7)
	(have_image star21 image6)
	(have_image planet22 thermograph2)
	(have_image planet22 image6)
	(have_image phenomenon23 infrared5)
	(have_image phenomenon24 thermograph0)
	(have_image phenomenon24 thermograph7)
))

)
