(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite1 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite2 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite3 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	satellite4 - satellite
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	infrared5 - mode
	thermograph7 - mode
	thermograph2 - mode
	thermograph4 - mode
	image1 - mode
	thermograph0 - mode
	image6 - mode
	thermograph3 - mode
	groundstation2 - direction
	star0 - direction
	groundstation1 - direction
	groundstation4 - direction
	groundstation3 - direction
	planet5 - direction
	planet6 - direction
	phenomenon7 - direction
	phenomenon8 - direction
	star9 - direction
	star10 - direction
	star11 - direction
	star12 - direction
	planet13 - direction
	phenomenon14 - direction
	planet15 - direction
	planet16 - direction
	phenomenon17 - direction
	planet18 - direction
	phenomenon19 - direction
	planet20 - direction
	phenomenon21 - direction
	star22 - direction
	planet23 - direction
	phenomenon24 - direction
)
(:init
	(supports instrument0 thermograph4)
	(supports instrument0 image6)
	(calibration_target instrument0 groundstation1)
	(supports instrument1 image6)
	(calibration_target instrument1 groundstation4)
	(supports instrument2 thermograph4)
	(supports instrument2 thermograph2)
	(supports instrument2 thermograph7)
	(calibration_target instrument2 groundstation1)
	(supports instrument3 thermograph7)
	(supports instrument3 thermograph3)
	(calibration_target instrument3 groundstation3)
	(supports instrument4 image1)
	(calibration_target instrument4 groundstation3)
	(supports instrument5 thermograph3)
	(calibration_target instrument5 star0)
	(supports instrument6 thermograph2)
	(calibration_target instrument6 groundstation2)
	(supports instrument7 thermograph2)
	(supports instrument7 infrared5)
	(calibration_target instrument7 star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(power_avail satellite0)
	(pointing satellite0 planet16)
	(supports instrument8 infrared5)
	(supports instrument8 thermograph3)
	(calibration_target instrument8 groundstation4)
	(supports instrument9 thermograph3)
	(supports instrument9 thermograph2)
	(calibration_target instrument9 groundstation1)
	(supports instrument10 image6)
	(calibration_target instrument10 star0)
	(supports instrument11 thermograph0)
	(supports instrument11 image1)
	(calibration_target instrument11 groundstation1)
	(supports instrument12 image6)
	(supports instrument12 infrared5)
	(supports instrument12 thermograph2)
	(calibration_target instrument12 groundstation2)
	(supports instrument13 image6)
	(calibration_target instrument13 groundstation2)
	(supports instrument14 image1)
	(supports instrument14 thermograph3)
	(calibration_target instrument14 groundstation4)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(power_avail satellite1)
	(pointing satellite1 groundstation1)
	(supports instrument15 thermograph0)
	(calibration_target instrument15 groundstation3)
	(supports instrument16 image1)
	(calibration_target instrument16 groundstation4)
	(supports instrument17 image1)
	(calibration_target instrument17 star0)
	(supports instrument18 image1)
	(calibration_target instrument18 groundstation4)
	(supports instrument19 image1)
	(supports instrument19 image6)
	(supports instrument19 thermograph2)
	(calibration_target instrument19 groundstation4)
	(supports instrument20 infrared5)
	(supports instrument20 thermograph3)
	(supports instrument20 thermograph2)
	(calibration_target instrument20 star0)
	(supports instrument21 image1)
	(supports instrument21 thermograph4)
	(calibration_target instrument21 groundstation1)
	(supports instrument22 thermograph0)
	(supports instrument22 infrared5)
	(calibration_target instrument22 groundstation3)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(on_board instrument21 satellite2)
	(on_board instrument22 satellite2)
	(power_avail satellite2)
	(pointing satellite2 phenomenon7)
	(supports instrument23 thermograph2)
	(supports instrument23 image6)
	(calibration_target instrument23 star0)
	(supports instrument24 image6)
	(supports instrument24 thermograph4)
	(supports instrument24 thermograph7)
	(calibration_target instrument24 groundstation2)
	(supports instrument25 thermograph3)
	(supports instrument25 image6)
	(supports instrument25 image1)
	(calibration_target instrument25 groundstation1)
	(supports instrument26 thermograph4)
	(supports instrument26 image6)
	(calibration_target instrument26 groundstation1)
	(supports instrument27 infrared5)
	(calibration_target instrument27 groundstation1)
	(supports instrument28 thermograph2)
	(supports instrument28 thermograph7)
	(calibration_target instrument28 groundstation2)
	(supports instrument29 image6)
	(supports instrument29 thermograph4)
	(calibration_target instrument29 groundstation2)
	(supports instrument30 thermograph4)
	(calibration_target instrument30 groundstation4)
	(supports instrument31 infrared5)
	(supports instrument31 thermograph3)
	(calibration_target instrument31 groundstation4)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(on_board instrument28 satellite3)
	(on_board instrument29 satellite3)
	(on_board instrument30 satellite3)
	(on_board instrument31 satellite3)
	(power_avail satellite3)
	(pointing satellite3 star11)
	(supports instrument32 image6)
	(supports instrument32 thermograph0)
	(supports instrument32 thermograph7)
	(calibration_target instrument32 groundstation2)
	(supports instrument33 image1)
	(supports instrument33 thermograph0)
	(supports instrument33 thermograph3)
	(calibration_target instrument33 star0)
	(supports instrument34 image1)
	(supports instrument34 image6)
	(supports instrument34 thermograph7)
	(calibration_target instrument34 groundstation3)
	(supports instrument35 image1)
	(supports instrument35 thermograph2)
	(calibration_target instrument35 groundstation3)
	(supports instrument36 image6)
	(calibration_target instrument36 groundstation1)
	(supports instrument37 thermograph4)
	(supports instrument37 image6)
	(supports instrument37 thermograph3)
	(calibration_target instrument37 groundstation4)
	(supports instrument38 image6)
	(supports instrument38 thermograph0)
	(supports instrument38 image1)
	(calibration_target instrument38 groundstation4)
	(supports instrument39 thermograph3)
	(calibration_target instrument39 groundstation3)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(on_board instrument34 satellite4)
	(on_board instrument35 satellite4)
	(on_board instrument36 satellite4)
	(on_board instrument37 satellite4)
	(on_board instrument38 satellite4)
	(on_board instrument39 satellite4)
	(power_avail satellite4)
	(pointing satellite4 star22)
)
(:goal (and
	(have_image planet5 image6)
	(have_image planet6 thermograph4)
	(have_image planet6 thermograph0)
	(have_image phenomenon8 thermograph0)
	(have_image phenomenon8 thermograph7)
	(have_image star9 image1)
	(have_image star10 infrared5)
	(have_image star10 image1)
	(have_image star11 infrared5)
	(have_image star11 thermograph3)
	(have_image star12 infrared5)
	(have_image planet13 thermograph3)
	(have_image phenomenon14 thermograph0)
	(have_image phenomenon14 image6)
	(have_image planet15 image1)
	(have_image planet16 image1)
	(have_image phenomenon17 infrared5)
	(have_image phenomenon17 thermograph7)
	(have_image planet18 image1)
	(have_image planet18 infrared5)
	(have_image planet20 thermograph7)
	(have_image phenomenon21 thermograph7)
	(have_image star22 thermograph4)
	(have_image star22 thermograph7)
	(have_image planet23 infrared5)
	(have_image phenomenon24 thermograph4)
	(have_image phenomenon24 thermograph2)
))

)
