(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite1 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite2 - satellite
	instrument18 - instrument
	satellite3 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite4 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	thermograph0 - mode
	thermograph7 - mode
	image6 - mode
	image8 - mode
	thermograph3 - mode
	infrared5 - mode
	thermograph2 - mode
	spectrograph9 - mode
	image1 - mode
	thermograph4 - mode
	groundstation4 - direction
	star3 - direction
	star0 - direction
	groundstation1 - direction
	star2 - direction
	phenomenon5 - direction
	planet6 - direction
	planet7 - direction
	planet8 - direction
	star9 - direction
	planet10 - direction
	planet11 - direction
	star12 - direction
	phenomenon13 - direction
	phenomenon14 - direction
	planet15 - direction
	phenomenon16 - direction
	star17 - direction
	phenomenon18 - direction
	phenomenon19 - direction
	star20 - direction
	star21 - direction
	phenomenon22 - direction
	star23 - direction
	star24 - direction
)
(:init
	(supports instrument0 thermograph2)
	(supports instrument0 thermograph7)
	(supports instrument0 image6)
	(calibration_target instrument0 star3)
	(supports instrument1 spectrograph9)
	(calibration_target instrument1 star0)
	(supports instrument2 thermograph4)
	(supports instrument2 infrared5)
	(calibration_target instrument2 groundstation1)
	(supports instrument3 thermograph2)
	(supports instrument3 thermograph0)
	(supports instrument3 infrared5)
	(calibration_target instrument3 groundstation4)
	(supports instrument4 image1)
	(supports instrument4 thermograph4)
	(calibration_target instrument4 groundstation4)
	(supports instrument5 thermograph0)
	(supports instrument5 spectrograph9)
	(supports instrument5 thermograph7)
	(calibration_target instrument5 star3)
	(supports instrument6 infrared5)
	(supports instrument6 image8)
	(calibration_target instrument6 groundstation1)
	(supports instrument7 image8)
	(calibration_target instrument7 star0)
	(supports instrument8 image8)
	(calibration_target instrument8 star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(power_avail satellite0)
	(pointing satellite0 star17)
	(supports instrument9 image8)
	(calibration_target instrument9 groundstation1)
	(supports instrument10 infrared5)
	(supports instrument10 spectrograph9)
	(supports instrument10 thermograph4)
	(calibration_target instrument10 groundstation1)
	(supports instrument11 image1)
	(supports instrument11 thermograph7)
	(supports instrument11 image8)
	(calibration_target instrument11 star0)
	(supports instrument12 spectrograph9)
	(supports instrument12 thermograph3)
	(calibration_target instrument12 star2)
	(supports instrument13 thermograph0)
	(supports instrument13 thermograph7)
	(calibration_target instrument13 star3)
	(supports instrument14 infrared5)
	(supports instrument14 image6)
	(calibration_target instrument14 star3)
	(supports instrument15 spectrograph9)
	(supports instrument15 image8)
	(supports instrument15 thermograph4)
	(calibration_target instrument15 star0)
	(supports instrument16 thermograph4)
	(supports instrument16 thermograph7)
	(supports instrument16 image1)
	(calibration_target instrument16 groundstation4)
	(supports instrument17 thermograph3)
	(supports instrument17 thermograph7)
	(supports instrument17 thermograph0)
	(calibration_target instrument17 star2)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(on_board instrument16 satellite1)
	(on_board instrument17 satellite1)
	(power_avail satellite1)
	(pointing satellite1 planet8)
	(supports instrument18 thermograph7)
	(calibration_target instrument18 groundstation1)
	(on_board instrument18 satellite2)
	(power_avail satellite2)
	(pointing satellite2 planet15)
	(supports instrument19 thermograph4)
	(supports instrument19 thermograph3)
	(calibration_target instrument19 star0)
	(supports instrument20 thermograph2)
	(supports instrument20 thermograph4)
	(supports instrument20 spectrograph9)
	(calibration_target instrument20 groundstation4)
	(supports instrument21 infrared5)
	(supports instrument21 thermograph2)
	(supports instrument21 thermograph4)
	(calibration_target instrument21 groundstation4)
	(supports instrument22 thermograph2)
	(calibration_target instrument22 groundstation1)
	(supports instrument23 image1)
	(calibration_target instrument23 star2)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(power_avail satellite3)
	(pointing satellite3 star0)
	(supports instrument24 thermograph4)
	(supports instrument24 spectrograph9)
	(supports instrument24 thermograph7)
	(calibration_target instrument24 star2)
	(supports instrument25 image6)
	(supports instrument25 thermograph3)
	(supports instrument25 spectrograph9)
	(calibration_target instrument25 star3)
	(supports instrument26 image8)
	(supports instrument26 spectrograph9)
	(calibration_target instrument26 star0)
	(supports instrument27 thermograph3)
	(calibration_target instrument27 star0)
	(supports instrument28 thermograph2)
	(supports instrument28 thermograph4)
	(supports instrument28 infrared5)
	(calibration_target instrument28 groundstation1)
	(supports instrument29 thermograph4)
	(supports instrument29 spectrograph9)
	(calibration_target instrument29 groundstation1)
	(supports instrument30 thermograph4)
	(supports instrument30 image1)
	(calibration_target instrument30 star2)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(power_avail satellite4)
	(pointing satellite4 groundstation1)
)
(:goal (and
	(pointing satellite3 star17)
	(pointing satellite4 phenomenon22)
	(have_image phenomenon5 thermograph0)
	(have_image phenomenon5 spectrograph9)
	(have_image phenomenon5 infrared5)
	(have_image planet7 thermograph0)
	(have_image planet7 image6)
	(have_image planet7 spectrograph9)
	(have_image planet8 thermograph2)
	(have_image planet8 spectrograph9)
	(have_image planet8 image1)
	(have_image star9 thermograph4)
	(have_image planet10 image8)
	(have_image planet10 thermograph2)
	(have_image planet11 image6)
	(have_image planet11 thermograph4)
	(have_image phenomenon13 infrared5)
	(have_image phenomenon13 thermograph3)
	(have_image phenomenon13 spectrograph9)
	(have_image phenomenon14 spectrograph9)
	(have_image planet15 thermograph4)
	(have_image phenomenon16 image1)
	(have_image phenomenon16 thermograph3)
	(have_image phenomenon16 image6)
	(have_image star17 thermograph3)
	(have_image star17 infrared5)
	(have_image star17 thermograph4)
	(have_image phenomenon18 thermograph0)
	(have_image phenomenon18 spectrograph9)
	(have_image phenomenon19 thermograph0)
	(have_image phenomenon19 thermograph2)
	(have_image star20 thermograph4)
	(have_image star21 thermograph3)
	(have_image phenomenon22 image8)
	(have_image star23 infrared5)
	(have_image star23 image6)
	(have_image star24 image1)
	(have_image star24 thermograph4)
	(have_image star24 thermograph2)
))

)
