(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	satellite4 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	image6 - mode
	thermograph7 - mode
	thermograph4 - mode
	infrared5 - mode
	image8 - mode
	thermograph3 - mode
	thermograph2 - mode
	spectrograph9 - mode
	image1 - mode
	thermograph0 - mode
	groundstation1 - direction
	star0 - direction
	star2 - direction
	groundstation4 - direction
	star3 - direction
	phenomenon5 - direction
	planet6 - direction
	planet7 - direction
	planet8 - direction
	star9 - direction
	planet10 - direction
	planet11 - direction
	star12 - direction
	phenomenon13 - direction
	phenomenon14 - direction
	planet15 - direction
	phenomenon16 - direction
	star17 - direction
	phenomenon18 - direction
	phenomenon19 - direction
	star20 - direction
	star21 - direction
	phenomenon22 - direction
	star23 - direction
	star24 - direction
)
(:init
	(supports instrument0 thermograph2)
	(supports instrument0 thermograph7)
	(supports instrument0 image6)
	(calibration_target instrument0 star3)
	(supports instrument1 spectrograph9)
	(calibration_target instrument1 star0)
	(supports instrument2 thermograph4)
	(supports instrument2 infrared5)
	(calibration_target instrument2 groundstation1)
	(supports instrument3 thermograph2)
	(supports instrument3 thermograph0)
	(supports instrument3 infrared5)
	(calibration_target instrument3 groundstation4)
	(supports instrument4 image1)
	(supports instrument4 thermograph4)
	(calibration_target instrument4 groundstation4)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 star17)
	(supports instrument5 thermograph7)
	(supports instrument5 image8)
	(calibration_target instrument5 star0)
	(supports instrument6 image8)
	(calibration_target instrument6 star3)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 phenomenon18)
	(supports instrument7 image8)
	(calibration_target instrument7 star2)
	(supports instrument8 image8)
	(calibration_target instrument8 star3)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 star3)
	(supports instrument9 infrared5)
	(supports instrument9 thermograph0)
	(supports instrument9 thermograph4)
	(calibration_target instrument9 star2)
	(on_board instrument9 satellite3)
	(power_avail satellite3)
	(pointing satellite3 phenomenon22)
	(supports instrument10 image8)
	(calibration_target instrument10 groundstation4)
	(supports instrument11 thermograph2)
	(supports instrument11 thermograph3)
	(calibration_target instrument11 groundstation4)
	(supports instrument12 thermograph0)
	(supports instrument12 image1)
	(supports instrument12 spectrograph9)
	(calibration_target instrument12 star3)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(on_board instrument12 satellite4)
	(power_avail satellite4)
	(pointing satellite4 planet15)
)
(:goal (and
	(pointing satellite1 phenomenon14)
	(pointing satellite3 phenomenon13)
	(pointing satellite4 groundstation4)
	(have_image phenomenon5 thermograph0)
	(have_image phenomenon5 spectrograph9)
	(have_image phenomenon5 infrared5)
	(have_image planet7 thermograph0)
	(have_image planet7 image6)
	(have_image planet7 spectrograph9)
	(have_image planet8 thermograph2)
	(have_image planet8 spectrograph9)
	(have_image planet8 image1)
	(have_image star9 thermograph4)
	(have_image planet10 image8)
	(have_image planet10 thermograph2)
	(have_image planet11 image6)
	(have_image planet11 thermograph4)
	(have_image phenomenon13 infrared5)
	(have_image phenomenon13 thermograph3)
	(have_image phenomenon13 spectrograph9)
	(have_image phenomenon14 spectrograph9)
	(have_image planet15 thermograph4)
	(have_image phenomenon16 image1)
	(have_image phenomenon16 thermograph3)
	(have_image phenomenon16 image6)
	(have_image star17 thermograph3)
	(have_image star17 infrared5)
	(have_image star17 thermograph4)
	(have_image phenomenon18 thermograph0)
	(have_image phenomenon18 spectrograph9)
	(have_image phenomenon19 thermograph0)
	(have_image phenomenon19 thermograph2)
	(have_image star20 thermograph4)
	(have_image star21 thermograph3)
	(have_image phenomenon22 image8)
	(have_image star23 infrared5)
	(have_image star23 image6)
	(have_image star24 image1)
	(have_image star24 thermograph4)
	(have_image star24 thermograph2)
))

)
