(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite1 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite2 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite3 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite4 - satellite
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	thermograph3 - mode
	image1 - mode
	thermograph4 - mode
	thermograph0 - mode
	thermograph2 - mode
	star0 - direction
	star1 - direction
	star4 - direction
	star3 - direction
	groundstation2 - direction
	phenomenon5 - direction
	planet6 - direction
	planet7 - direction
	star8 - direction
	star9 - direction
	star10 - direction
	planet11 - direction
	phenomenon12 - direction
	phenomenon13 - direction
	planet14 - direction
	star15 - direction
	phenomenon16 - direction
	phenomenon17 - direction
	phenomenon18 - direction
	planet19 - direction
	planet20 - direction
	phenomenon21 - direction
	star22 - direction
	planet23 - direction
	phenomenon24 - direction
)
(:init
	(supports instrument0 thermograph4)
	(supports instrument0 thermograph0)
	(supports instrument0 thermograph2)
	(calibration_target instrument0 star4)
	(supports instrument1 thermograph3)
	(calibration_target instrument1 star0)
	(supports instrument2 image1)
	(calibration_target instrument2 star4)
	(supports instrument3 image1)
	(supports instrument3 thermograph0)
	(supports instrument3 thermograph3)
	(calibration_target instrument3 star3)
	(supports instrument4 thermograph0)
	(calibration_target instrument4 star1)
	(supports instrument5 image1)
	(calibration_target instrument5 star1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(power_avail satellite0)
	(pointing satellite0 star8)
	(supports instrument6 thermograph3)
	(calibration_target instrument6 star0)
	(supports instrument7 thermograph4)
	(calibration_target instrument7 groundstation2)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(power_avail satellite1)
	(pointing satellite1 phenomenon18)
	(supports instrument8 thermograph2)
	(supports instrument8 thermograph0)
	(supports instrument8 thermograph3)
	(calibration_target instrument8 groundstation2)
	(supports instrument9 thermograph3)
	(supports instrument9 thermograph0)
	(calibration_target instrument9 star1)
	(supports instrument10 thermograph2)
	(supports instrument10 thermograph3)
	(supports instrument10 image1)
	(calibration_target instrument10 star3)
	(supports instrument11 thermograph2)
	(calibration_target instrument11 star1)
	(supports instrument12 thermograph2)
	(supports instrument12 image1)
	(supports instrument12 thermograph0)
	(calibration_target instrument12 star3)
	(supports instrument13 image1)
	(supports instrument13 thermograph4)
	(calibration_target instrument13 groundstation2)
	(supports instrument14 thermograph3)
	(calibration_target instrument14 groundstation2)
	(supports instrument15 image1)
	(calibration_target instrument15 star4)
	(supports instrument16 thermograph4)
	(calibration_target instrument16 star0)
	(supports instrument17 thermograph4)
	(supports instrument17 thermograph0)
	(calibration_target instrument17 star4)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(power_avail satellite2)
	(pointing satellite2 star1)
	(supports instrument18 thermograph4)
	(supports instrument18 thermograph0)
	(calibration_target instrument18 star1)
	(supports instrument19 thermograph0)
	(supports instrument19 thermograph4)
	(calibration_target instrument19 star3)
	(supports instrument20 thermograph2)
	(calibration_target instrument20 star4)
	(supports instrument21 thermograph3)
	(supports instrument21 thermograph4)
	(calibration_target instrument21 star3)
	(supports instrument22 thermograph4)
	(supports instrument22 thermograph0)
	(supports instrument22 thermograph2)
	(calibration_target instrument22 star0)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 star0)
	(supports instrument24 thermograph2)
	(supports instrument24 thermograph3)
	(calibration_target instrument24 star1)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(power_avail satellite3)
	(pointing satellite3 star3)
	(supports instrument25 thermograph0)
	(calibration_target instrument25 groundstation2)
	(supports instrument26 thermograph0)
	(calibration_target instrument26 star1)
	(supports instrument27 thermograph0)
	(calibration_target instrument27 star4)
	(supports instrument28 thermograph0)
	(calibration_target instrument28 star1)
	(supports instrument29 thermograph0)
	(supports instrument29 thermograph3)
	(supports instrument29 thermograph4)
	(calibration_target instrument29 star1)
	(supports instrument30 thermograph2)
	(supports instrument30 thermograph4)
	(supports instrument30 thermograph3)
	(calibration_target instrument30 star4)
	(supports instrument31 thermograph3)
	(supports instrument31 image1)
	(calibration_target instrument31 star3)
	(supports instrument32 thermograph4)
	(supports instrument32 image1)
	(calibration_target instrument32 groundstation2)
	(supports instrument33 thermograph2)
	(supports instrument33 thermograph0)
	(calibration_target instrument33 groundstation2)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(power_avail satellite4)
	(pointing satellite4 planet7)
)
(:goal (and
	(have_image phenomenon5 thermograph4)
	(have_image planet7 image1)
	(have_image star8 thermograph3)
	(have_image star9 image1)
	(have_image star10 image1)
	(have_image phenomenon13 thermograph2)
	(have_image star15 thermograph2)
	(have_image phenomenon17 thermograph4)
	(have_image phenomenon18 image1)
	(have_image planet19 thermograph2)
	(have_image planet20 thermograph4)
	(have_image phenomenon21 image1)
	(have_image star22 thermograph3)
))

)
