(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite2 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite3 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite4 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	image1 - mode
	thermograph4 - mode
	thermograph2 - mode
	thermograph0 - mode
	thermograph3 - mode
	star0 - direction
	star4 - direction
	groundstation2 - direction
	star3 - direction
	star1 - direction
	phenomenon5 - direction
	planet6 - direction
	planet7 - direction
	star8 - direction
	star9 - direction
	star10 - direction
	planet11 - direction
	phenomenon12 - direction
	phenomenon13 - direction
	planet14 - direction
	star15 - direction
	phenomenon16 - direction
	phenomenon17 - direction
	phenomenon18 - direction
	planet19 - direction
	planet20 - direction
	phenomenon21 - direction
	star22 - direction
	planet23 - direction
	phenomenon24 - direction
)
(:init
	(supports instrument0 thermograph4)
	(supports instrument0 thermograph0)
	(supports instrument0 thermograph2)
	(calibration_target instrument0 star4)
	(supports instrument1 thermograph3)
	(calibration_target instrument1 star0)
	(supports instrument2 image1)
	(calibration_target instrument2 star4)
	(supports instrument3 image1)
	(supports instrument3 thermograph0)
	(supports instrument3 thermograph3)
	(calibration_target instrument3 star3)
	(supports instrument4 thermograph0)
	(calibration_target instrument4 star1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 star8)
	(supports instrument5 thermograph4)
	(supports instrument5 thermograph0)
	(calibration_target instrument5 groundstation2)
	(supports instrument6 thermograph3)
	(supports instrument6 thermograph2)
	(calibration_target instrument6 star0)
	(supports instrument7 image1)
	(supports instrument7 thermograph2)
	(calibration_target instrument7 star1)
	(supports instrument8 thermograph2)
	(supports instrument8 thermograph3)
	(supports instrument8 image1)
	(calibration_target instrument8 star4)
	(supports instrument9 thermograph0)
	(supports instrument9 thermograph2)
	(calibration_target instrument9 groundstation2)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(power_avail satellite1)
	(pointing satellite1 star3)
	(supports instrument10 thermograph2)
	(calibration_target instrument10 star0)
	(supports instrument11 image1)
	(supports instrument11 thermograph0)
	(supports instrument11 thermograph2)
	(calibration_target instrument11 star0)
	(supports instrument12 thermograph2)
	(supports instrument12 thermograph0)
	(calibration_target instrument12 star4)
	(supports instrument13 thermograph0)
	(calibration_target instrument13 star3)
	(supports instrument14 thermograph2)
	(calibration_target instrument14 star4)
	(supports instrument15 thermograph3)
	(supports instrument15 thermograph4)
	(supports instrument15 thermograph2)
	(calibration_target instrument15 star0)
	(supports instrument16 thermograph0)
	(calibration_target instrument16 star0)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(power_avail satellite2)
	(pointing satellite2 planet19)
	(supports instrument17 thermograph2)
	(supports instrument17 thermograph3)
	(supports instrument17 thermograph4)
	(calibration_target instrument17 star0)
	(supports instrument18 thermograph4)
	(calibration_target instrument18 star4)
	(supports instrument19 image1)
	(calibration_target instrument19 star1)
	(supports instrument20 thermograph2)
	(supports instrument20 thermograph3)
	(calibration_target instrument20 groundstation2)
	(supports instrument21 thermograph3)
	(supports instrument21 thermograph0)
	(supports instrument21 thermograph2)
	(calibration_target instrument21 star0)
	(on_board instrument17 satellite3)
	(on_board instrument18 satellite3)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(power_avail satellite3)
	(pointing satellite3 planet20)
	(supports instrument22 thermograph2)
	(supports instrument22 image1)
	(supports instrument22 thermograph4)
	(calibration_target instrument22 star4)
	(supports instrument23 thermograph0)
	(calibration_target instrument23 groundstation2)
	(supports instrument24 thermograph0)
	(calibration_target instrument24 star1)
	(supports instrument25 thermograph0)
	(calibration_target instrument25 star1)
	(supports instrument26 thermograph3)
	(supports instrument26 thermograph4)
	(supports instrument26 thermograph0)
	(calibration_target instrument26 star3)
	(supports instrument27 thermograph3)
	(calibration_target instrument27 star1)
	(supports instrument28 thermograph3)
	(supports instrument28 thermograph0)
	(supports instrument28 thermograph2)
	(calibration_target instrument28 star1)
	(on_board instrument22 satellite4)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(power_avail satellite4)
	(pointing satellite4 star10)
)
(:goal (and
	(pointing satellite3 planet7)
	(have_image phenomenon5 thermograph4)
	(have_image planet7 image1)
	(have_image star8 thermograph3)
	(have_image star9 image1)
	(have_image star10 image1)
	(have_image phenomenon13 thermograph2)
	(have_image star15 thermograph2)
	(have_image phenomenon17 thermograph4)
	(have_image phenomenon18 image1)
	(have_image planet19 thermograph2)
	(have_image planet20 thermograph4)
	(have_image phenomenon21 image1)
	(have_image star22 thermograph3)
))

)
