(define (problem depotprob4470) (:domain depot)
(:objects
	depot0 depot1 depot2 - depot
	distributor0 distributor1 distributor2 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist)
(:init
	(at pallet0 depot0)
	(clear pallet0)
	(at pallet1 depot1)
	(clear crate11)
	(at pallet2 depot2)
	(clear pallet2)
	(at pallet3 distributor0)
	(clear crate12)
	(at pallet4 distributor1)
	(clear crate10)
	(at pallet5 distributor2)
	(clear crate8)
	(at pallet6 depot1)
	(clear pallet6)
	(at pallet7 distributor1)
	(clear pallet7)
	(at pallet8 distributor0)
	(clear crate6)
	(at pallet9 distributor1)
	(clear crate9)
	(at truck0 depot2)
	(at truck1 distributor2)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 distributor2)
	(available hoist5)
	(at crate0 distributor0)
	(on crate0 pallet8)
	(at crate1 distributor1)
	(on crate1 pallet9)
	(at crate2 distributor1)
	(on crate2 pallet4)
	(at crate3 distributor1)
	(on crate3 crate1)
	(at crate4 distributor1)
	(on crate4 crate3)
	(at crate5 distributor1)
	(on crate5 crate2)
	(at crate6 distributor0)
	(on crate6 crate0)
	(at crate7 distributor1)
	(on crate7 crate4)
	(at crate8 distributor2)
	(on crate8 pallet5)
	(at crate9 distributor1)
	(on crate9 crate7)
	(at crate10 distributor1)
	(on crate10 crate5)
	(at crate11 depot1)
	(on crate11 pallet1)
	(at crate12 distributor0)
	(on crate12 pallet3)
)

(:goal (and
		(on crate0 crate6)
		(on crate1 pallet7)
		(on crate2 pallet5)
		(on crate3 crate1)
		(on crate4 crate2)
		(on crate5 pallet8)
		(on crate6 crate4)
		(on crate7 pallet9)
		(on crate8 pallet4)
		(on crate9 pallet2)
		(on crate10 crate3)
		(on crate11 crate8)
		(on crate12 crate9)
	)
))
