(define (problem depotprob3647) (:domain depot)
(:objects
	depot0 - depot
	distributor0 distributor1 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 - crate
	hoist0 hoist1 hoist2 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate10)
	(at pallet1 distributor0)
	(clear crate9)
	(at pallet2 distributor1)
	(clear crate7)
	(at truck0 depot0)
	(at truck1 depot0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 distributor0)
	(available hoist1)
	(at hoist2 distributor1)
	(available hoist2)
	(at crate0 distributor1)
	(on crate0 pallet2)
	(at crate1 depot0)
	(on crate1 pallet0)
	(at crate2 distributor0)
	(on crate2 pallet1)
	(at crate3 distributor1)
	(on crate3 crate0)
	(at crate4 depot0)
	(on crate4 crate1)
	(at crate5 distributor0)
	(on crate5 crate2)
	(at crate6 depot0)
	(on crate6 crate4)
	(at crate7 distributor1)
	(on crate7 crate3)
	(at crate8 distributor0)
	(on crate8 crate5)
	(at crate9 distributor0)
	(on crate9 crate8)
	(at crate10 depot0)
	(on crate10 crate6)
)

(:goal (and
		(on crate1 crate5)
		(on crate3 crate9)
		(on crate4 pallet1)
		(on crate5 crate6)
		(on crate6 pallet2)
		(on crate7 crate3)
		(on crate8 crate4)
		(on crate9 pallet0)
		(on crate10 crate7)
	)
))
