(define (problem depotprob4443) (:domain depot)
(:objects
	depot0 - depot
	distributor0 distributor1 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 - crate
	hoist0 hoist1 hoist2 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate0)
	(at pallet1 distributor0)
	(clear crate13)
	(at pallet2 distributor1)
	(clear crate8)
	(at pallet3 depot0)
	(clear crate11)
	(at pallet4 distributor1)
	(clear crate12)
	(at pallet5 distributor0)
	(clear crate9)
	(at truck0 depot0)
	(at truck1 depot0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 distributor0)
	(available hoist1)
	(at hoist2 distributor1)
	(available hoist2)
	(at crate0 depot0)
	(on crate0 pallet0)
	(at crate1 distributor1)
	(on crate1 pallet2)
	(at crate2 distributor0)
	(on crate2 pallet1)
	(at crate3 depot0)
	(on crate3 pallet3)
	(at crate4 depot0)
	(on crate4 crate3)
	(at crate5 distributor1)
	(on crate5 crate1)
	(at crate6 distributor0)
	(on crate6 crate2)
	(at crate7 distributor1)
	(on crate7 pallet4)
	(at crate8 distributor1)
	(on crate8 crate5)
	(at crate9 distributor0)
	(on crate9 pallet5)
	(at crate10 depot0)
	(on crate10 crate4)
	(at crate11 depot0)
	(on crate11 crate10)
	(at crate12 distributor1)
	(on crate12 crate7)
	(at crate13 distributor0)
	(on crate13 crate6)
)

(:goal (and
		(on crate1 pallet3)
		(on crate2 crate11)
		(on crate3 pallet4)
		(on crate4 pallet2)
		(on crate5 crate8)
		(on crate6 crate4)
		(on crate8 pallet0)
		(on crate9 crate1)
		(on crate10 pallet5)
		(on crate11 crate12)
		(on crate12 pallet1)
		(on crate13 crate9)
	)
))
