(define (problem depotprob5689) (:domain depot)
(:objects
	depot0 depot1 depot2 - depot
	distributor0 distributor1 distributor2 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate10)
	(at pallet1 depot1)
	(clear crate1)
	(at pallet2 depot2)
	(clear pallet2)
	(at pallet3 distributor0)
	(clear crate6)
	(at pallet4 distributor1)
	(clear pallet4)
	(at pallet5 distributor2)
	(clear pallet5)
	(at pallet6 distributor2)
	(clear crate3)
	(at pallet7 depot0)
	(clear crate8)
	(at pallet8 depot1)
	(clear pallet8)
	(at pallet9 distributor0)
	(clear crate9)
	(at truck0 depot1)
	(at truck1 depot0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 distributor2)
	(available hoist5)
	(at crate0 depot1)
	(on crate0 pallet1)
	(at crate1 depot1)
	(on crate1 crate0)
	(at crate2 distributor0)
	(on crate2 pallet9)
	(at crate3 distributor2)
	(on crate3 pallet6)
	(at crate4 depot0)
	(on crate4 pallet0)
	(at crate5 distributor0)
	(on crate5 pallet3)
	(at crate6 distributor0)
	(on crate6 crate5)
	(at crate7 depot0)
	(on crate7 crate4)
	(at crate8 depot0)
	(on crate8 pallet7)
	(at crate9 distributor0)
	(on crate9 crate2)
	(at crate10 depot0)
	(on crate10 crate7)
)

(:goal (and
		(on crate0 pallet7)
		(on crate1 pallet2)
		(on crate2 pallet8)
		(on crate3 crate4)
		(on crate4 pallet9)
		(on crate5 pallet3)
		(on crate6 pallet0)
		(on crate7 crate9)
		(on crate9 crate6)
		(on crate10 crate0)
	)
))
