(define (problem depotprob3695) (:domain depot)
(:objects
	depot0 - depot
	distributor0 distributor1 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 - crate
	hoist0 hoist1 hoist2 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate0)
	(at pallet1 distributor0)
	(clear crate6)
	(at pallet2 distributor1)
	(clear crate9)
	(at truck0 distributor0)
	(at truck1 distributor1)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 distributor0)
	(available hoist1)
	(at hoist2 distributor1)
	(available hoist2)
	(at crate0 depot0)
	(on crate0 pallet0)
	(at crate1 distributor1)
	(on crate1 pallet2)
	(at crate2 distributor1)
	(on crate2 crate1)
	(at crate3 distributor0)
	(on crate3 pallet1)
	(at crate4 distributor1)
	(on crate4 crate2)
	(at crate5 distributor1)
	(on crate5 crate4)
	(at crate6 distributor0)
	(on crate6 crate3)
	(at crate7 distributor1)
	(on crate7 crate5)
	(at crate8 distributor1)
	(on crate8 crate7)
	(at crate9 distributor1)
	(on crate9 crate8)
)

(:goal (and
		(on crate0 pallet0)
		(on crate1 crate0)
		(on crate2 crate7)
		(on crate3 crate2)
		(on crate4 crate6)
		(on crate5 crate4)
		(on crate6 pallet1)
		(on crate7 crate1)
		(on crate8 crate3)
	)
))
