(define (problem depotprob4605) (:domain depot)
(:objects
	depot0 - depot
	distributor0 distributor1 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 - crate
	hoist0 hoist1 hoist2 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate11)
	(at pallet1 distributor0)
	(clear crate8)
	(at pallet2 distributor1)
	(clear crate3)
	(at pallet3 distributor1)
	(clear crate9)
	(at pallet4 depot0)
	(clear crate1)
	(at pallet5 depot0)
	(clear crate12)
	(at truck0 distributor1)
	(at truck1 distributor0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 distributor0)
	(available hoist1)
	(at hoist2 distributor1)
	(available hoist2)
	(at crate0 distributor1)
	(on crate0 pallet3)
	(at crate1 depot0)
	(on crate1 pallet4)
	(at crate2 depot0)
	(on crate2 pallet0)
	(at crate3 distributor1)
	(on crate3 pallet2)
	(at crate4 distributor0)
	(on crate4 pallet1)
	(at crate5 distributor0)
	(on crate5 crate4)
	(at crate6 distributor0)
	(on crate6 crate5)
	(at crate7 distributor1)
	(on crate7 crate0)
	(at crate8 distributor0)
	(on crate8 crate6)
	(at crate9 distributor1)
	(on crate9 crate7)
	(at crate10 depot0)
	(on crate10 pallet5)
	(at crate11 depot0)
	(on crate11 crate2)
	(at crate12 depot0)
	(on crate12 crate10)
)

(:goal (and
		(on crate0 pallet0)
		(on crate2 crate8)
		(on crate3 pallet1)
		(on crate4 crate0)
		(on crate5 crate7)
		(on crate7 crate11)
		(on crate8 pallet4)
		(on crate9 crate5)
		(on crate10 pallet2)
		(on crate11 pallet5)
		(on crate12 crate10)
	)
))
