(define (problem depotprob5405) (:domain depot)
(:objects
	depot0 - depot
	distributor0 distributor1 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 - crate
	hoist0 hoist1 hoist2 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate8)
	(at pallet1 distributor0)
	(clear crate9)
	(at pallet2 distributor1)
	(clear crate11)
	(at truck0 distributor0)
	(at truck1 distributor0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 distributor0)
	(available hoist1)
	(at hoist2 distributor1)
	(available hoist2)
	(at crate0 distributor0)
	(on crate0 pallet1)
	(at crate1 distributor0)
	(on crate1 crate0)
	(at crate2 distributor0)
	(on crate2 crate1)
	(at crate3 depot0)
	(on crate3 pallet0)
	(at crate4 distributor1)
	(on crate4 pallet2)
	(at crate5 depot0)
	(on crate5 crate3)
	(at crate6 depot0)
	(on crate6 crate5)
	(at crate7 distributor1)
	(on crate7 crate4)
	(at crate8 depot0)
	(on crate8 crate6)
	(at crate9 distributor0)
	(on crate9 crate2)
	(at crate10 distributor1)
	(on crate10 crate7)
	(at crate11 distributor1)
	(on crate11 crate10)
)

(:goal (and
		(on crate0 pallet1)
		(on crate1 crate4)
		(on crate2 pallet0)
		(on crate3 crate1)
		(on crate4 crate8)
		(on crate5 pallet2)
		(on crate6 crate2)
		(on crate7 crate10)
		(on crate8 crate9)
		(on crate9 crate5)
		(on crate10 crate6)
	)
))
