(define (problem depotprob5904) (:domain depot)
(:objects
	depot0 depot1 depot2 - depot
	distributor0 distributor1 distributor2 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate3)
	(at pallet1 depot1)
	(clear pallet1)
	(at pallet2 depot2)
	(clear crate7)
	(at pallet3 distributor0)
	(clear crate8)
	(at pallet4 distributor1)
	(clear pallet4)
	(at pallet5 distributor2)
	(clear crate0)
	(at pallet6 distributor2)
	(clear crate5)
	(at pallet7 depot1)
	(clear pallet7)
	(at pallet8 distributor2)
	(clear crate10)
	(at pallet9 depot1)
	(clear crate4)
	(at truck0 distributor1)
	(at truck1 distributor2)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 distributor2)
	(available hoist5)
	(at crate0 distributor2)
	(on crate0 pallet5)
	(at crate1 depot1)
	(on crate1 pallet9)
	(at crate2 distributor0)
	(on crate2 pallet3)
	(at crate3 depot0)
	(on crate3 pallet0)
	(at crate4 depot1)
	(on crate4 crate1)
	(at crate5 distributor2)
	(on crate5 pallet6)
	(at crate6 distributor0)
	(on crate6 crate2)
	(at crate7 depot2)
	(on crate7 pallet2)
	(at crate8 distributor0)
	(on crate8 crate6)
	(at crate9 distributor2)
	(on crate9 pallet8)
	(at crate10 distributor2)
	(on crate10 crate9)
)

(:goal (and
		(on crate0 crate10)
		(on crate1 pallet9)
		(on crate2 crate8)
		(on crate3 crate6)
		(on crate4 crate1)
		(on crate5 crate9)
		(on crate6 pallet5)
		(on crate7 pallet6)
		(on crate8 pallet1)
		(on crate9 pallet4)
		(on crate10 pallet0)
	)
))
