(define (problem depotprob3792) (:domain depot)
(:objects
	depot0 - depot
	distributor0 distributor1 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 - crate
	hoist0 hoist1 hoist2 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate6)
	(at pallet1 distributor0)
	(clear crate11)
	(at pallet2 distributor1)
	(clear crate10)
	(at pallet3 distributor0)
	(clear crate12)
	(at pallet4 depot0)
	(clear crate9)
	(at pallet5 depot0)
	(clear pallet5)
	(at truck0 depot0)
	(at truck1 distributor1)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 distributor0)
	(available hoist1)
	(at hoist2 distributor1)
	(available hoist2)
	(at crate0 depot0)
	(on crate0 pallet4)
	(at crate1 depot0)
	(on crate1 crate0)
	(at crate2 depot0)
	(on crate2 pallet0)
	(at crate3 distributor0)
	(on crate3 pallet3)
	(at crate4 distributor0)
	(on crate4 crate3)
	(at crate5 distributor0)
	(on crate5 crate4)
	(at crate6 depot0)
	(on crate6 crate2)
	(at crate7 distributor0)
	(on crate7 crate5)
	(at crate8 depot0)
	(on crate8 crate1)
	(at crate9 depot0)
	(on crate9 crate8)
	(at crate10 distributor1)
	(on crate10 pallet2)
	(at crate11 distributor0)
	(on crate11 pallet1)
	(at crate12 distributor0)
	(on crate12 crate7)
)

(:goal (and
		(on crate0 pallet1)
		(on crate1 crate8)
		(on crate3 pallet2)
		(on crate4 crate6)
		(on crate5 crate3)
		(on crate6 crate0)
		(on crate7 crate9)
		(on crate8 crate10)
		(on crate9 crate11)
		(on crate10 pallet0)
		(on crate11 crate5)
		(on crate12 pallet4)
	)
))
