(define (problem depotprob3252) (:domain depot)
(:objects
	depot0 depot1 depot2 - depot
	distributor0 distributor1 distributor2 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist)
(:init
	(at pallet0 depot0)
	(clear pallet0)
	(at pallet1 depot1)
	(clear crate2)
	(at pallet2 depot2)
	(clear pallet2)
	(at pallet3 distributor0)
	(clear crate9)
	(at pallet4 distributor1)
	(clear pallet4)
	(at pallet5 distributor2)
	(clear crate8)
	(at pallet6 distributor2)
	(clear crate5)
	(at pallet7 depot1)
	(clear crate6)
	(at pallet8 depot2)
	(clear crate4)
	(at pallet9 distributor2)
	(clear crate7)
	(at truck0 distributor1)
	(at truck1 depot0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 distributor2)
	(available hoist5)
	(at crate0 distributor2)
	(on crate0 pallet9)
	(at crate1 distributor2)
	(on crate1 pallet5)
	(at crate2 depot1)
	(on crate2 pallet1)
	(at crate3 distributor2)
	(on crate3 crate1)
	(at crate4 depot2)
	(on crate4 pallet8)
	(at crate5 distributor2)
	(on crate5 pallet6)
	(at crate6 depot1)
	(on crate6 pallet7)
	(at crate7 distributor2)
	(on crate7 crate0)
	(at crate8 distributor2)
	(on crate8 crate3)
	(at crate9 distributor0)
	(on crate9 pallet3)
)

(:goal (and
		(on crate0 pallet8)
		(on crate1 crate8)
		(on crate2 pallet3)
		(on crate3 pallet1)
		(on crate4 pallet5)
		(on crate5 pallet6)
		(on crate6 pallet7)
		(on crate7 pallet9)
		(on crate8 crate6)
		(on crate9 crate2)
	)
))
