(define (problem depotprob5294) (:domain depot)
(:objects
	depot0 - depot
	distributor0 distributor1 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 - crate
	hoist0 hoist1 hoist2 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate9)
	(at pallet1 distributor0)
	(clear crate6)
	(at pallet2 distributor1)
	(clear pallet2)
	(at pallet3 depot0)
	(clear pallet3)
	(at pallet4 distributor1)
	(clear crate8)
	(at pallet5 depot0)
	(clear crate7)
	(at truck0 distributor1)
	(at truck1 distributor0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 distributor0)
	(available hoist1)
	(at hoist2 distributor1)
	(available hoist2)
	(at crate0 depot0)
	(on crate0 pallet5)
	(at crate1 distributor1)
	(on crate1 pallet4)
	(at crate2 depot0)
	(on crate2 crate0)
	(at crate3 distributor1)
	(on crate3 crate1)
	(at crate4 depot0)
	(on crate4 pallet0)
	(at crate5 depot0)
	(on crate5 crate4)
	(at crate6 distributor0)
	(on crate6 pallet1)
	(at crate7 depot0)
	(on crate7 crate2)
	(at crate8 distributor1)
	(on crate8 crate3)
	(at crate9 depot0)
	(on crate9 crate5)
)

(:goal (and
		(on crate0 pallet1)
		(on crate1 pallet2)
		(on crate2 crate0)
		(on crate3 crate1)
		(on crate4 crate2)
		(on crate5 pallet5)
		(on crate6 pallet0)
		(on crate7 pallet4)
		(on crate8 crate7)
		(on crate9 crate4)
	)
))
