(define (problem depotprob6553) (:domain depot)
(:objects
	depot0 depot1 depot2 - depot
	distributor0 distributor1 distributor2 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 crate14 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate7)
	(at pallet1 depot1)
	(clear crate8)
	(at pallet2 depot2)
	(clear crate10)
	(at pallet3 distributor0)
	(clear crate0)
	(at pallet4 distributor1)
	(clear crate6)
	(at pallet5 distributor2)
	(clear crate13)
	(at pallet6 distributor1)
	(clear crate14)
	(at pallet7 distributor1)
	(clear pallet7)
	(at pallet8 distributor1)
	(clear pallet8)
	(at pallet9 distributor0)
	(clear crate12)
	(at truck0 distributor2)
	(at truck1 distributor1)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 distributor2)
	(available hoist5)
	(at crate0 distributor0)
	(on crate0 pallet3)
	(at crate1 distributor2)
	(on crate1 pallet5)
	(at crate2 distributor2)
	(on crate2 crate1)
	(at crate3 distributor1)
	(on crate3 pallet4)
	(at crate4 distributor2)
	(on crate4 crate2)
	(at crate5 depot1)
	(on crate5 pallet1)
	(at crate6 distributor1)
	(on crate6 crate3)
	(at crate7 depot0)
	(on crate7 pallet0)
	(at crate8 depot1)
	(on crate8 crate5)
	(at crate9 distributor0)
	(on crate9 pallet9)
	(at crate10 depot2)
	(on crate10 pallet2)
	(at crate11 distributor1)
	(on crate11 pallet6)
	(at crate12 distributor0)
	(on crate12 crate9)
	(at crate13 distributor2)
	(on crate13 crate4)
	(at crate14 distributor1)
	(on crate14 crate11)
)

(:goal (and
		(on crate0 pallet4)
		(on crate1 pallet2)
		(on crate2 crate10)
		(on crate3 crate9)
		(on crate4 pallet5)
		(on crate7 crate14)
		(on crate8 crate7)
		(on crate9 pallet8)
		(on crate10 pallet6)
		(on crate11 crate1)
		(on crate12 pallet3)
		(on crate14 pallet1)
	)
))
