(define (problem depotprob2314) (:domain depot)
(:objects
	depot0 - depot
	distributor0 distributor1 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 - crate
	hoist0 hoist1 hoist2 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate4)
	(at pallet1 distributor0)
	(clear crate0)
	(at pallet2 distributor1)
	(clear crate1)
	(at pallet3 distributor0)
	(clear crate6)
	(at pallet4 depot0)
	(clear crate3)
	(at pallet5 distributor0)
	(clear pallet5)
	(at truck0 distributor1)
	(at truck1 depot0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 distributor0)
	(available hoist1)
	(at hoist2 distributor1)
	(available hoist2)
	(at crate0 distributor0)
	(on crate0 pallet1)
	(at crate1 distributor1)
	(on crate1 pallet2)
	(at crate2 depot0)
	(on crate2 pallet0)
	(at crate3 depot0)
	(on crate3 pallet4)
	(at crate4 depot0)
	(on crate4 crate2)
	(at crate5 distributor0)
	(on crate5 pallet3)
	(at crate6 distributor0)
	(on crate6 crate5)
)

(:goal (and
		(on crate0 crate4)
		(on crate1 pallet2)
		(on crate2 crate1)
		(on crate3 pallet4)
		(on crate4 crate6)
		(on crate5 pallet1)
		(on crate6 pallet0)
	)
))
