(define (problem depotprob3293) (:domain depot)
(:objects
	depot0 depot1 depot2 - depot
	distributor0 distributor1 distributor2 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate8)
	(at pallet1 depot1)
	(clear crate11)
	(at pallet2 depot2)
	(clear crate7)
	(at pallet3 distributor0)
	(clear crate2)
	(at pallet4 distributor1)
	(clear crate10)
	(at pallet5 distributor2)
	(clear pallet5)
	(at pallet6 depot0)
	(clear crate9)
	(at pallet7 depot0)
	(clear crate6)
	(at pallet8 depot2)
	(clear pallet8)
	(at pallet9 distributor2)
	(clear pallet9)
	(at truck0 depot2)
	(at truck1 distributor2)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 distributor2)
	(available hoist5)
	(at crate0 depot1)
	(on crate0 pallet1)
	(at crate1 depot0)
	(on crate1 pallet7)
	(at crate2 distributor0)
	(on crate2 pallet3)
	(at crate3 depot0)
	(on crate3 pallet0)
	(at crate4 depot0)
	(on crate4 pallet6)
	(at crate5 depot0)
	(on crate5 crate4)
	(at crate6 depot0)
	(on crate6 crate1)
	(at crate7 depot2)
	(on crate7 pallet2)
	(at crate8 depot0)
	(on crate8 crate3)
	(at crate9 depot0)
	(on crate9 crate5)
	(at crate10 distributor1)
	(on crate10 pallet4)
	(at crate11 depot1)
	(on crate11 crate0)
)

(:goal (and
		(on crate0 crate3)
		(on crate1 pallet1)
		(on crate2 pallet9)
		(on crate3 crate7)
		(on crate4 pallet8)
		(on crate5 pallet5)
		(on crate6 pallet4)
		(on crate7 crate5)
		(on crate8 pallet0)
		(on crate9 crate10)
		(on crate10 crate6)
		(on crate11 pallet7)
	)
))
