(define (problem depotprob4911) (:domain depot)
(:objects
	depot0 - depot
	distributor0 distributor1 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 - crate
	hoist0 hoist1 hoist2 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate8)
	(at pallet1 distributor0)
	(clear crate9)
	(at pallet2 distributor1)
	(clear crate4)
	(at pallet3 distributor1)
	(clear crate6)
	(at pallet4 depot0)
	(clear crate5)
	(at pallet5 depot0)
	(clear crate2)
	(at truck0 distributor1)
	(at truck1 distributor1)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 distributor0)
	(available hoist1)
	(at hoist2 distributor1)
	(available hoist2)
	(at crate0 depot0)
	(on crate0 pallet5)
	(at crate1 distributor0)
	(on crate1 pallet1)
	(at crate2 depot0)
	(on crate2 crate0)
	(at crate3 distributor1)
	(on crate3 pallet2)
	(at crate4 distributor1)
	(on crate4 crate3)
	(at crate5 depot0)
	(on crate5 pallet4)
	(at crate6 distributor1)
	(on crate6 pallet3)
	(at crate7 distributor0)
	(on crate7 crate1)
	(at crate8 depot0)
	(on crate8 pallet0)
	(at crate9 distributor0)
	(on crate9 crate7)
)

(:goal (and
		(on crate0 crate3)
		(on crate1 pallet4)
		(on crate3 pallet5)
		(on crate4 pallet2)
		(on crate5 crate6)
		(on crate6 crate4)
		(on crate8 crate1)
		(on crate9 pallet0)
	)
))
