(define (problem depotprob4671) (:domain depot)
(:objects
	depot0 depot1 depot2 - depot
	distributor0 distributor1 distributor2 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist)
(:init
	(at pallet0 depot0)
	(clear pallet0)
	(at pallet1 depot1)
	(clear crate0)
	(at pallet2 depot2)
	(clear crate9)
	(at pallet3 distributor0)
	(clear crate8)
	(at pallet4 distributor1)
	(clear crate7)
	(at pallet5 distributor2)
	(clear crate6)
	(at pallet6 depot0)
	(clear crate4)
	(at pallet7 depot1)
	(clear pallet7)
	(at pallet8 depot2)
	(clear pallet8)
	(at pallet9 depot0)
	(clear pallet9)
	(at truck0 depot2)
	(at truck1 distributor2)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 distributor2)
	(available hoist5)
	(at crate0 depot1)
	(on crate0 pallet1)
	(at crate1 depot0)
	(on crate1 pallet6)
	(at crate2 distributor0)
	(on crate2 pallet3)
	(at crate3 distributor0)
	(on crate3 crate2)
	(at crate4 depot0)
	(on crate4 crate1)
	(at crate5 depot2)
	(on crate5 pallet2)
	(at crate6 distributor2)
	(on crate6 pallet5)
	(at crate7 distributor1)
	(on crate7 pallet4)
	(at crate8 distributor0)
	(on crate8 crate3)
	(at crate9 depot2)
	(on crate9 crate5)
)

(:goal (and
		(on crate0 pallet6)
		(on crate1 crate6)
		(on crate2 pallet8)
		(on crate3 crate4)
		(on crate4 crate5)
		(on crate5 pallet0)
		(on crate6 pallet2)
		(on crate7 pallet5)
		(on crate8 crate2)
	)
))
