(define (problem depotprob6665) (:domain depot)
(:objects
	depot0 depot1 depot2 - depot
	distributor0 distributor1 distributor2 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist)
(:init
	(at pallet0 depot0)
	(clear pallet0)
	(at pallet1 depot1)
	(clear pallet1)
	(at pallet2 depot2)
	(clear pallet2)
	(at pallet3 distributor0)
	(clear crate2)
	(at pallet4 distributor1)
	(clear crate4)
	(at pallet5 distributor2)
	(clear pallet5)
	(at pallet6 depot1)
	(clear crate7)
	(at pallet7 distributor1)
	(clear crate0)
	(at pallet8 distributor1)
	(clear crate6)
	(at pallet9 depot1)
	(clear crate5)
	(at truck0 depot0)
	(at truck1 depot0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 distributor2)
	(available hoist5)
	(at crate0 distributor1)
	(on crate0 pallet7)
	(at crate1 depot1)
	(on crate1 pallet6)
	(at crate2 distributor0)
	(on crate2 pallet3)
	(at crate3 depot1)
	(on crate3 pallet9)
	(at crate4 distributor1)
	(on crate4 pallet4)
	(at crate5 depot1)
	(on crate5 crate3)
	(at crate6 distributor1)
	(on crate6 pallet8)
	(at crate7 depot1)
	(on crate7 crate1)
)

(:goal (and
		(on crate0 pallet6)
		(on crate1 pallet0)
		(on crate2 pallet9)
		(on crate3 pallet4)
		(on crate4 crate1)
		(on crate5 pallet2)
		(on crate6 pallet5)
	)
))
