(define (problem depotprob3568) (:domain depot)
(:objects
	depot0 - depot
	distributor0 distributor1 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 - crate
	hoist0 hoist1 hoist2 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate1)
	(at pallet1 distributor0)
	(clear crate3)
	(at pallet2 distributor1)
	(clear pallet2)
	(at pallet3 distributor0)
	(clear pallet3)
	(at pallet4 distributor0)
	(clear crate4)
	(at pallet5 distributor0)
	(clear crate7)
	(at truck0 distributor0)
	(at truck1 distributor0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 distributor0)
	(available hoist1)
	(at hoist2 distributor1)
	(available hoist2)
	(at crate0 distributor0)
	(on crate0 pallet5)
	(at crate1 depot0)
	(on crate1 pallet0)
	(at crate2 distributor0)
	(on crate2 pallet4)
	(at crate3 distributor0)
	(on crate3 pallet1)
	(at crate4 distributor0)
	(on crate4 crate2)
	(at crate5 distributor0)
	(on crate5 crate0)
	(at crate6 distributor0)
	(on crate6 crate5)
	(at crate7 distributor0)
	(on crate7 crate6)
)

(:goal (and
		(on crate0 pallet2)
		(on crate1 pallet3)
		(on crate2 pallet5)
		(on crate3 pallet0)
		(on crate4 pallet1)
		(on crate5 crate7)
		(on crate7 crate2)
	)
))
