(define (problem depotprob3701) (:domain depot)
(:objects
	depot0 - depot
	distributor0 distributor1 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 - crate
	hoist0 hoist1 hoist2 - hoist)
(:init
	(at pallet0 depot0)
	(clear pallet0)
	(at pallet1 distributor0)
	(clear crate9)
	(at pallet2 distributor1)
	(clear crate11)
	(at pallet3 depot0)
	(clear crate5)
	(at pallet4 distributor1)
	(clear crate10)
	(at pallet5 distributor0)
	(clear crate4)
	(at truck0 distributor0)
	(at truck1 distributor1)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 distributor0)
	(available hoist1)
	(at hoist2 distributor1)
	(available hoist2)
	(at crate0 distributor1)
	(on crate0 pallet4)
	(at crate1 depot0)
	(on crate1 pallet3)
	(at crate2 distributor1)
	(on crate2 pallet2)
	(at crate3 distributor1)
	(on crate3 crate2)
	(at crate4 distributor0)
	(on crate4 pallet5)
	(at crate5 depot0)
	(on crate5 crate1)
	(at crate6 distributor1)
	(on crate6 crate0)
	(at crate7 distributor1)
	(on crate7 crate6)
	(at crate8 distributor0)
	(on crate8 pallet1)
	(at crate9 distributor0)
	(on crate9 crate8)
	(at crate10 distributor1)
	(on crate10 crate7)
	(at crate11 distributor1)
	(on crate11 crate3)
)

(:goal (and
		(on crate0 pallet2)
		(on crate1 pallet5)
		(on crate2 pallet3)
		(on crate3 pallet1)
		(on crate4 crate10)
		(on crate5 crate3)
		(on crate7 pallet4)
		(on crate8 crate7)
		(on crate10 crate2)
		(on crate11 crate0)
	)
))
