(define (problem depotprob4687) (:domain depot)
(:objects
	depot0 - depot
	distributor0 distributor1 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 - crate
	hoist0 hoist1 hoist2 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate11)
	(at pallet1 distributor0)
	(clear crate10)
	(at pallet2 distributor1)
	(clear pallet2)
	(at pallet3 distributor1)
	(clear crate12)
	(at pallet4 distributor0)
	(clear crate8)
	(at pallet5 distributor1)
	(clear pallet5)
	(at truck0 depot0)
	(at truck1 distributor1)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 distributor0)
	(available hoist1)
	(at hoist2 distributor1)
	(available hoist2)
	(at crate0 depot0)
	(on crate0 pallet0)
	(at crate1 distributor0)
	(on crate1 pallet4)
	(at crate2 distributor1)
	(on crate2 pallet3)
	(at crate3 distributor1)
	(on crate3 crate2)
	(at crate4 distributor0)
	(on crate4 crate1)
	(at crate5 distributor0)
	(on crate5 pallet1)
	(at crate6 depot0)
	(on crate6 crate0)
	(at crate7 distributor0)
	(on crate7 crate5)
	(at crate8 distributor0)
	(on crate8 crate4)
	(at crate9 distributor0)
	(on crate9 crate7)
	(at crate10 distributor0)
	(on crate10 crate9)
	(at crate11 depot0)
	(on crate11 crate6)
	(at crate12 distributor1)
	(on crate12 crate3)
)

(:goal (and
		(on crate0 crate4)
		(on crate1 pallet1)
		(on crate2 crate8)
		(on crate4 pallet4)
		(on crate5 pallet0)
		(on crate6 pallet3)
		(on crate7 crate6)
		(on crate8 crate0)
		(on crate10 pallet2)
		(on crate11 crate10)
		(on crate12 crate1)
	)
))
