(define (problem depotprob6551) (:domain depot)
(:objects
	depot0 depot1 depot2 - depot
	distributor0 distributor1 distributor2 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist)
(:init
	(at pallet0 depot0)
	(clear pallet0)
	(at pallet1 depot1)
	(clear crate7)
	(at pallet2 depot2)
	(clear crate12)
	(at pallet3 distributor0)
	(clear pallet3)
	(at pallet4 distributor1)
	(clear crate10)
	(at pallet5 distributor2)
	(clear crate13)
	(at pallet6 depot1)
	(clear crate8)
	(at pallet7 distributor0)
	(clear pallet7)
	(at pallet8 depot0)
	(clear crate5)
	(at pallet9 depot2)
	(clear crate11)
	(at truck0 depot0)
	(at truck1 depot2)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 distributor2)
	(available hoist5)
	(at crate0 depot1)
	(on crate0 pallet1)
	(at crate1 depot1)
	(on crate1 crate0)
	(at crate2 depot1)
	(on crate2 pallet6)
	(at crate3 distributor1)
	(on crate3 pallet4)
	(at crate4 depot1)
	(on crate4 crate2)
	(at crate5 depot0)
	(on crate5 pallet8)
	(at crate6 depot1)
	(on crate6 crate1)
	(at crate7 depot1)
	(on crate7 crate6)
	(at crate8 depot1)
	(on crate8 crate4)
	(at crate9 distributor1)
	(on crate9 crate3)
	(at crate10 distributor1)
	(on crate10 crate9)
	(at crate11 depot2)
	(on crate11 pallet9)
	(at crate12 depot2)
	(on crate12 pallet2)
	(at crate13 distributor2)
	(on crate13 pallet5)
)

(:goal (and
		(on crate0 crate1)
		(on crate1 pallet3)
		(on crate2 pallet4)
		(on crate4 pallet5)
		(on crate6 pallet2)
		(on crate7 pallet6)
		(on crate8 crate6)
		(on crate9 crate13)
		(on crate10 pallet7)
		(on crate11 pallet9)
		(on crate13 pallet8)
	)
))
