(define (problem depotprob6884) (:domain depot)
(:objects
	depot0 depot1 depot2 - depot
	distributor0 distributor1 distributor2 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate4)
	(at pallet1 depot1)
	(clear crate11)
	(at pallet2 depot2)
	(clear crate2)
	(at pallet3 distributor0)
	(clear crate8)
	(at pallet4 distributor1)
	(clear crate9)
	(at pallet5 distributor2)
	(clear crate5)
	(at pallet6 distributor0)
	(clear crate12)
	(at pallet7 depot0)
	(clear crate10)
	(at pallet8 depot2)
	(clear crate3)
	(at pallet9 depot2)
	(clear crate7)
	(at truck0 depot0)
	(at truck1 depot0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 distributor2)
	(available hoist5)
	(at crate0 depot0)
	(on crate0 pallet7)
	(at crate1 depot2)
	(on crate1 pallet2)
	(at crate2 depot2)
	(on crate2 crate1)
	(at crate3 depot2)
	(on crate3 pallet8)
	(at crate4 depot0)
	(on crate4 pallet0)
	(at crate5 distributor2)
	(on crate5 pallet5)
	(at crate6 depot0)
	(on crate6 crate0)
	(at crate7 depot2)
	(on crate7 pallet9)
	(at crate8 distributor0)
	(on crate8 pallet3)
	(at crate9 distributor1)
	(on crate9 pallet4)
	(at crate10 depot0)
	(on crate10 crate6)
	(at crate11 depot1)
	(on crate11 pallet1)
	(at crate12 distributor0)
	(on crate12 pallet6)
)

(:goal (and
		(on crate0 crate10)
		(on crate1 crate3)
		(on crate2 crate12)
		(on crate3 pallet3)
		(on crate4 pallet5)
		(on crate5 pallet2)
		(on crate6 pallet9)
		(on crate8 pallet4)
		(on crate9 pallet7)
		(on crate10 crate9)
		(on crate11 crate1)
		(on crate12 pallet8)
	)
))
