(define (problem depotprob4775) (:domain depot)
(:objects
	depot0 depot1 depot2 - depot
	distributor0 distributor1 distributor2 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate8)
	(at pallet1 depot1)
	(clear pallet1)
	(at pallet2 depot2)
	(clear crate3)
	(at pallet3 distributor0)
	(clear crate13)
	(at pallet4 distributor1)
	(clear crate12)
	(at pallet5 distributor2)
	(clear pallet5)
	(at pallet6 depot0)
	(clear crate0)
	(at pallet7 distributor0)
	(clear crate4)
	(at pallet8 distributor0)
	(clear crate10)
	(at pallet9 distributor1)
	(clear crate6)
	(at truck0 distributor0)
	(at truck1 distributor1)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 distributor2)
	(available hoist5)
	(at crate0 depot0)
	(on crate0 pallet6)
	(at crate1 distributor0)
	(on crate1 pallet7)
	(at crate2 depot2)
	(on crate2 pallet2)
	(at crate3 depot2)
	(on crate3 crate2)
	(at crate4 distributor0)
	(on crate4 crate1)
	(at crate5 depot0)
	(on crate5 pallet0)
	(at crate6 distributor1)
	(on crate6 pallet9)
	(at crate7 distributor0)
	(on crate7 pallet8)
	(at crate8 depot0)
	(on crate8 crate5)
	(at crate9 distributor1)
	(on crate9 pallet4)
	(at crate10 distributor0)
	(on crate10 crate7)
	(at crate11 distributor0)
	(on crate11 pallet3)
	(at crate12 distributor1)
	(on crate12 crate9)
	(at crate13 distributor0)
	(on crate13 crate11)
)

(:goal (and
		(on crate0 pallet0)
		(on crate1 crate6)
		(on crate2 pallet2)
		(on crate3 pallet3)
		(on crate4 crate5)
		(on crate5 crate13)
		(on crate6 crate7)
		(on crate7 pallet4)
		(on crate8 pallet6)
		(on crate9 crate0)
		(on crate10 crate3)
		(on crate11 crate10)
		(on crate12 pallet1)
		(on crate13 pallet8)
	)
))
