(define (problem depotprob6421) (:domain depot)
(:objects
	depot0 depot1 depot2 - depot
	distributor0 distributor1 distributor2 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate4)
	(at pallet1 depot1)
	(clear pallet1)
	(at pallet2 depot2)
	(clear crate3)
	(at pallet3 distributor0)
	(clear pallet3)
	(at pallet4 distributor1)
	(clear crate7)
	(at pallet5 distributor2)
	(clear pallet5)
	(at pallet6 distributor0)
	(clear crate2)
	(at pallet7 distributor0)
	(clear crate9)
	(at pallet8 distributor0)
	(clear crate5)
	(at pallet9 distributor1)
	(clear pallet9)
	(at truck0 distributor2)
	(at truck1 depot2)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 distributor2)
	(available hoist5)
	(at crate0 distributor0)
	(on crate0 pallet8)
	(at crate1 depot0)
	(on crate1 pallet0)
	(at crate2 distributor0)
	(on crate2 pallet6)
	(at crate3 depot2)
	(on crate3 pallet2)
	(at crate4 depot0)
	(on crate4 crate1)
	(at crate5 distributor0)
	(on crate5 crate0)
	(at crate6 distributor0)
	(on crate6 pallet7)
	(at crate7 distributor1)
	(on crate7 pallet4)
	(at crate8 distributor0)
	(on crate8 crate6)
	(at crate9 distributor0)
	(on crate9 crate8)
)

(:goal (and
		(on crate0 pallet9)
		(on crate1 crate4)
		(on crate2 pallet7)
		(on crate3 pallet5)
		(on crate4 pallet0)
		(on crate5 pallet3)
		(on crate6 crate5)
		(on crate7 pallet1)
	)
))
