(define (problem depotprob7638) (:domain depot)
(:objects
	depot0 depot1 depot2 - depot
	distributor0 distributor1 distributor2 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate10)
	(at pallet1 depot1)
	(clear crate9)
	(at pallet2 depot2)
	(clear crate7)
	(at pallet3 distributor0)
	(clear crate11)
	(at pallet4 distributor1)
	(clear pallet4)
	(at pallet5 distributor2)
	(clear pallet5)
	(at pallet6 distributor1)
	(clear crate5)
	(at pallet7 depot2)
	(clear crate13)
	(at pallet8 distributor2)
	(clear pallet8)
	(at pallet9 depot1)
	(clear crate8)
	(at truck0 depot0)
	(at truck1 distributor2)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 distributor2)
	(available hoist5)
	(at crate0 depot2)
	(on crate0 pallet2)
	(at crate1 depot2)
	(on crate1 crate0)
	(at crate2 depot2)
	(on crate2 crate1)
	(at crate3 depot1)
	(on crate3 pallet9)
	(at crate4 depot1)
	(on crate4 pallet1)
	(at crate5 distributor1)
	(on crate5 pallet6)
	(at crate6 depot1)
	(on crate6 crate4)
	(at crate7 depot2)
	(on crate7 crate2)
	(at crate8 depot1)
	(on crate8 crate3)
	(at crate9 depot1)
	(on crate9 crate6)
	(at crate10 depot0)
	(on crate10 pallet0)
	(at crate11 distributor0)
	(on crate11 pallet3)
	(at crate12 depot2)
	(on crate12 pallet7)
	(at crate13 depot2)
	(on crate13 crate12)
)

(:goal (and
		(on crate0 crate1)
		(on crate1 pallet7)
		(on crate3 crate8)
		(on crate6 pallet9)
		(on crate7 pallet5)
		(on crate8 crate10)
		(on crate9 crate11)
		(on crate10 pallet6)
		(on crate11 pallet4)
		(on crate12 pallet8)
		(on crate13 pallet3)
	)
))
