(define (problem depotprob2974) (:domain depot)
(:objects
	depot0 depot1 depot2 - depot
	distributor0 distributor1 distributor2 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate10)
	(at pallet1 depot1)
	(clear crate2)
	(at pallet2 depot2)
	(clear crate8)
	(at pallet3 distributor0)
	(clear pallet3)
	(at pallet4 distributor1)
	(clear pallet4)
	(at pallet5 distributor2)
	(clear pallet5)
	(at pallet6 distributor0)
	(clear crate12)
	(at pallet7 depot0)
	(clear crate11)
	(at pallet8 distributor1)
	(clear crate4)
	(at pallet9 distributor0)
	(clear crate5)
	(at truck0 depot2)
	(at truck1 distributor2)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 distributor2)
	(available hoist5)
	(at crate0 distributor0)
	(on crate0 pallet9)
	(at crate1 depot1)
	(on crate1 pallet1)
	(at crate2 depot1)
	(on crate2 crate1)
	(at crate3 depot0)
	(on crate3 pallet0)
	(at crate4 distributor1)
	(on crate4 pallet8)
	(at crate5 distributor0)
	(on crate5 crate0)
	(at crate6 depot0)
	(on crate6 pallet7)
	(at crate7 depot0)
	(on crate7 crate3)
	(at crate8 depot2)
	(on crate8 pallet2)
	(at crate9 depot0)
	(on crate9 crate7)
	(at crate10 depot0)
	(on crate10 crate9)
	(at crate11 depot0)
	(on crate11 crate6)
	(at crate12 distributor0)
	(on crate12 pallet6)
)

(:goal (and
		(on crate1 pallet6)
		(on crate3 pallet4)
		(on crate4 crate8)
		(on crate6 crate3)
		(on crate7 crate12)
		(on crate8 pallet8)
		(on crate9 crate10)
		(on crate10 pallet0)
		(on crate11 pallet7)
		(on crate12 pallet5)
	)
))
