(define (problem depotprob4254) (:domain depot)
(:objects
	depot0 - depot
	distributor0 distributor1 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 - crate
	hoist0 hoist1 hoist2 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate10)
	(at pallet1 distributor0)
	(clear crate9)
	(at pallet2 distributor1)
	(clear crate11)
	(at pallet3 depot0)
	(clear pallet3)
	(at pallet4 distributor1)
	(clear crate13)
	(at pallet5 distributor0)
	(clear crate12)
	(at truck0 depot0)
	(at truck1 depot0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 distributor0)
	(available hoist1)
	(at hoist2 distributor1)
	(available hoist2)
	(at crate0 depot0)
	(on crate0 pallet0)
	(at crate1 distributor1)
	(on crate1 pallet2)
	(at crate2 distributor0)
	(on crate2 pallet5)
	(at crate3 distributor0)
	(on crate3 pallet1)
	(at crate4 distributor0)
	(on crate4 crate3)
	(at crate5 distributor1)
	(on crate5 pallet4)
	(at crate6 distributor0)
	(on crate6 crate4)
	(at crate7 distributor0)
	(on crate7 crate2)
	(at crate8 distributor0)
	(on crate8 crate6)
	(at crate9 distributor0)
	(on crate9 crate8)
	(at crate10 depot0)
	(on crate10 crate0)
	(at crate11 distributor1)
	(on crate11 crate1)
	(at crate12 distributor0)
	(on crate12 crate7)
	(at crate13 distributor1)
	(on crate13 crate5)
)

(:goal (and
		(on crate1 crate7)
		(on crate2 crate9)
		(on crate3 pallet1)
		(on crate4 pallet3)
		(on crate5 pallet2)
		(on crate6 pallet0)
		(on crate7 crate2)
		(on crate8 pallet4)
		(on crate9 crate4)
		(on crate11 pallet5)
		(on crate12 crate8)
		(on crate13 crate3)
	)
))
