(define (problem depotprob4125) (:domain depot)
(:objects
	depot0 depot1 depot2 - depot
	distributor0 distributor1 distributor2 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate8)
	(at pallet1 depot1)
	(clear crate2)
	(at pallet2 depot2)
	(clear crate13)
	(at pallet3 distributor0)
	(clear pallet3)
	(at pallet4 distributor1)
	(clear crate7)
	(at pallet5 distributor2)
	(clear crate12)
	(at pallet6 distributor1)
	(clear crate6)
	(at pallet7 distributor2)
	(clear crate4)
	(at pallet8 distributor0)
	(clear crate10)
	(at pallet9 distributor2)
	(clear crate3)
	(at truck0 depot0)
	(at truck1 distributor1)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 distributor2)
	(available hoist5)
	(at crate0 distributor2)
	(on crate0 pallet7)
	(at crate1 distributor2)
	(on crate1 crate0)
	(at crate2 depot1)
	(on crate2 pallet1)
	(at crate3 distributor2)
	(on crate3 pallet9)
	(at crate4 distributor2)
	(on crate4 crate1)
	(at crate5 depot0)
	(on crate5 pallet0)
	(at crate6 distributor1)
	(on crate6 pallet6)
	(at crate7 distributor1)
	(on crate7 pallet4)
	(at crate8 depot0)
	(on crate8 crate5)
	(at crate9 depot2)
	(on crate9 pallet2)
	(at crate10 distributor0)
	(on crate10 pallet8)
	(at crate11 depot2)
	(on crate11 crate9)
	(at crate12 distributor2)
	(on crate12 pallet5)
	(at crate13 depot2)
	(on crate13 crate11)
)

(:goal (and
		(on crate1 pallet9)
		(on crate2 crate10)
		(on crate4 crate12)
		(on crate5 pallet8)
		(on crate6 crate4)
		(on crate7 crate9)
		(on crate8 pallet0)
		(on crate9 pallet3)
		(on crate10 crate1)
		(on crate11 pallet5)
		(on crate12 pallet6)
		(on crate13 pallet7)
	)
))
