(define (problem depotprob2321) (:domain depot)
(:objects
	depot0 - depot
	distributor0 distributor1 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 - crate
	hoist0 hoist1 hoist2 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate11)
	(at pallet1 distributor0)
	(clear crate2)
	(at pallet2 distributor1)
	(clear crate7)
	(at pallet3 depot0)
	(clear crate3)
	(at pallet4 distributor0)
	(clear crate10)
	(at pallet5 distributor1)
	(clear crate8)
	(at truck0 distributor1)
	(at truck1 distributor1)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 distributor0)
	(available hoist1)
	(at hoist2 distributor1)
	(available hoist2)
	(at crate0 distributor1)
	(on crate0 pallet2)
	(at crate1 distributor0)
	(on crate1 pallet4)
	(at crate2 distributor0)
	(on crate2 pallet1)
	(at crate3 depot0)
	(on crate3 pallet3)
	(at crate4 depot0)
	(on crate4 pallet0)
	(at crate5 distributor0)
	(on crate5 crate1)
	(at crate6 depot0)
	(on crate6 crate4)
	(at crate7 distributor1)
	(on crate7 crate0)
	(at crate8 distributor1)
	(on crate8 pallet5)
	(at crate9 distributor0)
	(on crate9 crate5)
	(at crate10 distributor0)
	(on crate10 crate9)
	(at crate11 depot0)
	(on crate11 crate6)
)

(:goal (and
		(on crate1 pallet2)
		(on crate2 pallet5)
		(on crate4 pallet0)
		(on crate5 crate9)
		(on crate7 crate5)
		(on crate8 pallet1)
		(on crate9 pallet3)
		(on crate11 crate4)
	)
))
