(define (problem depotprob3252) (:domain depot)
(:objects
	depot0 depot1 depot2 - depot
	distributor0 distributor1 distributor2 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 crate14 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist)
(:init
	(at pallet0 depot0)
	(clear pallet0)
	(at pallet1 depot1)
	(clear crate11)
	(at pallet2 depot2)
	(clear pallet2)
	(at pallet3 distributor0)
	(clear crate9)
	(at pallet4 distributor1)
	(clear pallet4)
	(at pallet5 distributor2)
	(clear crate13)
	(at pallet6 distributor2)
	(clear crate12)
	(at pallet7 depot1)
	(clear crate14)
	(at pallet8 depot2)
	(clear crate4)
	(at pallet9 distributor2)
	(clear crate7)
	(at truck0 distributor1)
	(at truck1 depot0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 distributor2)
	(available hoist5)
	(at crate0 distributor2)
	(on crate0 pallet9)
	(at crate1 distributor2)
	(on crate1 pallet5)
	(at crate2 depot1)
	(on crate2 pallet1)
	(at crate3 distributor2)
	(on crate3 crate1)
	(at crate4 depot2)
	(on crate4 pallet8)
	(at crate5 distributor2)
	(on crate5 pallet6)
	(at crate6 depot1)
	(on crate6 pallet7)
	(at crate7 distributor2)
	(on crate7 crate0)
	(at crate8 distributor2)
	(on crate8 crate3)
	(at crate9 distributor0)
	(on crate9 pallet3)
	(at crate10 depot1)
	(on crate10 crate6)
	(at crate11 depot1)
	(on crate11 crate2)
	(at crate12 distributor2)
	(on crate12 crate5)
	(at crate13 distributor2)
	(on crate13 crate8)
	(at crate14 depot1)
	(on crate14 crate10)
)

(:goal (and
		(on crate0 pallet1)
		(on crate1 pallet8)
		(on crate2 pallet7)
		(on crate3 crate7)
		(on crate4 pallet3)
		(on crate5 crate1)
		(on crate6 crate3)
		(on crate7 pallet6)
		(on crate9 pallet2)
		(on crate10 pallet9)
		(on crate11 crate9)
		(on crate12 crate10)
		(on crate14 crate4)
	)
))
