(define (problem depotprob4325) (:domain depot)
(:objects
	depot0 - depot
	distributor0 distributor1 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 crate14 - crate
	hoist0 hoist1 hoist2 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate14)
	(at pallet1 distributor0)
	(clear crate12)
	(at pallet2 distributor1)
	(clear pallet2)
	(at pallet3 distributor0)
	(clear crate9)
	(at pallet4 distributor1)
	(clear pallet4)
	(at pallet5 distributor0)
	(clear crate13)
	(at truck0 distributor1)
	(at truck1 distributor0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 distributor0)
	(available hoist1)
	(at hoist2 distributor1)
	(available hoist2)
	(at crate0 distributor0)
	(on crate0 pallet3)
	(at crate1 depot0)
	(on crate1 pallet0)
	(at crate2 distributor0)
	(on crate2 pallet5)
	(at crate3 distributor0)
	(on crate3 crate2)
	(at crate4 distributor0)
	(on crate4 crate0)
	(at crate5 depot0)
	(on crate5 crate1)
	(at crate6 depot0)
	(on crate6 crate5)
	(at crate7 distributor0)
	(on crate7 crate4)
	(at crate8 distributor0)
	(on crate8 crate3)
	(at crate9 distributor0)
	(on crate9 crate7)
	(at crate10 distributor0)
	(on crate10 pallet1)
	(at crate11 distributor0)
	(on crate11 crate8)
	(at crate12 distributor0)
	(on crate12 crate10)
	(at crate13 distributor0)
	(on crate13 crate11)
	(at crate14 depot0)
	(on crate14 crate6)
)

(:goal (and
		(on crate0 crate13)
		(on crate1 crate5)
		(on crate2 pallet2)
		(on crate3 pallet0)
		(on crate4 pallet3)
		(on crate5 pallet1)
		(on crate6 crate2)
		(on crate7 crate11)
		(on crate8 crate7)
		(on crate9 crate10)
		(on crate10 pallet4)
		(on crate11 crate9)
		(on crate13 pallet5)
		(on crate14 crate4)
	)
))
