(define (problem depotprob5010) (:domain depot)
(:objects
	depot0 - depot
	distributor0 distributor1 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 - crate
	hoist0 hoist1 hoist2 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate4)
	(at pallet1 distributor0)
	(clear crate10)
	(at pallet2 distributor1)
	(clear crate12)
	(at truck0 depot0)
	(at truck1 distributor0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 distributor0)
	(available hoist1)
	(at hoist2 distributor1)
	(available hoist2)
	(at crate0 depot0)
	(on crate0 pallet0)
	(at crate1 depot0)
	(on crate1 crate0)
	(at crate2 distributor0)
	(on crate2 pallet1)
	(at crate3 distributor0)
	(on crate3 crate2)
	(at crate4 depot0)
	(on crate4 crate1)
	(at crate5 distributor0)
	(on crate5 crate3)
	(at crate6 distributor1)
	(on crate6 pallet2)
	(at crate7 distributor1)
	(on crate7 crate6)
	(at crate8 distributor0)
	(on crate8 crate5)
	(at crate9 distributor0)
	(on crate9 crate8)
	(at crate10 distributor0)
	(on crate10 crate9)
	(at crate11 distributor1)
	(on crate11 crate7)
	(at crate12 distributor1)
	(on crate12 crate11)
)

(:goal (and
		(on crate0 crate10)
		(on crate1 pallet1)
		(on crate2 crate1)
		(on crate3 crate11)
		(on crate4 crate0)
		(on crate5 crate6)
		(on crate6 crate2)
		(on crate7 pallet2)
		(on crate8 pallet0)
		(on crate9 crate12)
		(on crate10 crate9)
		(on crate11 crate4)
		(on crate12 crate8)
	)
))
