(define (problem depotprob4317) (:domain depot)
(:objects
	depot0 depot1 depot2 - depot
	distributor0 distributor1 distributor2 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate2)
	(at pallet1 depot1)
	(clear crate5)
	(at pallet2 depot2)
	(clear crate7)
	(at pallet3 distributor0)
	(clear pallet3)
	(at pallet4 distributor1)
	(clear crate6)
	(at pallet5 distributor2)
	(clear pallet5)
	(at pallet6 depot0)
	(clear pallet6)
	(at pallet7 depot1)
	(clear pallet7)
	(at pallet8 depot0)
	(clear pallet8)
	(at pallet9 depot1)
	(clear crate4)
	(at truck0 distributor2)
	(at truck1 distributor1)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 distributor2)
	(available hoist5)
	(at crate0 depot1)
	(on crate0 pallet9)
	(at crate1 depot1)
	(on crate1 crate0)
	(at crate2 depot0)
	(on crate2 pallet0)
	(at crate3 depot1)
	(on crate3 pallet1)
	(at crate4 depot1)
	(on crate4 crate1)
	(at crate5 depot1)
	(on crate5 crate3)
	(at crate6 distributor1)
	(on crate6 pallet4)
	(at crate7 depot2)
	(on crate7 pallet2)
)

(:goal (and
		(on crate0 crate4)
		(on crate1 pallet2)
		(on crate2 pallet5)
		(on crate3 pallet0)
		(on crate4 pallet4)
		(on crate5 crate2)
		(on crate6 pallet7)
		(on crate7 pallet6)
	)
))
