
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain satellite)
    (:requirements )
    (:types
        object
    )

    (:constants
        
    )

    (:predicates
        (pointing_object_satellite1_object_planet7 )
        (supports_object_instrument6_object_infrared0 )
        (pointing_object_satellite0_object_planet7 )
        (have_image_object_star10_object_spectrograph3 )
        (have_image_object_phenomenon12_object_spectrograph3 )
        (have_image_object_planet13_object_spectrograph3 )
        (pointing_object_satellite1_object_phenomenon12 )
        (pointing_object_satellite4_object_planet5 )
        (power_on_object_instrument5 )
        (pointing_object_satellite2_object_phenomenon18 )
        (supports_object_instrument0_object_thermograph4 )
        (have_image_object_star8_object_infrared0 )
        (have_image_object_star1_object_thermograph4 )
        (have_image_object_star1_object_image2 )
        (pointing_object_satellite0_object_star3 )
        (pointing_object_satellite2_object_phenomenon12 )
        (have_image_object_star6_object_infrared0 )
        (direction_object_star9 )
        (supports_object_instrument9_object_infrared0 )
        (have_image_object_star0_object_thermograph4 )
        (pointing_object_satellite4_object_star6 )
        (have_image_object_phenomenon11_object_thermograph4 )
        (pointing_object_satellite0_object_star0 )
        (pointing_object_satellite2_object_planet7 )
        (calibration_target_object_instrument10_object_groundstation4 )
        (pointing_object_satellite2_object_star0 )
        (power_on_object_instrument0 )
        (pointing_object_satellite2_object_star1 )
        (power_on_object_instrument1 )
        (direction_object_planet7 )
        (pointing_object_satellite3_object_phenomenon18 )
        (power_on_object_instrument6 )
        (pointing_object_satellite1_object_star1 )
        (pointing_object_satellite4_object_star3 )
        (pointing_object_satellite2_object_planet17 )
        (pointing_object_satellite2_object_groundstation4 )
        (supports_object_instrument7_object_infrared0 )
        (pointing_object_satellite4_object_star1 )
        (have_image_object_star9_object_image2 )
        (pointing_object_satellite3_object_planet16 )
        (have_image_object_phenomenon18_object_infrared0 )
        (calibrated_object_instrument4 )
        (have_image_object_star8_object_thermograph4 )
        (direction_object_planet17 )
        (direction_object_star0 )
        (have_image_object_planet13_object_thermograph4 )
        (pointing_object_satellite4_object_groundstation4 )
        (pointing_object_satellite0_object_star10 )
        (pointing_object_satellite3_object_phenomenon15 )
        (have_image_object_star3_object_thermograph4 )
        (have_image_object_phenomenon11_object_spectrograph3 )
        (pointing_object_satellite4_object_planet17 )
        (instrument_object_instrument4 )
        (direction_object_groundstation2 )
        (have_image_object_star9_object_spectrograph3 )
        (have_image_object_star0_object_thermograph1 )
        (calibration_target_object_instrument9_object_star3 )
        (mode_object_image2 )
        (power_avail_object_satellite1 )
        (supports_object_instrument2_object_thermograph1 )
        (supports_object_instrument5_object_thermograph1 )
        (have_image_object_planet7_object_spectrograph3 )
        (have_image_object_groundstation2_object_infrared0 )
        (have_image_object_star3_object_infrared0 )
        (pointing_object_satellite4_object_planet13 )
        (have_image_object_star9_object_thermograph1 )
        (have_image_object_star0_object_infrared0 )
        (pointing_object_satellite3_object_phenomenon12 )
        (calibrated_object_instrument2 )
        (direction_object_phenomenon12 )
        (calibrated_object_instrument3 )
        (calibration_target_object_instrument2_object_groundstation4 )
        (direction_object_phenomenon18 )
        (pointing_object_satellite1_object_phenomenon11 )
        (pointing_object_satellite3_object_star8 )
        (calibration_target_object_instrument5_object_groundstation4 )
        (pointing_object_satellite1_object_star9 )
        (have_image_object_star10_object_image2 )
        (direction_object_planet14 )
        (mode_object_thermograph4 )
        (pointing_object_satellite4_object_planet16 )
        (have_image_object_planet17_object_spectrograph3 )
        (have_image_object_phenomenon12_object_thermograph1 )
        (have_image_object_planet13_object_image2 )
        (have_image_object_star8_object_spectrograph3 )
        (have_image_object_star0_object_spectrograph3 )
        (have_image_object_groundstation4_object_thermograph4 )
        (pointing_object_satellite0_object_planet13 )
        (pointing_object_satellite0_object_groundstation4 )
        (pointing_object_satellite4_object_planet7 )
        (instrument_object_instrument0 )
        (have_image_object_star3_object_image2 )
        (supports_object_instrument9_object_image2 )
        (have_image_object_phenomenon11_object_image2 )
        (pointing_object_satellite2_object_star3 )
        (pointing_object_satellite3_object_star1 )
        (pointing_object_satellite1_object_phenomenon15 )
        (supports_object_instrument3_object_thermograph4 )
        (calibration_target_object_instrument7_object_star0 )
        (pointing_object_satellite4_object_star9 )
        (have_image_object_planet5_object_thermograph4 )
        (have_image_object_planet7_object_image2 )
        (instrument_object_instrument3 )
        (calibrated_object_instrument0 )
        (calibrated_object_instrument1 )
        (have_image_object_star9_object_thermograph4 )
        (pointing_object_satellite3_object_planet14 )
        (pointing_object_satellite2_object_planet14 )
        (on_board_object_instrument1_object_satellite0 )
        (have_image_object_star10_object_infrared0 )
        (pointing_object_satellite1_object_planet14 )
        (have_image_object_phenomenon15_object_infrared0 )
        (have_image_object_planet7_object_infrared0 )
        (have_image_object_groundstation2_object_spectrograph3 )
        (power_on_object_instrument4 )
        (calibration_target_object_instrument3_object_star3 )
        (pointing_object_satellite2_object_planet5 )
        (pointing_object_satellite2_object_star8 )
        (pointing_object_satellite2_object_star6 )
        (have_image_object_groundstation2_object_thermograph1 )
        (pointing_object_satellite0_object_phenomenon11 )
        (on_board_object_instrument6_object_satellite3 )
        (have_image_object_planet5_object_image2 )
        (satellite_object_satellite1 )
        (pointing_object_satellite0_object_phenomenon15 )
        (calibrated_object_instrument7 )
        (instrument_object_instrument5 )
        (power_on_object_instrument7 )
        (calibration_target_object_instrument8_object_groundstation2 )
        (direction_object_planet5 )
        (have_image_object_star6_object_spectrograph3 )
        (have_image_object_planet17_object_thermograph1 )
        (pointing_object_satellite4_object_phenomenon12 )
        (satellite_object_satellite0 )
        (have_image_object_star10_object_thermograph1 )
        (on_board_object_instrument4_object_satellite1 )
        (on_board_object_instrument8_object_satellite3 )
        (have_image_object_star1_object_infrared0 )
        (power_avail_object_satellite2 )
        (supports_object_instrument8_object_thermograph1 )
        (instrument_object_instrument10 )
        (pointing_object_satellite1_object_phenomenon18 )
        (pointing_object_satellite3_object_planet13 )
        (supports_object_instrument0_object_infrared0 )
        (pointing_object_satellite3_object_groundstation2 )
        (pointing_object_satellite2_object_planet16 )
        (supports_object_instrument10_object_image2 )
        (mode_object_spectrograph3 )
        (have_image_object_planet16_object_thermograph4 )
        (pointing_object_satellite4_object_star0 )
        (have_image_object_planet14_object_spectrograph3 )
        (pointing_object_satellite4_object_planet14 )
        (power_avail_object_satellite3 )
        (have_image_object_planet17_object_thermograph4 )
        (have_image_object_planet7_object_thermograph1 )
        (have_image_object_planet7_object_thermograph4 )
        (pointing_object_satellite0_object_groundstation2 )
        (have_image_object_star6_object_thermograph4 )
        (direction_object_star8 )
        (have_image_object_phenomenon11_object_infrared0 )
        (have_image_object_planet14_object_image2 )
        (pointing_object_satellite1_object_planet16 )
        (pointing_object_satellite2_object_star9 )
        (have_image_object_planet16_object_image2 )
        (have_image_object_phenomenon15_object_spectrograph3 )
        (have_image_object_planet16_object_infrared0 )
        (calibrated_object_instrument5 )
        (supports_object_instrument4_object_thermograph1 )
        (pointing_object_satellite0_object_planet17 )
        (instrument_object_instrument6 )
        (have_image_object_star8_object_image2 )
        (power_on_object_instrument3 )
        (pointing_object_satellite4_object_phenomenon15 )
        (mode_object_thermograph1 )
        (pointing_object_satellite3_object_planet5 )
        (have_image_object_star6_object_image2 )
        (have_image_object_phenomenon15_object_thermograph4 )
        (have_image_object_star6_object_thermograph1 )
        (have_image_object_planet13_object_thermograph1 )
        (have_image_object_groundstation4_object_infrared0 )
        (pointing_object_satellite3_object_star6 )
        (pointing_object_satellite3_object_star0 )
        (have_image_object_phenomenon12_object_infrared0 )
        (calibrated_object_instrument9 )
        (direction_object_planet16 )
        (direction_object_phenomenon15 )
        (pointing_object_satellite1_object_planet5 )
        (direction_object_star1 )
        (have_image_object_star0_object_image2 )
        (have_image_object_planet14_object_thermograph1 )
        (have_image_object_planet17_object_image2 )
        (on_board_object_instrument10_object_satellite4 )
        (pointing_object_satellite2_object_planet13 )
        (pointing_object_satellite2_object_phenomenon15 )
        (on_board_object_instrument2_object_satellite0 )
        (pointing_object_satellite3_object_planet17 )
        (pointing_object_satellite2_object_phenomenon11 )
        (power_avail_object_satellite0 )
        (pointing_object_satellite1_object_groundstation4 )
        (calibrated_object_instrument6 )
        (pointing_object_satellite0_object_star1 )
        (pointing_object_satellite0_object_star6 )
        (on_board_object_instrument3_object_satellite1 )
        (calibration_target_object_instrument6_object_groundstation2 )
        (have_image_object_star1_object_spectrograph3 )
        (have_image_object_phenomenon12_object_thermograph4 )
        (pointing_object_satellite4_object_star8 )
        (pointing_object_satellite1_object_star3 )
        (have_image_object_star8_object_thermograph1 )
        (supports_object_instrument1_object_infrared0 )
        (have_image_object_phenomenon18_object_thermograph1 )
        (pointing_object_satellite0_object_phenomenon18 )
        (on_board_object_instrument9_object_satellite4 )
        (calibrated_object_instrument10 )
        (pointing_object_satellite1_object_planet13 )
        (pointing_object_satellite2_object_groundstation2 )
        (on_board_object_instrument7_object_satellite3 )
        (have_image_object_planet16_object_spectrograph3 )
        (have_image_object_phenomenon15_object_image2 )
        (instrument_object_instrument2 )
        (pointing_object_satellite0_object_star8 )
        (direction_object_phenomenon11 )
        (mode_object_infrared0 )
        (pointing_object_satellite3_object_star9 )
        (have_image_object_groundstation4_object_thermograph1 )
        (instrument_object_instrument1 )
        (pointing_object_satellite1_object_star6 )
        (direction_object_star6 )
        (calibration_target_object_instrument0_object_star3 )
        (pointing_object_satellite4_object_star10 )
        (have_image_object_phenomenon11_object_thermograph1 )
        (pointing_object_satellite3_object_planet7 )
        (have_image_object_phenomenon18_object_thermograph4 )
        (have_image_object_phenomenon18_object_spectrograph3 )
        (have_image_object_planet16_object_thermograph1 )
        (have_image_object_groundstation2_object_image2 )
        (pointing_object_satellite0_object_star9 )
        (pointing_object_satellite0_object_phenomenon12 )
        (have_image_object_planet14_object_infrared0 )
        (have_image_object_planet5_object_spectrograph3 )
        (pointing_object_satellite3_object_star10 )
        (pointing_object_satellite1_object_star8 )
        (have_image_object_groundstation4_object_spectrograph3 )
        (pointing_object_satellite0_object_planet5 )
        (supports_object_instrument2_object_spectrograph3 )
        (have_image_object_phenomenon18_object_image2 )
        (on_board_object_instrument5_object_satellite2 )
        (instrument_object_instrument7 )
        (pointing_object_satellite1_object_star0 )
        (power_on_object_instrument2 )
        (have_image_object_planet17_object_infrared0 )
        (pointing_object_satellite0_object_planet16 )
        (satellite_object_satellite3 )
        (pointing_object_satellite3_object_phenomenon11 )
        (pointing_object_satellite4_object_groundstation2 )
        (have_image_object_star1_object_thermograph1 )
        (pointing_object_satellite4_object_phenomenon11 )
        (satellite_object_satellite4 )
        (supports_object_instrument6_object_image2 )
        (calibration_target_object_instrument4_object_star3 )
        (have_image_object_phenomenon12_object_image2 )
        (have_image_object_star9_object_infrared0 )
        (calibrated_object_instrument8 )
        (supports_object_instrument9_object_spectrograph3 )
        (power_avail_object_satellite4 )
        (have_image_object_star3_object_spectrograph3 )
        (have_image_object_star3_object_thermograph1 )
        (direction_object_groundstation4 )
        (have_image_object_planet5_object_thermograph1 )
        (instrument_object_instrument8 )
        (pointing_object_satellite0_object_planet14 )
        (direction_object_star10 )
        (power_on_object_instrument10 )
        (have_image_object_planet14_object_thermograph4 )
        (pointing_object_satellite4_object_phenomenon18 )
        (on_board_object_instrument0_object_satellite0 )
        (pointing_object_satellite3_object_groundstation4 )
        (pointing_object_satellite2_object_star10 )
        (have_image_object_groundstation2_object_thermograph4 )
        (calibration_target_object_instrument1_object_star3 )
        (direction_object_planet13 )
        (instrument_object_instrument9 )
        (power_on_object_instrument9 )
        (have_image_object_planet13_object_infrared0 )
        (have_image_object_star10_object_thermograph4 )
        (have_image_object_groundstation4_object_image2 )
        (direction_object_star3 )
        (pointing_object_satellite1_object_planet17 )
        (pointing_object_satellite1_object_star10 )
        (pointing_object_satellite3_object_star3 )
        (satellite_object_satellite2 )
        (have_image_object_phenomenon15_object_thermograph1 )
        (pointing_object_satellite1_object_groundstation2 )
        (have_image_object_planet5_object_infrared0 )
        (power_on_object_instrument8 )
    )

    (:functions
        
    )

    

    
    (:action calibrate_object_satellite0_object_instrument2_object_groundstation4
     :parameters ()
     :precondition (and (have_image_object_planet17_object_spectrograph3 ) (direction_object_phenomenon18 ) (pointing_object_satellite4_object_star0 ) (have_image_object_star9_object_image2 ))
     :effect (and
        (have_image_object_star9_object_thermograph1 )
        (pointing_object_satellite2_object_planet16 )
        (not (have_image_object_planet5_object_spectrograph3 )))
    )


    (:action turn_to_object_satellite4_object_planet17_object_planet14
     :parameters ()
     :precondition (and (direction_object_groundstation4 ) (have_image_object_phenomenon12_object_image2 ))
     :effect (and
        (satellite_object_satellite1 )
        (have_image_object_planet17_object_spectrograph3 )
        (have_image_object_planet16_object_thermograph4 )
        (pointing_object_satellite3_object_planet13 )
        (not (direction_object_planet14 )))
    )


    (:action turn_to_object_satellite4_object_star9_object_star8
     :parameters ()
     :precondition (have_image_object_planet14_object_infrared0 )
     :effect (and
        (pointing_object_satellite2_object_star8 )
        (pointing_object_satellite4_object_star6 )
        (pointing_object_satellite2_object_star9 )
        (calibration_target_object_instrument0_object_star3 )
        (not (pointing_object_satellite1_object_planet17 ))
        (not (pointing_object_satellite0_object_planet5 ))
        (not (have_image_object_planet16_object_image2 ))
        (not (power_avail_object_satellite2 )))
    )


    (:action take_image_object_satellite4_object_star9_object_instrument9_object_infrared0
     :parameters ()
     :precondition (and (have_image_object_planet17_object_spectrograph3 ) (have_image_object_star0_object_infrared0 ))
     :effect (and
        (pointing_object_satellite1_object_phenomenon18 )
        (not (pointing_object_satellite1_object_phenomenon12 )))
    )


    (:action turn_to_object_satellite4_object_star3_object_phenomenon11
     :parameters ()
     :precondition (and (satellite_object_satellite1 ) (satellite_object_satellite2 ))
     :effect (and
        (not (pointing_object_satellite3_object_star3 ))
        (not (pointing_object_satellite2_object_star1 ))
        (not (have_image_object_phenomenon15_object_thermograph4 ))
        (not (pointing_object_satellite0_object_phenomenon12 )))
    )


    (:action turn_to_object_satellite0_object_phenomenon11_object_phenomenon15
     :parameters ()
     :precondition (and )
     :effect (and
        (have_image_object_phenomenon11_object_infrared0 )
        (not (have_image_object_planet7_object_image2 ))
        (not (pointing_object_satellite0_object_groundstation4 ))
        (not (pointing_object_satellite1_object_groundstation4 )))
    )


    (:action turn_to_object_satellite4_object_planet7_object_planet5
     :parameters ()
     :precondition (and (pointing_object_satellite1_object_phenomenon11 ) (pointing_object_satellite2_object_star9 ))
     :effect (and
        (pointing_object_satellite0_object_star8 )
        (not (pointing_object_satellite4_object_planet16 ))
        (not (have_image_object_planet16_object_spectrograph3 ))
        (not (have_image_object_star6_object_spectrograph3 )))
    )


    (:action turn_to_object_satellite4_object_star6_object_planet7
     :parameters ()
     :precondition (power_on_object_instrument8 )
     :effect (and
        (power_on_object_instrument1 )
        (pointing_object_satellite2_object_planet17 )
        (not (have_image_object_star9_object_spectrograph3 ))
        (not (pointing_object_satellite0_object_star0 ))
        (not (have_image_object_planet7_object_thermograph1 )))
    )


    (:action turn_to_object_satellite4_object_planet5_object_planet17
     :parameters ()
     :precondition (supports_object_instrument9_object_image2 )
     :effect (and
        (supports_object_instrument1_object_infrared0 )
        (supports_object_instrument6_object_infrared0 )
        (power_on_object_instrument10 )
        (not (have_image_object_star0_object_thermograph4 ))
        (not (have_image_object_planet17_object_thermograph1 )))
    )


    (:action turn_to_object_satellite4_object_phenomenon11_object_star3
     :parameters ()
     :precondition (and (pointing_object_satellite0_object_star8 ) (pointing_object_satellite1_object_star0 ))
     :effect (and
        (have_image_object_phenomenon18_object_image2 )
        (not (pointing_object_satellite2_object_star1 ))
        (not (have_image_object_phenomenon11_object_thermograph4 ))
        (not (on_board_object_instrument3_object_satellite1 )))
    )


    (:action take_image_object_satellite4_object_star8_object_instrument9_object_infrared0
     :parameters ()
     :precondition (and (have_image_object_planet16_object_image2 ) (pointing_object_satellite1_object_phenomenon18 ))
     :effect (and
        (have_image_object_planet17_object_spectrograph3 )
        (not (have_image_object_planet14_object_infrared0 )))
    )


    (:action take_image_object_satellite4_object_planet14_object_instrument9_object_image2
     :parameters ()
     :precondition (direction_object_planet14 )
     :effect (and
        (have_image_object_phenomenon18_object_thermograph1 )
        (pointing_object_satellite4_object_planet13 )
        (power_avail_object_satellite2 )
        (not (direction_object_groundstation4 ))
        (not (pointing_object_satellite2_object_star1 ))
        (not (on_board_object_instrument2_object_satellite0 )))
    )


    (:action take_image_object_satellite4_object_planet5_object_instrument9_object_image2
     :parameters ()
     :precondition (and (pointing_object_satellite0_object_star8 ) (have_image_object_planet17_object_thermograph1 ) (supports_object_instrument1_object_infrared0 ))
     :effect (and
        (pointing_object_satellite2_object_star9 ))
    )


    (:action turn_to_object_satellite4_object_phenomenon11_object_planet7
     :parameters ()
     :precondition (have_image_object_star9_object_thermograph1 )
     :effect (and
        (pointing_object_satellite1_object_star9 )
        (have_image_object_planet17_object_spectrograph3 )
        (have_image_object_phenomenon12_object_thermograph4 )
        (not (pointing_object_satellite4_object_planet16 ))
        (not (have_image_object_phenomenon15_object_image2 ))
        (not (pointing_object_satellite4_object_star1 )))
    )


    (:action turn_to_object_satellite0_object_phenomenon11_object_groundstation4
     :parameters ()
     :precondition (have_image_object_phenomenon15_object_thermograph4 )
     :effect (and
        (pointing_object_satellite0_object_star6 )
        (calibrated_object_instrument0 )
        (direction_object_planet17 )
        (pointing_object_satellite4_object_star0 )
        (not (power_avail_object_satellite3 ))
        (not (have_image_object_planet17_object_thermograph4 ))
        (not (have_image_object_star9_object_image2 ))
        (not (satellite_object_satellite1 ))
        (not (on_board_object_instrument1_object_satellite0 ))
        (not (pointing_object_satellite3_object_phenomenon15 )))
    )


    (:action take_image_object_satellite4_object_phenomenon12_object_instrument9_object_infrared0
     :parameters ()
     :precondition (and (pointing_object_satellite0_object_star8 ) (have_image_object_planet16_object_thermograph4 ))
     :effect (and
        (have_image_object_star8_object_infrared0 )
        (not (have_image_object_groundstation4_object_thermograph1 ))
        (not (calibration_target_object_instrument10_object_groundstation4 )))
    )


    (:action switch_on_object_instrument9_object_satellite4
     :parameters ()
     :precondition (and (direction_object_groundstation2 ) (pointing_object_satellite1_object_star9 ) (supports_object_instrument10_object_image2 ) (have_image_object_phenomenon11_object_thermograph1 ) (pointing_object_satellite4_object_star1 ))
     :effect (and
        (pointing_object_satellite2_object_star8 )
        (have_image_object_planet7_object_infrared0 )
        (not (satellite_object_satellite2 )))
    )


    (:action turn_to_object_satellite0_object_groundstation4_object_groundstation2
     :parameters ()
     :precondition (and (satellite_object_satellite2 ) (pointing_object_satellite4_object_phenomenon11 ) (have_image_object_planet5_object_spectrograph3 ) (pointing_object_satellite2_object_planet16 ))
     :effect (and
        (instrument_object_instrument7 )
        (not (power_on_object_instrument6 ))
        (not (direction_object_groundstation2 )))
    )


    (:action switch_on_object_instrument2_object_satellite0
     :parameters ()
     :precondition (and (pointing_object_satellite4_object_planet16 ) (have_image_object_phenomenon12_object_thermograph4 ) (instrument_object_instrument7 ) (have_image_object_groundstation4_object_thermograph1 ))
     :effect (and
        (pointing_object_satellite2_object_star10 )
        (pointing_object_satellite0_object_planet7 )
        (pointing_object_satellite4_object_phenomenon11 )
        (not (calibrated_object_instrument7 ))
        (not (pointing_object_satellite2_object_groundstation2 )))
    )


    (:action turn_to_object_satellite0_object_phenomenon15_object_phenomenon11
     :parameters ()
     :precondition (and (pointing_object_satellite0_object_planet5 ) (have_image_object_star6_object_image2 ) (calibration_target_object_instrument0_object_star3 ) (instrument_object_instrument0 ))
     :effect (and )
    )


    (:action turn_to_object_satellite4_object_planet13_object_phenomenon12
     :parameters ()
     :precondition (and (supports_object_instrument1_object_infrared0 ) (have_image_object_groundstation4_object_thermograph1 ) (instrument_object_instrument1 ))
     :effect (and
        (pointing_object_satellite4_object_planet7 )
        (not (have_image_object_planet16_object_thermograph4 )))
    )


    (:action turn_to_object_satellite4_object_star8_object_star6
     :parameters ()
     :precondition (and )
     :effect (and
        (mode_object_image2 )
        (pointing_object_satellite1_object_planet17 )
        (not (calibrated_object_instrument8 )))
    )


    (:action take_image_object_satellite4_object_planet13_object_instrument9_object_spectrograph3
     :parameters ()
     :precondition (and (pointing_object_satellite4_object_planet16 ) (pointing_object_satellite0_object_star6 ))
     :effect (and
        (supports_object_instrument1_object_infrared0 )
        (direction_object_planet14 )
        (not (instrument_object_instrument1 )))
    )


    (:action take_image_object_satellite4_object_planet7_object_instrument9_object_spectrograph3
     :parameters ()
     :precondition (and (pointing_object_satellite2_object_planet17 ) (pointing_object_satellite0_object_star0 ) (have_image_object_star6_object_spectrograph3 ))
     :effect (and
        (not (pointing_object_satellite1_object_phenomenon11 )))
    )


    (:action calibrate_object_satellite4_object_instrument9_object_star3
     :parameters ()
     :precondition (pointing_object_satellite3_object_star3 )
     :effect (and
        (supports_object_instrument3_object_thermograph4 )
        (have_image_object_star10_object_thermograph1 )
        (pointing_object_satellite0_object_star8 )
        (not (power_on_object_instrument4 ))
        (not (have_image_object_planet5_object_infrared0 ))
        (not (pointing_object_satellite1_object_phenomenon18 ))
        (not (pointing_object_satellite1_object_star0 ))
        (not (satellite_object_satellite2 ))
        (not (pointing_object_satellite1_object_star1 )))
    )


    (:action turn_to_object_satellite4_object_planet14_object_planet13
     :parameters ()
     :precondition (and (pointing_object_satellite2_object_star1 ) (pointing_object_satellite4_object_planet13 ))
     :effect (and
        (pointing_object_satellite4_object_planet16 )
        (direction_object_star8 )
        (not (pointing_object_satellite0_object_star6 )))
    )


    (:action take_image_object_satellite0_object_phenomenon18_object_instrument2_object_thermograph1
     :parameters ()
     :precondition (have_image_object_star3_object_thermograph4 )
     :effect (and
        (have_image_object_planet7_object_infrared0 )
        (have_image_object_star6_object_image2 )
        (power_avail_object_satellite1 )
        (not (pointing_object_satellite3_object_star10 )))
    )


    (:action take_image_object_satellite0_object_phenomenon15_object_instrument2_object_thermograph1
     :parameters ()
     :precondition (and (calibrated_object_instrument8 ) (mode_object_image2 ))
     :effect (and
        (pointing_object_satellite1_object_groundstation4 )
        (instrument_object_instrument0 )
        (not (have_image_object_star6_object_image2 )))
    )


    (:action turn_to_object_satellite1_object_planet17_object_phenomenon12
     :parameters ()
     :precondition (and (have_image_object_planet5_object_spectrograph3 ) (pointing_object_satellite2_object_star10 ))
     :effect (and
        (have_image_object_groundstation4_object_thermograph1 )
        (pointing_object_satellite2_object_star9 )
        (have_image_object_phenomenon11_object_thermograph1 )
        (not (supports_object_instrument10_object_image2 ))
        (not (direction_object_phenomenon18 )))
    )


    (:action turn_to_object_satellite0_object_phenomenon11_object_phenomenon18
     :parameters ()
     :precondition (and (have_image_object_planet7_object_infrared0 ) (pointing_object_satellite3_object_star10 ))
     :effect (and )
    )


    (:action take_image_object_satellite4_object_phenomenon11_object_instrument9_object_image2
     :parameters ()
     :precondition (and (have_image_object_phenomenon18_object_image2 ) (pointing_object_satellite2_object_planet5 ) (pointing_object_satellite2_object_star1 ))
     :effect (and
        (direction_object_planet14 )
        (pointing_object_satellite4_object_groundstation2 )
        (have_image_object_groundstation2_object_spectrograph3 )
        (pointing_object_satellite2_object_groundstation2 )
        (not (have_image_object_star9_object_spectrograph3 )))
    )


    (:action turn_to_object_satellite4_object_phenomenon12_object_phenomenon11
     :parameters ()
     :precondition (pointing_object_satellite4_object_groundstation2 )
     :effect (and
        (pointing_object_satellite2_object_planet5 )
        (calibrated_object_instrument5 )
        (have_image_object_planet16_object_thermograph4 )
        (not (pointing_object_satellite0_object_planet16 ))
        (not (pointing_object_satellite0_object_star8 )))
    )


    (:action take_image_object_satellite4_object_star6_object_instrument9_object_image2
     :parameters ()
     :precondition (and (pointing_object_satellite1_object_phenomenon12 ) (have_image_object_planet7_object_thermograph1 ))
     :effect (and
        (not (have_image_object_star0_object_infrared0 ))
        (not (power_on_object_instrument8 )))
    )


    (:action take_image_object_satellite4_object_planet17_object_instrument9_object_infrared0
     :parameters ()
     :precondition (and (power_on_object_instrument10 ) (pointing_object_satellite3_object_planet13 ))
     :effect (and
        (supports_object_instrument9_object_image2 )
        (have_image_object_phenomenon12_object_image2 ))
    )


    (:action turn_to_object_satellite0_object_phenomenon18_object_phenomenon11
     :parameters ()
     :precondition (and (pointing_object_satellite0_object_groundstation4 ) (power_avail_object_satellite1 ) (have_image_object_phenomenon11_object_infrared0 ))
     :effect (and
        (have_image_object_star3_object_thermograph4 ))
    )

)